class AirConditionerExecutor {

    public static void main(String[] args) {

        AirConditioner ac1 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac1.acBrand);
        System.out.println("The acId is : " + ac1.acId);
        System.out.println("The acPrice is : " + ac1.acPrice);
        System.out.println("The isAvailable is : " + ac1.isAvailable);
        System.out.println("The acType is : " + ac1.acType);
        System.out.println("The capacityTons is : " + ac1.capacityTons);
        System.out.println("The weight is : " + ac1.weight);
        System.out.println("The isInverter is : " + ac1.isInverter);
        System.out.println("The compressorType is : " + ac1.compressorType);
        System.out.println("The warrantyYears is : " + ac1.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac1.coolingCapacity);
        System.out.println("The hasRemote is : " + ac1.hasRemote);
        System.out.println("The color is : " + ac1.color);
        System.out.println("The stockQuantity is : " + ac1.stockQuantity);
        System.out.println("The powerConsumption is : " + ac1.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac1.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac1.refrigerantType);
        System.out.println("The rating is : " + ac1.rating);
        System.out.println("The airFlowRate is : " + ac1.airFlowRate);
        System.out.println("The isCertified is : " + ac1.isCertified);
        System.out.println("The countryOfOrigin is : " + ac1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac1.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac1.noiseLevel);
        System.out.println("The supportsWifi is : " + ac1.supportsWifi);
        System.out.println("The certificationType is : " + ac1.certificationType);

        ac1.acBrand = "Daikin";
        ac1.acId = 1;
        ac1.acPrice = 1000.99;
        ac1.isAvailable = true;
        ac1.acType = "Split";
        ac1.capacityTons = 1.5;
        ac1.weight = 35.0;
        ac1.isInverter = true;
        ac1.compressorType = "Rotary";
        ac1.warrantyYears = 5;
        ac1.coolingCapacity = 5200.0;
        ac1.hasRemote = true;
        ac1.color = "White";
        ac1.stockQuantity = 15;
        ac1.powerConsumption = 1450.0;
        ac1.isEcoFriendly = true;
        ac1.refrigerantType = "R32";
        ac1.rating = 5;
        ac1.airFlowRate = 600.0;
        ac1.isCertified = true;
        ac1.countryOfOrigin = "India";
        ac1.manufacturingYear = 2025;
        ac1.noiseLevel = 42.0;
        ac1.supportsWifi = true;
        ac1.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac1.acBrand);
        System.out.println("The acId is : " + ac1.acId);
        System.out.println("The acPrice is : " + ac1.acPrice);
        System.out.println("The isAvailable is : " + ac1.isAvailable);
        System.out.println("The acType is : " + ac1.acType);
        System.out.println("The capacityTons is : " + ac1.capacityTons);
        System.out.println("The weight is : " + ac1.weight);
        System.out.println("The isInverter is : " + ac1.isInverter);
        System.out.println("The compressorType is : " + ac1.compressorType);
        System.out.println("The warrantyYears is : " + ac1.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac1.coolingCapacity);
        System.out.println("The hasRemote is : " + ac1.hasRemote);
        System.out.println("The color is : " + ac1.color);
        System.out.println("The stockQuantity is : " + ac1.stockQuantity);
        System.out.println("The powerConsumption is : " + ac1.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac1.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac1.refrigerantType);
        System.out.println("The rating is : " + ac1.rating);
        System.out.println("The airFlowRate is : " + ac1.airFlowRate);
        System.out.println("The isCertified is : " + ac1.isCertified);
        System.out.println("The countryOfOrigin is : " + ac1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac1.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac1.noiseLevel);
        System.out.println("The supportsWifi is : " + ac1.supportsWifi);
        System.out.println("The certificationType is : " + ac1.certificationType);


        AirConditioner ac2 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac2.acBrand);
        System.out.println("The acId is : " + ac2.acId);
        System.out.println("The acPrice is : " + ac2.acPrice);
        System.out.println("The isAvailable is : " + ac2.isAvailable);
        System.out.println("The acType is : " + ac2.acType);
        System.out.println("The capacityTons is : " + ac2.capacityTons);
        System.out.println("The weight is : " + ac2.weight);
        System.out.println("The isInverter is : " + ac2.isInverter);
        System.out.println("The compressorType is : " + ac2.compressorType);
        System.out.println("The warrantyYears is : " + ac2.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac2.coolingCapacity);
        System.out.println("The hasRemote is : " + ac2.hasRemote);
        System.out.println("The color is : " + ac2.color);
        System.out.println("The stockQuantity is : " + ac2.stockQuantity);
        System.out.println("The powerConsumption is : " + ac2.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac2.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac2.refrigerantType);
        System.out.println("The rating is : " + ac2.rating);
        System.out.println("The airFlowRate is : " + ac2.airFlowRate);
        System.out.println("The isCertified is : " + ac2.isCertified);
        System.out.println("The countryOfOrigin is : " + ac2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac2.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac2.noiseLevel);
        System.out.println("The supportsWifi is : " + ac2.supportsWifi);
        System.out.println("The certificationType is : " + ac2.certificationType);

        ac2.acBrand = "Daikin";
        ac2.acId = 2;
        ac2.acPrice = 2000.99;
        ac2.isAvailable = true;
        ac2.acType = "Split";
        ac2.capacityTons = 1.5;
        ac2.weight = 35.0;
        ac2.isInverter = true;
        ac2.compressorType = "Rotary";
        ac2.warrantyYears = 5;
        ac2.coolingCapacity = 5200.0;
        ac2.hasRemote = true;
        ac2.color = "White";
        ac2.stockQuantity = 15;
        ac2.powerConsumption = 1450.0;
        ac2.isEcoFriendly = true;
        ac2.refrigerantType = "R32";
        ac2.rating = 5;
        ac2.airFlowRate = 600.0;
        ac2.isCertified = true;
        ac2.countryOfOrigin = "India";
        ac2.manufacturingYear = 2025;
        ac2.noiseLevel = 42.0;
        ac2.supportsWifi = true;
        ac2.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac2.acBrand);
        System.out.println("The acId is : " + ac2.acId);
        System.out.println("The acPrice is : " + ac2.acPrice);
        System.out.println("The isAvailable is : " + ac2.isAvailable);
        System.out.println("The acType is : " + ac2.acType);
        System.out.println("The capacityTons is : " + ac2.capacityTons);
        System.out.println("The weight is : " + ac2.weight);
        System.out.println("The isInverter is : " + ac2.isInverter);
        System.out.println("The compressorType is : " + ac2.compressorType);
        System.out.println("The warrantyYears is : " + ac2.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac2.coolingCapacity);
        System.out.println("The hasRemote is : " + ac2.hasRemote);
        System.out.println("The color is : " + ac2.color);
        System.out.println("The stockQuantity is : " + ac2.stockQuantity);
        System.out.println("The powerConsumption is : " + ac2.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac2.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac2.refrigerantType);
        System.out.println("The rating is : " + ac2.rating);
        System.out.println("The airFlowRate is : " + ac2.airFlowRate);
        System.out.println("The isCertified is : " + ac2.isCertified);
        System.out.println("The countryOfOrigin is : " + ac2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac2.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac2.noiseLevel);
        System.out.println("The supportsWifi is : " + ac2.supportsWifi);
        System.out.println("The certificationType is : " + ac2.certificationType);


        AirConditioner ac3 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac3.acBrand);
        System.out.println("The acId is : " + ac3.acId);
        System.out.println("The acPrice is : " + ac3.acPrice);
        System.out.println("The isAvailable is : " + ac3.isAvailable);
        System.out.println("The acType is : " + ac3.acType);
        System.out.println("The capacityTons is : " + ac3.capacityTons);
        System.out.println("The weight is : " + ac3.weight);
        System.out.println("The isInverter is : " + ac3.isInverter);
        System.out.println("The compressorType is : " + ac3.compressorType);
        System.out.println("The warrantyYears is : " + ac3.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac3.coolingCapacity);
        System.out.println("The hasRemote is : " + ac3.hasRemote);
        System.out.println("The color is : " + ac3.color);
        System.out.println("The stockQuantity is : " + ac3.stockQuantity);
        System.out.println("The powerConsumption is : " + ac3.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac3.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac3.refrigerantType);
        System.out.println("The rating is : " + ac3.rating);
        System.out.println("The airFlowRate is : " + ac3.airFlowRate);
        System.out.println("The isCertified is : " + ac3.isCertified);
        System.out.println("The countryOfOrigin is : " + ac3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac3.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac3.noiseLevel);
        System.out.println("The supportsWifi is : " + ac3.supportsWifi);
        System.out.println("The certificationType is : " + ac3.certificationType);

        ac3.acBrand = "Daikin";
        ac3.acId = 3;
        ac3.acPrice = 3000.99;
        ac3.isAvailable = true;
        ac3.acType = "Split";
        ac3.capacityTons = 1.5;
        ac3.weight = 35.0;
        ac3.isInverter = true;
        ac3.compressorType = "Rotary";
        ac3.warrantyYears = 5;
        ac3.coolingCapacity = 5200.0;
        ac3.hasRemote = true;
        ac3.color = "White";
        ac3.stockQuantity = 15;
        ac3.powerConsumption = 1450.0;
        ac3.isEcoFriendly = true;
        ac3.refrigerantType = "R32";
        ac3.rating = 5;
        ac3.airFlowRate = 600.0;
        ac3.isCertified = true;
        ac3.countryOfOrigin = "India";
        ac3.manufacturingYear = 2025;
        ac3.noiseLevel = 42.0;
        ac3.supportsWifi = true;
        ac3.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac3.acBrand);
        System.out.println("The acId is : " + ac3.acId);
        System.out.println("The acPrice is : " + ac3.acPrice);
        System.out.println("The isAvailable is : " + ac3.isAvailable);
        System.out.println("The acType is : " + ac3.acType);
        System.out.println("The capacityTons is : " + ac3.capacityTons);
        System.out.println("The weight is : " + ac3.weight);
        System.out.println("The isInverter is : " + ac3.isInverter);
        System.out.println("The compressorType is : " + ac3.compressorType);
        System.out.println("The warrantyYears is : " + ac3.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac3.coolingCapacity);
        System.out.println("The hasRemote is : " + ac3.hasRemote);
        System.out.println("The color is : " + ac3.color);
        System.out.println("The stockQuantity is : " + ac3.stockQuantity);
        System.out.println("The powerConsumption is : " + ac3.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac3.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac3.refrigerantType);
        System.out.println("The rating is : " + ac3.rating);
        System.out.println("The airFlowRate is : " + ac3.airFlowRate);
        System.out.println("The isCertified is : " + ac3.isCertified);
        System.out.println("The countryOfOrigin is : " + ac3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac3.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac3.noiseLevel);
        System.out.println("The supportsWifi is : " + ac3.supportsWifi);
        System.out.println("The certificationType is : " + ac3.certificationType);


        AirConditioner ac4 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac4.acBrand);
        System.out.println("The acId is : " + ac4.acId);
        System.out.println("The acPrice is : " + ac4.acPrice);
        System.out.println("The isAvailable is : " + ac4.isAvailable);
        System.out.println("The acType is : " + ac4.acType);
        System.out.println("The capacityTons is : " + ac4.capacityTons);
        System.out.println("The weight is : " + ac4.weight);
        System.out.println("The isInverter is : " + ac4.isInverter);
        System.out.println("The compressorType is : " + ac4.compressorType);
        System.out.println("The warrantyYears is : " + ac4.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac4.coolingCapacity);
        System.out.println("The hasRemote is : " + ac4.hasRemote);
        System.out.println("The color is : " + ac4.color);
        System.out.println("The stockQuantity is : " + ac4.stockQuantity);
        System.out.println("The powerConsumption is : " + ac4.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac4.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac4.refrigerantType);
        System.out.println("The rating is : " + ac4.rating);
        System.out.println("The airFlowRate is : " + ac4.airFlowRate);
        System.out.println("The isCertified is : " + ac4.isCertified);
        System.out.println("The countryOfOrigin is : " + ac4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac4.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac4.noiseLevel);
        System.out.println("The supportsWifi is : " + ac4.supportsWifi);
        System.out.println("The certificationType is : " + ac4.certificationType);

        ac4.acBrand = "Daikin";
        ac4.acId = 4;
        ac4.acPrice = 4000.99;
        ac4.isAvailable = true;
        ac4.acType = "Split";
        ac4.capacityTons = 1.5;
        ac4.weight = 35.0;
        ac4.isInverter = true;
        ac4.compressorType = "Rotary";
        ac4.warrantyYears = 5;
        ac4.coolingCapacity = 5200.0;
        ac4.hasRemote = true;
        ac4.color = "White";
        ac4.stockQuantity = 15;
        ac4.powerConsumption = 1450.0;
        ac4.isEcoFriendly = true;
        ac4.refrigerantType = "R32";
        ac4.rating = 5;
        ac4.airFlowRate = 600.0;
        ac4.isCertified = true;
        ac4.countryOfOrigin = "India";
        ac4.manufacturingYear = 2025;
        ac4.noiseLevel = 42.0;
        ac4.supportsWifi = true;
        ac4.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac4.acBrand);
        System.out.println("The acId is : " + ac4.acId);
        System.out.println("The acPrice is : " + ac4.acPrice);
        System.out.println("The isAvailable is : " + ac4.isAvailable);
        System.out.println("The acType is : " + ac4.acType);
        System.out.println("The capacityTons is : " + ac4.capacityTons);
        System.out.println("The weight is : " + ac4.weight);
        System.out.println("The isInverter is : " + ac4.isInverter);
        System.out.println("The compressorType is : " + ac4.compressorType);
        System.out.println("The warrantyYears is : " + ac4.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac4.coolingCapacity);
        System.out.println("The hasRemote is : " + ac4.hasRemote);
        System.out.println("The color is : " + ac4.color);
        System.out.println("The stockQuantity is : " + ac4.stockQuantity);
        System.out.println("The powerConsumption is : " + ac4.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac4.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac4.refrigerantType);
        System.out.println("The rating is : " + ac4.rating);
        System.out.println("The airFlowRate is : " + ac4.airFlowRate);
        System.out.println("The isCertified is : " + ac4.isCertified);
        System.out.println("The countryOfOrigin is : " + ac4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac4.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac4.noiseLevel);
        System.out.println("The supportsWifi is : " + ac4.supportsWifi);
        System.out.println("The certificationType is : " + ac4.certificationType);


        AirConditioner ac5 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac5.acBrand);
        System.out.println("The acId is : " + ac5.acId);
        System.out.println("The acPrice is : " + ac5.acPrice);
        System.out.println("The isAvailable is : " + ac5.isAvailable);
        System.out.println("The acType is : " + ac5.acType);
        System.out.println("The capacityTons is : " + ac5.capacityTons);
        System.out.println("The weight is : " + ac5.weight);
        System.out.println("The isInverter is : " + ac5.isInverter);
        System.out.println("The compressorType is : " + ac5.compressorType);
        System.out.println("The warrantyYears is : " + ac5.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac5.coolingCapacity);
        System.out.println("The hasRemote is : " + ac5.hasRemote);
        System.out.println("The color is : " + ac5.color);
        System.out.println("The stockQuantity is : " + ac5.stockQuantity);
        System.out.println("The powerConsumption is : " + ac5.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac5.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac5.refrigerantType);
        System.out.println("The rating is : " + ac5.rating);
        System.out.println("The airFlowRate is : " + ac5.airFlowRate);
        System.out.println("The isCertified is : " + ac5.isCertified);
        System.out.println("The countryOfOrigin is : " + ac5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac5.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac5.noiseLevel);
        System.out.println("The supportsWifi is : " + ac5.supportsWifi);
        System.out.println("The certificationType is : " + ac5.certificationType);

        ac5.acBrand = "Daikin";
        ac5.acId = 5;
        ac5.acPrice = 5000.99;
        ac5.isAvailable = true;
        ac5.acType = "Split";
        ac5.capacityTons = 1.5;
        ac5.weight = 35.0;
        ac5.isInverter = true;
        ac5.compressorType = "Rotary";
        ac5.warrantyYears = 5;
        ac5.coolingCapacity = 5200.0;
        ac5.hasRemote = true;
        ac5.color = "White";
        ac5.stockQuantity = 15;
        ac5.powerConsumption = 1450.0;
        ac5.isEcoFriendly = true;
        ac5.refrigerantType = "R32";
        ac5.rating = 5;
        ac5.airFlowRate = 600.0;
        ac5.isCertified = true;
        ac5.countryOfOrigin = "India";
        ac5.manufacturingYear = 2025;
        ac5.noiseLevel = 42.0;
        ac5.supportsWifi = true;
        ac5.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac5.acBrand);
        System.out.println("The acId is : " + ac5.acId);
        System.out.println("The acPrice is : " + ac5.acPrice);
        System.out.println("The isAvailable is : " + ac5.isAvailable);
        System.out.println("The acType is : " + ac5.acType);
        System.out.println("The capacityTons is : " + ac5.capacityTons);
        System.out.println("The weight is : " + ac5.weight);
        System.out.println("The isInverter is : " + ac5.isInverter);
        System.out.println("The compressorType is : " + ac5.compressorType);
        System.out.println("The warrantyYears is : " + ac5.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac5.coolingCapacity);
        System.out.println("The hasRemote is : " + ac5.hasRemote);
        System.out.println("The color is : " + ac5.color);
        System.out.println("The stockQuantity is : " + ac5.stockQuantity);
        System.out.println("The powerConsumption is : " + ac5.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac5.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac5.refrigerantType);
        System.out.println("The rating is : " + ac5.rating);
        System.out.println("The airFlowRate is : " + ac5.airFlowRate);
        System.out.println("The isCertified is : " + ac5.isCertified);
        System.out.println("The countryOfOrigin is : " + ac5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac5.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac5.noiseLevel);
        System.out.println("The supportsWifi is : " + ac5.supportsWifi);
        System.out.println("The certificationType is : " + ac5.certificationType);


        AirConditioner ac6 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac6.acBrand);
        System.out.println("The acId is : " + ac6.acId);
        System.out.println("The acPrice is : " + ac6.acPrice);
        System.out.println("The isAvailable is : " + ac6.isAvailable);
        System.out.println("The acType is : " + ac6.acType);
        System.out.println("The capacityTons is : " + ac6.capacityTons);
        System.out.println("The weight is : " + ac6.weight);
        System.out.println("The isInverter is : " + ac6.isInverter);
        System.out.println("The compressorType is : " + ac6.compressorType);
        System.out.println("The warrantyYears is : " + ac6.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac6.coolingCapacity);
        System.out.println("The hasRemote is : " + ac6.hasRemote);
        System.out.println("The color is : " + ac6.color);
        System.out.println("The stockQuantity is : " + ac6.stockQuantity);
        System.out.println("The powerConsumption is : " + ac6.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac6.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac6.refrigerantType);
        System.out.println("The rating is : " + ac6.rating);
        System.out.println("The airFlowRate is : " + ac6.airFlowRate);
        System.out.println("The isCertified is : " + ac6.isCertified);
        System.out.println("The countryOfOrigin is : " + ac6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac6.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac6.noiseLevel);
        System.out.println("The supportsWifi is : " + ac6.supportsWifi);
        System.out.println("The certificationType is : " + ac6.certificationType);

        ac6.acBrand = "Daikin";
        ac6.acId = 6;
        ac6.acPrice = 6000.99;
        ac6.isAvailable = true;
        ac6.acType = "Split";
        ac6.capacityTons = 1.5;
        ac6.weight = 35.0;
        ac6.isInverter = true;
        ac6.compressorType = "Rotary";
        ac6.warrantyYears = 5;
        ac6.coolingCapacity = 5200.0;
        ac6.hasRemote = true;
        ac6.color = "White";
        ac6.stockQuantity = 15;
        ac6.powerConsumption = 1450.0;
        ac6.isEcoFriendly = true;
        ac6.refrigerantType = "R32";
        ac6.rating = 5;
        ac6.airFlowRate = 600.0;
        ac6.isCertified = true;
        ac6.countryOfOrigin = "India";
        ac6.manufacturingYear = 2025;
        ac6.noiseLevel = 42.0;
        ac6.supportsWifi = true;
        ac6.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac6.acBrand);
        System.out.println("The acId is : " + ac6.acId);
        System.out.println("The acPrice is : " + ac6.acPrice);
        System.out.println("The isAvailable is : " + ac6.isAvailable);
        System.out.println("The acType is : " + ac6.acType);
        System.out.println("The capacityTons is : " + ac6.capacityTons);
        System.out.println("The weight is : " + ac6.weight);
        System.out.println("The isInverter is : " + ac6.isInverter);
        System.out.println("The compressorType is : " + ac6.compressorType);
        System.out.println("The warrantyYears is : " + ac6.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac6.coolingCapacity);
        System.out.println("The hasRemote is : " + ac6.hasRemote);
        System.out.println("The color is : " + ac6.color);
        System.out.println("The stockQuantity is : " + ac6.stockQuantity);
        System.out.println("The powerConsumption is : " + ac6.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac6.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac6.refrigerantType);
        System.out.println("The rating is : " + ac6.rating);
        System.out.println("The airFlowRate is : " + ac6.airFlowRate);
        System.out.println("The isCertified is : " + ac6.isCertified);
        System.out.println("The countryOfOrigin is : " + ac6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac6.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac6.noiseLevel);
        System.out.println("The supportsWifi is : " + ac6.supportsWifi);
        System.out.println("The certificationType is : " + ac6.certificationType);


        AirConditioner ac7 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac7.acBrand);
        System.out.println("The acId is : " + ac7.acId);
        System.out.println("The acPrice is : " + ac7.acPrice);
        System.out.println("The isAvailable is : " + ac7.isAvailable);
        System.out.println("The acType is : " + ac7.acType);
        System.out.println("The capacityTons is : " + ac7.capacityTons);
        System.out.println("The weight is : " + ac7.weight);
        System.out.println("The isInverter is : " + ac7.isInverter);
        System.out.println("The compressorType is : " + ac7.compressorType);
        System.out.println("The warrantyYears is : " + ac7.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac7.coolingCapacity);
        System.out.println("The hasRemote is : " + ac7.hasRemote);
        System.out.println("The color is : " + ac7.color);
        System.out.println("The stockQuantity is : " + ac7.stockQuantity);
        System.out.println("The powerConsumption is : " + ac7.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac7.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac7.refrigerantType);
        System.out.println("The rating is : " + ac7.rating);
        System.out.println("The airFlowRate is : " + ac7.airFlowRate);
        System.out.println("The isCertified is : " + ac7.isCertified);
        System.out.println("The countryOfOrigin is : " + ac7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac7.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac7.noiseLevel);
        System.out.println("The supportsWifi is : " + ac7.supportsWifi);
        System.out.println("The certificationType is : " + ac7.certificationType);

        ac7.acBrand = "Daikin";
        ac7.acId = 7;
        ac7.acPrice = 7000.99;
        ac7.isAvailable = true;
        ac7.acType = "Split";
        ac7.capacityTons = 1.5;
        ac7.weight = 35.0;
        ac7.isInverter = true;
        ac7.compressorType = "Rotary";
        ac7.warrantyYears = 5;
        ac7.coolingCapacity = 5200.0;
        ac7.hasRemote = true;
        ac7.color = "White";
        ac7.stockQuantity = 15;
        ac7.powerConsumption = 1450.0;
        ac7.isEcoFriendly = true;
        ac7.refrigerantType = "R32";
        ac7.rating = 5;
        ac7.airFlowRate = 600.0;
        ac7.isCertified = true;
        ac7.countryOfOrigin = "India";
        ac7.manufacturingYear = 2025;
        ac7.noiseLevel = 42.0;
        ac7.supportsWifi = true;
        ac7.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac7.acBrand);
        System.out.println("The acId is : " + ac7.acId);
        System.out.println("The acPrice is : " + ac7.acPrice);
        System.out.println("The isAvailable is : " + ac7.isAvailable);
        System.out.println("The acType is : " + ac7.acType);
        System.out.println("The capacityTons is : " + ac7.capacityTons);
        System.out.println("The weight is : " + ac7.weight);
        System.out.println("The isInverter is : " + ac7.isInverter);
        System.out.println("The compressorType is : " + ac7.compressorType);
        System.out.println("The warrantyYears is : " + ac7.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac7.coolingCapacity);
        System.out.println("The hasRemote is : " + ac7.hasRemote);
        System.out.println("The color is : " + ac7.color);
        System.out.println("The stockQuantity is : " + ac7.stockQuantity);
        System.out.println("The powerConsumption is : " + ac7.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac7.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac7.refrigerantType);
        System.out.println("The rating is : " + ac7.rating);
        System.out.println("The airFlowRate is : " + ac7.airFlowRate);
        System.out.println("The isCertified is : " + ac7.isCertified);
        System.out.println("The countryOfOrigin is : " + ac7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac7.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac7.noiseLevel);
        System.out.println("The supportsWifi is : " + ac7.supportsWifi);
        System.out.println("The certificationType is : " + ac7.certificationType);


        AirConditioner ac8 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac8.acBrand);
        System.out.println("The acId is : " + ac8.acId);
        System.out.println("The acPrice is : " + ac8.acPrice);
        System.out.println("The isAvailable is : " + ac8.isAvailable);
        System.out.println("The acType is : " + ac8.acType);
        System.out.println("The capacityTons is : " + ac8.capacityTons);
        System.out.println("The weight is : " + ac8.weight);
        System.out.println("The isInverter is : " + ac8.isInverter);
        System.out.println("The compressorType is : " + ac8.compressorType);
        System.out.println("The warrantyYears is : " + ac8.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac8.coolingCapacity);
        System.out.println("The hasRemote is : " + ac8.hasRemote);
        System.out.println("The color is : " + ac8.color);
        System.out.println("The stockQuantity is : " + ac8.stockQuantity);
        System.out.println("The powerConsumption is : " + ac8.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac8.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac8.refrigerantType);
        System.out.println("The rating is : " + ac8.rating);
        System.out.println("The airFlowRate is : " + ac8.airFlowRate);
        System.out.println("The isCertified is : " + ac8.isCertified);
        System.out.println("The countryOfOrigin is : " + ac8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac8.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac8.noiseLevel);
        System.out.println("The supportsWifi is : " + ac8.supportsWifi);
        System.out.println("The certificationType is : " + ac8.certificationType);

        ac8.acBrand = "Daikin";
        ac8.acId = 8;
        ac8.acPrice = 8000.99;
        ac8.isAvailable = true;
        ac8.acType = "Split";
        ac8.capacityTons = 1.5;
        ac8.weight = 35.0;
        ac8.isInverter = true;
        ac8.compressorType = "Rotary";
        ac8.warrantyYears = 5;
        ac8.coolingCapacity = 5200.0;
        ac8.hasRemote = true;
        ac8.color = "White";
        ac8.stockQuantity = 15;
        ac8.powerConsumption = 1450.0;
        ac8.isEcoFriendly = true;
        ac8.refrigerantType = "R32";
        ac8.rating = 5;
        ac8.airFlowRate = 600.0;
        ac8.isCertified = true;
        ac8.countryOfOrigin = "India";
        ac8.manufacturingYear = 2025;
        ac8.noiseLevel = 42.0;
        ac8.supportsWifi = true;
        ac8.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac8.acBrand);
        System.out.println("The acId is : " + ac8.acId);
        System.out.println("The acPrice is : " + ac8.acPrice);
        System.out.println("The isAvailable is : " + ac8.isAvailable);
        System.out.println("The acType is : " + ac8.acType);
        System.out.println("The capacityTons is : " + ac8.capacityTons);
        System.out.println("The weight is : " + ac8.weight);
        System.out.println("The isInverter is : " + ac8.isInverter);
        System.out.println("The compressorType is : " + ac8.compressorType);
        System.out.println("The warrantyYears is : " + ac8.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac8.coolingCapacity);
        System.out.println("The hasRemote is : " + ac8.hasRemote);
        System.out.println("The color is : " + ac8.color);
        System.out.println("The stockQuantity is : " + ac8.stockQuantity);
        System.out.println("The powerConsumption is : " + ac8.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac8.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac8.refrigerantType);
        System.out.println("The rating is : " + ac8.rating);
        System.out.println("The airFlowRate is : " + ac8.airFlowRate);
        System.out.println("The isCertified is : " + ac8.isCertified);
        System.out.println("The countryOfOrigin is : " + ac8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac8.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac8.noiseLevel);
        System.out.println("The supportsWifi is : " + ac8.supportsWifi);
        System.out.println("The certificationType is : " + ac8.certificationType);


        AirConditioner ac9 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac9.acBrand);
        System.out.println("The acId is : " + ac9.acId);
        System.out.println("The acPrice is : " + ac9.acPrice);
        System.out.println("The isAvailable is : " + ac9.isAvailable);
        System.out.println("The acType is : " + ac9.acType);
        System.out.println("The capacityTons is : " + ac9.capacityTons);
        System.out.println("The weight is : " + ac9.weight);
        System.out.println("The isInverter is : " + ac9.isInverter);
        System.out.println("The compressorType is : " + ac9.compressorType);
        System.out.println("The warrantyYears is : " + ac9.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac9.coolingCapacity);
        System.out.println("The hasRemote is : " + ac9.hasRemote);
        System.out.println("The color is : " + ac9.color);
        System.out.println("The stockQuantity is : " + ac9.stockQuantity);
        System.out.println("The powerConsumption is : " + ac9.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac9.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac9.refrigerantType);
        System.out.println("The rating is : " + ac9.rating);
        System.out.println("The airFlowRate is : " + ac9.airFlowRate);
        System.out.println("The isCertified is : " + ac9.isCertified);
        System.out.println("The countryOfOrigin is : " + ac9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac9.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac9.noiseLevel);
        System.out.println("The supportsWifi is : " + ac9.supportsWifi);
        System.out.println("The certificationType is : " + ac9.certificationType);

        ac9.acBrand = "Daikin";
        ac9.acId = 9;
        ac9.acPrice = 9000.99;
        ac9.isAvailable = true;
        ac9.acType = "Split";
        ac9.capacityTons = 1.5;
        ac9.weight = 35.0;
        ac9.isInverter = true;
        ac9.compressorType = "Rotary";
        ac9.warrantyYears = 5;
        ac9.coolingCapacity = 5200.0;
        ac9.hasRemote = true;
        ac9.color = "White";
        ac9.stockQuantity = 15;
        ac9.powerConsumption = 1450.0;
        ac9.isEcoFriendly = true;
        ac9.refrigerantType = "R32";
        ac9.rating = 5;
        ac9.airFlowRate = 600.0;
        ac9.isCertified = true;
        ac9.countryOfOrigin = "India";
        ac9.manufacturingYear = 2025;
        ac9.noiseLevel = 42.0;
        ac9.supportsWifi = true;
        ac9.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac9.acBrand);
        System.out.println("The acId is : " + ac9.acId);
        System.out.println("The acPrice is : " + ac9.acPrice);
        System.out.println("The isAvailable is : " + ac9.isAvailable);
        System.out.println("The acType is : " + ac9.acType);
        System.out.println("The capacityTons is : " + ac9.capacityTons);
        System.out.println("The weight is : " + ac9.weight);
        System.out.println("The isInverter is : " + ac9.isInverter);
        System.out.println("The compressorType is : " + ac9.compressorType);
        System.out.println("The warrantyYears is : " + ac9.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac9.coolingCapacity);
        System.out.println("The hasRemote is : " + ac9.hasRemote);
        System.out.println("The color is : " + ac9.color);
        System.out.println("The stockQuantity is : " + ac9.stockQuantity);
        System.out.println("The powerConsumption is : " + ac9.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac9.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac9.refrigerantType);
        System.out.println("The rating is : " + ac9.rating);
        System.out.println("The airFlowRate is : " + ac9.airFlowRate);
        System.out.println("The isCertified is : " + ac9.isCertified);
        System.out.println("The countryOfOrigin is : " + ac9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac9.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac9.noiseLevel);
        System.out.println("The supportsWifi is : " + ac9.supportsWifi);
        System.out.println("The certificationType is : " + ac9.certificationType);


        AirConditioner ac10 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac10.acBrand);
        System.out.println("The acId is : " + ac10.acId);
        System.out.println("The acPrice is : " + ac10.acPrice);
        System.out.println("The isAvailable is : " + ac10.isAvailable);
        System.out.println("The acType is : " + ac10.acType);
        System.out.println("The capacityTons is : " + ac10.capacityTons);
        System.out.println("The weight is : " + ac10.weight);
        System.out.println("The isInverter is : " + ac10.isInverter);
        System.out.println("The compressorType is : " + ac10.compressorType);
        System.out.println("The warrantyYears is : " + ac10.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac10.coolingCapacity);
        System.out.println("The hasRemote is : " + ac10.hasRemote);
        System.out.println("The color is : " + ac10.color);
        System.out.println("The stockQuantity is : " + ac10.stockQuantity);
        System.out.println("The powerConsumption is : " + ac10.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac10.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac10.refrigerantType);
        System.out.println("The rating is : " + ac10.rating);
        System.out.println("The airFlowRate is : " + ac10.airFlowRate);
        System.out.println("The isCertified is : " + ac10.isCertified);
        System.out.println("The countryOfOrigin is : " + ac10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac10.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac10.noiseLevel);
        System.out.println("The supportsWifi is : " + ac10.supportsWifi);
        System.out.println("The certificationType is : " + ac10.certificationType);

        ac10.acBrand = "Daikin";
        ac10.acId = 10;
        ac10.acPrice = 10000.99;
        ac10.isAvailable = true;
        ac10.acType = "Split";
        ac10.capacityTons = 1.5;
        ac10.weight = 35.0;
        ac10.isInverter = true;
        ac10.compressorType = "Rotary";
        ac10.warrantyYears = 5;
        ac10.coolingCapacity = 5200.0;
        ac10.hasRemote = true;
        ac10.color = "White";
        ac10.stockQuantity = 15;
        ac10.powerConsumption = 1450.0;
        ac10.isEcoFriendly = true;
        ac10.refrigerantType = "R32";
        ac10.rating = 5;
        ac10.airFlowRate = 600.0;
        ac10.isCertified = true;
        ac10.countryOfOrigin = "India";
        ac10.manufacturingYear = 2025;
        ac10.noiseLevel = 42.0;
        ac10.supportsWifi = true;
        ac10.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac10.acBrand);
        System.out.println("The acId is : " + ac10.acId);
        System.out.println("The acPrice is : " + ac10.acPrice);
        System.out.println("The isAvailable is : " + ac10.isAvailable);
        System.out.println("The acType is : " + ac10.acType);
        System.out.println("The capacityTons is : " + ac10.capacityTons);
        System.out.println("The weight is : " + ac10.weight);
        System.out.println("The isInverter is : " + ac10.isInverter);
        System.out.println("The compressorType is : " + ac10.compressorType);
        System.out.println("The warrantyYears is : " + ac10.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac10.coolingCapacity);
        System.out.println("The hasRemote is : " + ac10.hasRemote);
        System.out.println("The color is : " + ac10.color);
        System.out.println("The stockQuantity is : " + ac10.stockQuantity);
        System.out.println("The powerConsumption is : " + ac10.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac10.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac10.refrigerantType);
        System.out.println("The rating is : " + ac10.rating);
        System.out.println("The airFlowRate is : " + ac10.airFlowRate);
        System.out.println("The isCertified is : " + ac10.isCertified);
        System.out.println("The countryOfOrigin is : " + ac10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac10.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac10.noiseLevel);
        System.out.println("The supportsWifi is : " + ac10.supportsWifi);
        System.out.println("The certificationType is : " + ac10.certificationType);


        AirConditioner ac11 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac11.acBrand);
        System.out.println("The acId is : " + ac11.acId);
        System.out.println("The acPrice is : " + ac11.acPrice);
        System.out.println("The isAvailable is : " + ac11.isAvailable);
        System.out.println("The acType is : " + ac11.acType);
        System.out.println("The capacityTons is : " + ac11.capacityTons);
        System.out.println("The weight is : " + ac11.weight);
        System.out.println("The isInverter is : " + ac11.isInverter);
        System.out.println("The compressorType is : " + ac11.compressorType);
        System.out.println("The warrantyYears is : " + ac11.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac11.coolingCapacity);
        System.out.println("The hasRemote is : " + ac11.hasRemote);
        System.out.println("The color is : " + ac11.color);
        System.out.println("The stockQuantity is : " + ac11.stockQuantity);
        System.out.println("The powerConsumption is : " + ac11.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac11.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac11.refrigerantType);
        System.out.println("The rating is : " + ac11.rating);
        System.out.println("The airFlowRate is : " + ac11.airFlowRate);
        System.out.println("The isCertified is : " + ac11.isCertified);
        System.out.println("The countryOfOrigin is : " + ac11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac11.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac11.noiseLevel);
        System.out.println("The supportsWifi is : " + ac11.supportsWifi);
        System.out.println("The certificationType is : " + ac11.certificationType);

        ac11.acBrand = "Daikin";
        ac11.acId = 11;
        ac11.acPrice = 11000.99;
        ac11.isAvailable = true;
        ac11.acType = "Split";
        ac11.capacityTons = 1.5;
        ac11.weight = 35.0;
        ac11.isInverter = true;
        ac11.compressorType = "Rotary";
        ac11.warrantyYears = 5;
        ac11.coolingCapacity = 5200.0;
        ac11.hasRemote = true;
        ac11.color = "White";
        ac11.stockQuantity = 15;
        ac11.powerConsumption = 1450.0;
        ac11.isEcoFriendly = true;
        ac11.refrigerantType = "R32";
        ac11.rating = 5;
        ac11.airFlowRate = 600.0;
        ac11.isCertified = true;
        ac11.countryOfOrigin = "India";
        ac11.manufacturingYear = 2025;
        ac11.noiseLevel = 42.0;
        ac11.supportsWifi = true;
        ac11.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac11.acBrand);
        System.out.println("The acId is : " + ac11.acId);
        System.out.println("The acPrice is : " + ac11.acPrice);
        System.out.println("The isAvailable is : " + ac11.isAvailable);
        System.out.println("The acType is : " + ac11.acType);
        System.out.println("The capacityTons is : " + ac11.capacityTons);
        System.out.println("The weight is : " + ac11.weight);
        System.out.println("The isInverter is : " + ac11.isInverter);
        System.out.println("The compressorType is : " + ac11.compressorType);
        System.out.println("The warrantyYears is : " + ac11.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac11.coolingCapacity);
        System.out.println("The hasRemote is : " + ac11.hasRemote);
        System.out.println("The color is : " + ac11.color);
        System.out.println("The stockQuantity is : " + ac11.stockQuantity);
        System.out.println("The powerConsumption is : " + ac11.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac11.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac11.refrigerantType);
        System.out.println("The rating is : " + ac11.rating);
        System.out.println("The airFlowRate is : " + ac11.airFlowRate);
        System.out.println("The isCertified is : " + ac11.isCertified);
        System.out.println("The countryOfOrigin is : " + ac11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac11.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac11.noiseLevel);
        System.out.println("The supportsWifi is : " + ac11.supportsWifi);
        System.out.println("The certificationType is : " + ac11.certificationType);


        AirConditioner ac12 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac12.acBrand);
        System.out.println("The acId is : " + ac12.acId);
        System.out.println("The acPrice is : " + ac12.acPrice);
        System.out.println("The isAvailable is : " + ac12.isAvailable);
        System.out.println("The acType is : " + ac12.acType);
        System.out.println("The capacityTons is : " + ac12.capacityTons);
        System.out.println("The weight is : " + ac12.weight);
        System.out.println("The isInverter is : " + ac12.isInverter);
        System.out.println("The compressorType is : " + ac12.compressorType);
        System.out.println("The warrantyYears is : " + ac12.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac12.coolingCapacity);
        System.out.println("The hasRemote is : " + ac12.hasRemote);
        System.out.println("The color is : " + ac12.color);
        System.out.println("The stockQuantity is : " + ac12.stockQuantity);
        System.out.println("The powerConsumption is : " + ac12.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac12.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac12.refrigerantType);
        System.out.println("The rating is : " + ac12.rating);
        System.out.println("The airFlowRate is : " + ac12.airFlowRate);
        System.out.println("The isCertified is : " + ac12.isCertified);
        System.out.println("The countryOfOrigin is : " + ac12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac12.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac12.noiseLevel);
        System.out.println("The supportsWifi is : " + ac12.supportsWifi);
        System.out.println("The certificationType is : " + ac12.certificationType);

        ac12.acBrand = "Daikin";
        ac12.acId = 12;
        ac12.acPrice = 12000.99;
        ac12.isAvailable = true;
        ac12.acType = "Split";
        ac12.capacityTons = 1.5;
        ac12.weight = 35.0;
        ac12.isInverter = true;
        ac12.compressorType = "Rotary";
        ac12.warrantyYears = 5;
        ac12.coolingCapacity = 5200.0;
        ac12.hasRemote = true;
        ac12.color = "White";
        ac12.stockQuantity = 15;
        ac12.powerConsumption = 1450.0;
        ac12.isEcoFriendly = true;
        ac12.refrigerantType = "R32";
        ac12.rating = 5;
        ac12.airFlowRate = 600.0;
        ac12.isCertified = true;
        ac12.countryOfOrigin = "India";
        ac12.manufacturingYear = 2025;
        ac12.noiseLevel = 42.0;
        ac12.supportsWifi = true;
        ac12.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac12.acBrand);
        System.out.println("The acId is : " + ac12.acId);
        System.out.println("The acPrice is : " + ac12.acPrice);
        System.out.println("The isAvailable is : " + ac12.isAvailable);
        System.out.println("The acType is : " + ac12.acType);
        System.out.println("The capacityTons is : " + ac12.capacityTons);
        System.out.println("The weight is : " + ac12.weight);
        System.out.println("The isInverter is : " + ac12.isInverter);
        System.out.println("The compressorType is : " + ac12.compressorType);
        System.out.println("The warrantyYears is : " + ac12.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac12.coolingCapacity);
        System.out.println("The hasRemote is : " + ac12.hasRemote);
        System.out.println("The color is : " + ac12.color);
        System.out.println("The stockQuantity is : " + ac12.stockQuantity);
        System.out.println("The powerConsumption is : " + ac12.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac12.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac12.refrigerantType);
        System.out.println("The rating is : " + ac12.rating);
        System.out.println("The airFlowRate is : " + ac12.airFlowRate);
        System.out.println("The isCertified is : " + ac12.isCertified);
        System.out.println("The countryOfOrigin is : " + ac12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac12.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac12.noiseLevel);
        System.out.println("The supportsWifi is : " + ac12.supportsWifi);
        System.out.println("The certificationType is : " + ac12.certificationType);


        AirConditioner ac13 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac13.acBrand);
        System.out.println("The acId is : " + ac13.acId);
        System.out.println("The acPrice is : " + ac13.acPrice);
        System.out.println("The isAvailable is : " + ac13.isAvailable);
        System.out.println("The acType is : " + ac13.acType);
        System.out.println("The capacityTons is : " + ac13.capacityTons);
        System.out.println("The weight is : " + ac13.weight);
        System.out.println("The isInverter is : " + ac13.isInverter);
        System.out.println("The compressorType is : " + ac13.compressorType);
        System.out.println("The warrantyYears is : " + ac13.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac13.coolingCapacity);
        System.out.println("The hasRemote is : " + ac13.hasRemote);
        System.out.println("The color is : " + ac13.color);
        System.out.println("The stockQuantity is : " + ac13.stockQuantity);
        System.out.println("The powerConsumption is : " + ac13.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac13.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac13.refrigerantType);
        System.out.println("The rating is : " + ac13.rating);
        System.out.println("The airFlowRate is : " + ac13.airFlowRate);
        System.out.println("The isCertified is : " + ac13.isCertified);
        System.out.println("The countryOfOrigin is : " + ac13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac13.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac13.noiseLevel);
        System.out.println("The supportsWifi is : " + ac13.supportsWifi);
        System.out.println("The certificationType is : " + ac13.certificationType);

        ac13.acBrand = "Daikin";
        ac13.acId = 13;
        ac13.acPrice = 13000.99;
        ac13.isAvailable = true;
        ac13.acType = "Split";
        ac13.capacityTons = 1.5;
        ac13.weight = 35.0;
        ac13.isInverter = true;
        ac13.compressorType = "Rotary";
        ac13.warrantyYears = 5;
        ac13.coolingCapacity = 5200.0;
        ac13.hasRemote = true;
        ac13.color = "White";
        ac13.stockQuantity = 15;
        ac13.powerConsumption = 1450.0;
        ac13.isEcoFriendly = true;
        ac13.refrigerantType = "R32";
        ac13.rating = 5;
        ac13.airFlowRate = 600.0;
        ac13.isCertified = true;
        ac13.countryOfOrigin = "India";
        ac13.manufacturingYear = 2025;
        ac13.noiseLevel = 42.0;
        ac13.supportsWifi = true;
        ac13.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac13.acBrand);
        System.out.println("The acId is : " + ac13.acId);
        System.out.println("The acPrice is : " + ac13.acPrice);
        System.out.println("The isAvailable is : " + ac13.isAvailable);
        System.out.println("The acType is : " + ac13.acType);
        System.out.println("The capacityTons is : " + ac13.capacityTons);
        System.out.println("The weight is : " + ac13.weight);
        System.out.println("The isInverter is : " + ac13.isInverter);
        System.out.println("The compressorType is : " + ac13.compressorType);
        System.out.println("The warrantyYears is : " + ac13.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac13.coolingCapacity);
        System.out.println("The hasRemote is : " + ac13.hasRemote);
        System.out.println("The color is : " + ac13.color);
        System.out.println("The stockQuantity is : " + ac13.stockQuantity);
        System.out.println("The powerConsumption is : " + ac13.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac13.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac13.refrigerantType);
        System.out.println("The rating is : " + ac13.rating);
        System.out.println("The airFlowRate is : " + ac13.airFlowRate);
        System.out.println("The isCertified is : " + ac13.isCertified);
        System.out.println("The countryOfOrigin is : " + ac13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac13.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac13.noiseLevel);
        System.out.println("The supportsWifi is : " + ac13.supportsWifi);
        System.out.println("The certificationType is : " + ac13.certificationType);


        AirConditioner ac14 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac14.acBrand);
        System.out.println("The acId is : " + ac14.acId);
        System.out.println("The acPrice is : " + ac14.acPrice);
        System.out.println("The isAvailable is : " + ac14.isAvailable);
        System.out.println("The acType is : " + ac14.acType);
        System.out.println("The capacityTons is : " + ac14.capacityTons);
        System.out.println("The weight is : " + ac14.weight);
        System.out.println("The isInverter is : " + ac14.isInverter);
        System.out.println("The compressorType is : " + ac14.compressorType);
        System.out.println("The warrantyYears is : " + ac14.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac14.coolingCapacity);
        System.out.println("The hasRemote is : " + ac14.hasRemote);
        System.out.println("The color is : " + ac14.color);
        System.out.println("The stockQuantity is : " + ac14.stockQuantity);
        System.out.println("The powerConsumption is : " + ac14.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac14.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac14.refrigerantType);
        System.out.println("The rating is : " + ac14.rating);
        System.out.println("The airFlowRate is : " + ac14.airFlowRate);
        System.out.println("The isCertified is : " + ac14.isCertified);
        System.out.println("The countryOfOrigin is : " + ac14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac14.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac14.noiseLevel);
        System.out.println("The supportsWifi is : " + ac14.supportsWifi);
        System.out.println("The certificationType is : " + ac14.certificationType);

        ac14.acBrand = "Daikin";
        ac14.acId = 14;
        ac14.acPrice = 14000.99;
        ac14.isAvailable = true;
        ac14.acType = "Split";
        ac14.capacityTons = 1.5;
        ac14.weight = 35.0;
        ac14.isInverter = true;
        ac14.compressorType = "Rotary";
        ac14.warrantyYears = 5;
        ac14.coolingCapacity = 5200.0;
        ac14.hasRemote = true;
        ac14.color = "White";
        ac14.stockQuantity = 15;
        ac14.powerConsumption = 1450.0;
        ac14.isEcoFriendly = true;
        ac14.refrigerantType = "R32";
        ac14.rating = 5;
        ac14.airFlowRate = 600.0;
        ac14.isCertified = true;
        ac14.countryOfOrigin = "India";
        ac14.manufacturingYear = 2025;
        ac14.noiseLevel = 42.0;
        ac14.supportsWifi = true;
        ac14.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac14.acBrand);
        System.out.println("The acId is : " + ac14.acId);
        System.out.println("The acPrice is : " + ac14.acPrice);
        System.out.println("The isAvailable is : " + ac14.isAvailable);
        System.out.println("The acType is : " + ac14.acType);
        System.out.println("The capacityTons is : " + ac14.capacityTons);
        System.out.println("The weight is : " + ac14.weight);
        System.out.println("The isInverter is : " + ac14.isInverter);
        System.out.println("The compressorType is : " + ac14.compressorType);
        System.out.println("The warrantyYears is : " + ac14.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac14.coolingCapacity);
        System.out.println("The hasRemote is : " + ac14.hasRemote);
        System.out.println("The color is : " + ac14.color);
        System.out.println("The stockQuantity is : " + ac14.stockQuantity);
        System.out.println("The powerConsumption is : " + ac14.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac14.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac14.refrigerantType);
        System.out.println("The rating is : " + ac14.rating);
        System.out.println("The airFlowRate is : " + ac14.airFlowRate);
        System.out.println("The isCertified is : " + ac14.isCertified);
        System.out.println("The countryOfOrigin is : " + ac14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac14.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac14.noiseLevel);
        System.out.println("The supportsWifi is : " + ac14.supportsWifi);
        System.out.println("The certificationType is : " + ac14.certificationType);


        AirConditioner ac15 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac15.acBrand);
        System.out.println("The acId is : " + ac15.acId);
        System.out.println("The acPrice is : " + ac15.acPrice);
        System.out.println("The isAvailable is : " + ac15.isAvailable);
        System.out.println("The acType is : " + ac15.acType);
        System.out.println("The capacityTons is : " + ac15.capacityTons);
        System.out.println("The weight is : " + ac15.weight);
        System.out.println("The isInverter is : " + ac15.isInverter);
        System.out.println("The compressorType is : " + ac15.compressorType);
        System.out.println("The warrantyYears is : " + ac15.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac15.coolingCapacity);
        System.out.println("The hasRemote is : " + ac15.hasRemote);
        System.out.println("The color is : " + ac15.color);
        System.out.println("The stockQuantity is : " + ac15.stockQuantity);
        System.out.println("The powerConsumption is : " + ac15.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac15.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac15.refrigerantType);
        System.out.println("The rating is : " + ac15.rating);
        System.out.println("The airFlowRate is : " + ac15.airFlowRate);
        System.out.println("The isCertified is : " + ac15.isCertified);
        System.out.println("The countryOfOrigin is : " + ac15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac15.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac15.noiseLevel);
        System.out.println("The supportsWifi is : " + ac15.supportsWifi);
        System.out.println("The certificationType is : " + ac15.certificationType);

        ac15.acBrand = "Daikin";
        ac15.acId = 15;
        ac15.acPrice = 15000.99;
        ac15.isAvailable = true;
        ac15.acType = "Split";
        ac15.capacityTons = 1.5;
        ac15.weight = 35.0;
        ac15.isInverter = true;
        ac15.compressorType = "Rotary";
        ac15.warrantyYears = 5;
        ac15.coolingCapacity = 5200.0;
        ac15.hasRemote = true;
        ac15.color = "White";
        ac15.stockQuantity = 15;
        ac15.powerConsumption = 1450.0;
        ac15.isEcoFriendly = true;
        ac15.refrigerantType = "R32";
        ac15.rating = 5;
        ac15.airFlowRate = 600.0;
        ac15.isCertified = true;
        ac15.countryOfOrigin = "India";
        ac15.manufacturingYear = 2025;
        ac15.noiseLevel = 42.0;
        ac15.supportsWifi = true;
        ac15.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac15.acBrand);
        System.out.println("The acId is : " + ac15.acId);
        System.out.println("The acPrice is : " + ac15.acPrice);
        System.out.println("The isAvailable is : " + ac15.isAvailable);
        System.out.println("The acType is : " + ac15.acType);
        System.out.println("The capacityTons is : " + ac15.capacityTons);
        System.out.println("The weight is : " + ac15.weight);
        System.out.println("The isInverter is : " + ac15.isInverter);
        System.out.println("The compressorType is : " + ac15.compressorType);
        System.out.println("The warrantyYears is : " + ac15.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac15.coolingCapacity);
        System.out.println("The hasRemote is : " + ac15.hasRemote);
        System.out.println("The color is : " + ac15.color);
        System.out.println("The stockQuantity is : " + ac15.stockQuantity);
        System.out.println("The powerConsumption is : " + ac15.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac15.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac15.refrigerantType);
        System.out.println("The rating is : " + ac15.rating);
        System.out.println("The airFlowRate is : " + ac15.airFlowRate);
        System.out.println("The isCertified is : " + ac15.isCertified);
        System.out.println("The countryOfOrigin is : " + ac15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac15.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac15.noiseLevel);
        System.out.println("The supportsWifi is : " + ac15.supportsWifi);
        System.out.println("The certificationType is : " + ac15.certificationType);


        AirConditioner ac16 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac16.acBrand);
        System.out.println("The acId is : " + ac16.acId);
        System.out.println("The acPrice is : " + ac16.acPrice);
        System.out.println("The isAvailable is : " + ac16.isAvailable);
        System.out.println("The acType is : " + ac16.acType);
        System.out.println("The capacityTons is : " + ac16.capacityTons);
        System.out.println("The weight is : " + ac16.weight);
        System.out.println("The isInverter is : " + ac16.isInverter);
        System.out.println("The compressorType is : " + ac16.compressorType);
        System.out.println("The warrantyYears is : " + ac16.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac16.coolingCapacity);
        System.out.println("The hasRemote is : " + ac16.hasRemote);
        System.out.println("The color is : " + ac16.color);
        System.out.println("The stockQuantity is : " + ac16.stockQuantity);
        System.out.println("The powerConsumption is : " + ac16.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac16.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac16.refrigerantType);
        System.out.println("The rating is : " + ac16.rating);
        System.out.println("The airFlowRate is : " + ac16.airFlowRate);
        System.out.println("The isCertified is : " + ac16.isCertified);
        System.out.println("The countryOfOrigin is : " + ac16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac16.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac16.noiseLevel);
        System.out.println("The supportsWifi is : " + ac16.supportsWifi);
        System.out.println("The certificationType is : " + ac16.certificationType);

        ac16.acBrand = "Daikin";
        ac16.acId = 16;
        ac16.acPrice = 16000.99;
        ac16.isAvailable = true;
        ac16.acType = "Split";
        ac16.capacityTons = 1.5;
        ac16.weight = 35.0;
        ac16.isInverter = true;
        ac16.compressorType = "Rotary";
        ac16.warrantyYears = 5;
        ac16.coolingCapacity = 5200.0;
        ac16.hasRemote = true;
        ac16.color = "White";
        ac16.stockQuantity = 15;
        ac16.powerConsumption = 1450.0;
        ac16.isEcoFriendly = true;
        ac16.refrigerantType = "R32";
        ac16.rating = 5;
        ac16.airFlowRate = 600.0;
        ac16.isCertified = true;
        ac16.countryOfOrigin = "India";
        ac16.manufacturingYear = 2025;
        ac16.noiseLevel = 42.0;
        ac16.supportsWifi = true;
        ac16.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac16.acBrand);
        System.out.println("The acId is : " + ac16.acId);
        System.out.println("The acPrice is : " + ac16.acPrice);
        System.out.println("The isAvailable is : " + ac16.isAvailable);
        System.out.println("The acType is : " + ac16.acType);
        System.out.println("The capacityTons is : " + ac16.capacityTons);
        System.out.println("The weight is : " + ac16.weight);
        System.out.println("The isInverter is : " + ac16.isInverter);
        System.out.println("The compressorType is : " + ac16.compressorType);
        System.out.println("The warrantyYears is : " + ac16.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac16.coolingCapacity);
        System.out.println("The hasRemote is : " + ac16.hasRemote);
        System.out.println("The color is : " + ac16.color);
        System.out.println("The stockQuantity is : " + ac16.stockQuantity);
        System.out.println("The powerConsumption is : " + ac16.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac16.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac16.refrigerantType);
        System.out.println("The rating is : " + ac16.rating);
        System.out.println("The airFlowRate is : " + ac16.airFlowRate);
        System.out.println("The isCertified is : " + ac16.isCertified);
        System.out.println("The countryOfOrigin is : " + ac16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac16.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac16.noiseLevel);
        System.out.println("The supportsWifi is : " + ac16.supportsWifi);
        System.out.println("The certificationType is : " + ac16.certificationType);


        AirConditioner ac17 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac17.acBrand);
        System.out.println("The acId is : " + ac17.acId);
        System.out.println("The acPrice is : " + ac17.acPrice);
        System.out.println("The isAvailable is : " + ac17.isAvailable);
        System.out.println("The acType is : " + ac17.acType);
        System.out.println("The capacityTons is : " + ac17.capacityTons);
        System.out.println("The weight is : " + ac17.weight);
        System.out.println("The isInverter is : " + ac17.isInverter);
        System.out.println("The compressorType is : " + ac17.compressorType);
        System.out.println("The warrantyYears is : " + ac17.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac17.coolingCapacity);
        System.out.println("The hasRemote is : " + ac17.hasRemote);
        System.out.println("The color is : " + ac17.color);
        System.out.println("The stockQuantity is : " + ac17.stockQuantity);
        System.out.println("The powerConsumption is : " + ac17.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac17.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac17.refrigerantType);
        System.out.println("The rating is : " + ac17.rating);
        System.out.println("The airFlowRate is : " + ac17.airFlowRate);
        System.out.println("The isCertified is : " + ac17.isCertified);
        System.out.println("The countryOfOrigin is : " + ac17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac17.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac17.noiseLevel);
        System.out.println("The supportsWifi is : " + ac17.supportsWifi);
        System.out.println("The certificationType is : " + ac17.certificationType);

        ac17.acBrand = "Daikin";
        ac17.acId = 17;
        ac17.acPrice = 17000.99;
        ac17.isAvailable = true;
        ac17.acType = "Split";
        ac17.capacityTons = 1.5;
        ac17.weight = 35.0;
        ac17.isInverter = true;
        ac17.compressorType = "Rotary";
        ac17.warrantyYears = 5;
        ac17.coolingCapacity = 5200.0;
        ac17.hasRemote = true;
        ac17.color = "White";
        ac17.stockQuantity = 15;
        ac17.powerConsumption = 1450.0;
        ac17.isEcoFriendly = true;
        ac17.refrigerantType = "R32";
        ac17.rating = 5;
        ac17.airFlowRate = 600.0;
        ac17.isCertified = true;
        ac17.countryOfOrigin = "India";
        ac17.manufacturingYear = 2025;
        ac17.noiseLevel = 42.0;
        ac17.supportsWifi = true;
        ac17.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac17.acBrand);
        System.out.println("The acId is : " + ac17.acId);
        System.out.println("The acPrice is : " + ac17.acPrice);
        System.out.println("The isAvailable is : " + ac17.isAvailable);
        System.out.println("The acType is : " + ac17.acType);
        System.out.println("The capacityTons is : " + ac17.capacityTons);
        System.out.println("The weight is : " + ac17.weight);
        System.out.println("The isInverter is : " + ac17.isInverter);
        System.out.println("The compressorType is : " + ac17.compressorType);
        System.out.println("The warrantyYears is : " + ac17.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac17.coolingCapacity);
        System.out.println("The hasRemote is : " + ac17.hasRemote);
        System.out.println("The color is : " + ac17.color);
        System.out.println("The stockQuantity is : " + ac17.stockQuantity);
        System.out.println("The powerConsumption is : " + ac17.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac17.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac17.refrigerantType);
        System.out.println("The rating is : " + ac17.rating);
        System.out.println("The airFlowRate is : " + ac17.airFlowRate);
        System.out.println("The isCertified is : " + ac17.isCertified);
        System.out.println("The countryOfOrigin is : " + ac17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac17.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac17.noiseLevel);
        System.out.println("The supportsWifi is : " + ac17.supportsWifi);
        System.out.println("The certificationType is : " + ac17.certificationType);


        AirConditioner ac18 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac18.acBrand);
        System.out.println("The acId is : " + ac18.acId);
        System.out.println("The acPrice is : " + ac18.acPrice);
        System.out.println("The isAvailable is : " + ac18.isAvailable);
        System.out.println("The acType is : " + ac18.acType);
        System.out.println("The capacityTons is : " + ac18.capacityTons);
        System.out.println("The weight is : " + ac18.weight);
        System.out.println("The isInverter is : " + ac18.isInverter);
        System.out.println("The compressorType is : " + ac18.compressorType);
        System.out.println("The warrantyYears is : " + ac18.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac18.coolingCapacity);
        System.out.println("The hasRemote is : " + ac18.hasRemote);
        System.out.println("The color is : " + ac18.color);
        System.out.println("The stockQuantity is : " + ac18.stockQuantity);
        System.out.println("The powerConsumption is : " + ac18.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac18.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac18.refrigerantType);
        System.out.println("The rating is : " + ac18.rating);
        System.out.println("The airFlowRate is : " + ac18.airFlowRate);
        System.out.println("The isCertified is : " + ac18.isCertified);
        System.out.println("The countryOfOrigin is : " + ac18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac18.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac18.noiseLevel);
        System.out.println("The supportsWifi is : " + ac18.supportsWifi);
        System.out.println("The certificationType is : " + ac18.certificationType);

        ac18.acBrand = "Daikin";
        ac18.acId = 18;
        ac18.acPrice = 18000.99;
        ac18.isAvailable = true;
        ac18.acType = "Split";
        ac18.capacityTons = 1.5;
        ac18.weight = 35.0;
        ac18.isInverter = true;
        ac18.compressorType = "Rotary";
        ac18.warrantyYears = 5;
        ac18.coolingCapacity = 5200.0;
        ac18.hasRemote = true;
        ac18.color = "White";
        ac18.stockQuantity = 15;
        ac18.powerConsumption = 1450.0;
        ac18.isEcoFriendly = true;
        ac18.refrigerantType = "R32";
        ac18.rating = 5;
        ac18.airFlowRate = 600.0;
        ac18.isCertified = true;
        ac18.countryOfOrigin = "India";
        ac18.manufacturingYear = 2025;
        ac18.noiseLevel = 42.0;
        ac18.supportsWifi = true;
        ac18.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac18.acBrand);
        System.out.println("The acId is : " + ac18.acId);
        System.out.println("The acPrice is : " + ac18.acPrice);
        System.out.println("The isAvailable is : " + ac18.isAvailable);
        System.out.println("The acType is : " + ac18.acType);
        System.out.println("The capacityTons is : " + ac18.capacityTons);
        System.out.println("The weight is : " + ac18.weight);
        System.out.println("The isInverter is : " + ac18.isInverter);
        System.out.println("The compressorType is : " + ac18.compressorType);
        System.out.println("The warrantyYears is : " + ac18.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac18.coolingCapacity);
        System.out.println("The hasRemote is : " + ac18.hasRemote);
        System.out.println("The color is : " + ac18.color);
        System.out.println("The stockQuantity is : " + ac18.stockQuantity);
        System.out.println("The powerConsumption is : " + ac18.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac18.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac18.refrigerantType);
        System.out.println("The rating is : " + ac18.rating);
        System.out.println("The airFlowRate is : " + ac18.airFlowRate);
        System.out.println("The isCertified is : " + ac18.isCertified);
        System.out.println("The countryOfOrigin is : " + ac18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac18.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac18.noiseLevel);
        System.out.println("The supportsWifi is : " + ac18.supportsWifi);
        System.out.println("The certificationType is : " + ac18.certificationType);


        AirConditioner ac19 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac19.acBrand);
        System.out.println("The acId is : " + ac19.acId);
        System.out.println("The acPrice is : " + ac19.acPrice);
        System.out.println("The isAvailable is : " + ac19.isAvailable);
        System.out.println("The acType is : " + ac19.acType);
        System.out.println("The capacityTons is : " + ac19.capacityTons);
        System.out.println("The weight is : " + ac19.weight);
        System.out.println("The isInverter is : " + ac19.isInverter);
        System.out.println("The compressorType is : " + ac19.compressorType);
        System.out.println("The warrantyYears is : " + ac19.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac19.coolingCapacity);
        System.out.println("The hasRemote is : " + ac19.hasRemote);
        System.out.println("The color is : " + ac19.color);
        System.out.println("The stockQuantity is : " + ac19.stockQuantity);
        System.out.println("The powerConsumption is : " + ac19.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac19.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac19.refrigerantType);
        System.out.println("The rating is : " + ac19.rating);
        System.out.println("The airFlowRate is : " + ac19.airFlowRate);
        System.out.println("The isCertified is : " + ac19.isCertified);
        System.out.println("The countryOfOrigin is : " + ac19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac19.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac19.noiseLevel);
        System.out.println("The supportsWifi is : " + ac19.supportsWifi);
        System.out.println("The certificationType is : " + ac19.certificationType);

        ac19.acBrand = "Daikin";
        ac19.acId = 19;
        ac19.acPrice = 19000.99;
        ac19.isAvailable = true;
        ac19.acType = "Split";
        ac19.capacityTons = 1.5;
        ac19.weight = 35.0;
        ac19.isInverter = true;
        ac19.compressorType = "Rotary";
        ac19.warrantyYears = 5;
        ac19.coolingCapacity = 5200.0;
        ac19.hasRemote = true;
        ac19.color = "White";
        ac19.stockQuantity = 15;
        ac19.powerConsumption = 1450.0;
        ac19.isEcoFriendly = true;
        ac19.refrigerantType = "R32";
        ac19.rating = 5;
        ac19.airFlowRate = 600.0;
        ac19.isCertified = true;
        ac19.countryOfOrigin = "India";
        ac19.manufacturingYear = 2025;
        ac19.noiseLevel = 42.0;
        ac19.supportsWifi = true;
        ac19.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac19.acBrand);
        System.out.println("The acId is : " + ac19.acId);
        System.out.println("The acPrice is : " + ac19.acPrice);
        System.out.println("The isAvailable is : " + ac19.isAvailable);
        System.out.println("The acType is : " + ac19.acType);
        System.out.println("The capacityTons is : " + ac19.capacityTons);
        System.out.println("The weight is : " + ac19.weight);
        System.out.println("The isInverter is : " + ac19.isInverter);
        System.out.println("The compressorType is : " + ac19.compressorType);
        System.out.println("The warrantyYears is : " + ac19.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac19.coolingCapacity);
        System.out.println("The hasRemote is : " + ac19.hasRemote);
        System.out.println("The color is : " + ac19.color);
        System.out.println("The stockQuantity is : " + ac19.stockQuantity);
        System.out.println("The powerConsumption is : " + ac19.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac19.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac19.refrigerantType);
        System.out.println("The rating is : " + ac19.rating);
        System.out.println("The airFlowRate is : " + ac19.airFlowRate);
        System.out.println("The isCertified is : " + ac19.isCertified);
        System.out.println("The countryOfOrigin is : " + ac19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac19.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac19.noiseLevel);
        System.out.println("The supportsWifi is : " + ac19.supportsWifi);
        System.out.println("The certificationType is : " + ac19.certificationType);


        AirConditioner ac20 = new AirConditioner();

        System.out.println("Before initialization");

        System.out.println("The acBrand is : " + ac20.acBrand);
        System.out.println("The acId is : " + ac20.acId);
        System.out.println("The acPrice is : " + ac20.acPrice);
        System.out.println("The isAvailable is : " + ac20.isAvailable);
        System.out.println("The acType is : " + ac20.acType);
        System.out.println("The capacityTons is : " + ac20.capacityTons);
        System.out.println("The weight is : " + ac20.weight);
        System.out.println("The isInverter is : " + ac20.isInverter);
        System.out.println("The compressorType is : " + ac20.compressorType);
        System.out.println("The warrantyYears is : " + ac20.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac20.coolingCapacity);
        System.out.println("The hasRemote is : " + ac20.hasRemote);
        System.out.println("The color is : " + ac20.color);
        System.out.println("The stockQuantity is : " + ac20.stockQuantity);
        System.out.println("The powerConsumption is : " + ac20.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac20.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac20.refrigerantType);
        System.out.println("The rating is : " + ac20.rating);
        System.out.println("The airFlowRate is : " + ac20.airFlowRate);
        System.out.println("The isCertified is : " + ac20.isCertified);
        System.out.println("The countryOfOrigin is : " + ac20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac20.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac20.noiseLevel);
        System.out.println("The supportsWifi is : " + ac20.supportsWifi);
        System.out.println("The certificationType is : " + ac20.certificationType);

        ac20.acBrand = "Daikin";
        ac20.acId = 20;
        ac20.acPrice = 20000.99;
        ac20.isAvailable = true;
        ac20.acType = "Split";
        ac20.capacityTons = 1.5;
        ac20.weight = 35.0;
        ac20.isInverter = true;
        ac20.compressorType = "Rotary";
        ac20.warrantyYears = 5;
        ac20.coolingCapacity = 5200.0;
        ac20.hasRemote = true;
        ac20.color = "White";
        ac20.stockQuantity = 15;
        ac20.powerConsumption = 1450.0;
        ac20.isEcoFriendly = true;
        ac20.refrigerantType = "R32";
        ac20.rating = 5;
        ac20.airFlowRate = 600.0;
        ac20.isCertified = true;
        ac20.countryOfOrigin = "India";
        ac20.manufacturingYear = 2025;
        ac20.noiseLevel = 42.0;
        ac20.supportsWifi = true;
        ac20.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The acBrand is : " + ac20.acBrand);
        System.out.println("The acId is : " + ac20.acId);
        System.out.println("The acPrice is : " + ac20.acPrice);
        System.out.println("The isAvailable is : " + ac20.isAvailable);
        System.out.println("The acType is : " + ac20.acType);
        System.out.println("The capacityTons is : " + ac20.capacityTons);
        System.out.println("The weight is : " + ac20.weight);
        System.out.println("The isInverter is : " + ac20.isInverter);
        System.out.println("The compressorType is : " + ac20.compressorType);
        System.out.println("The warrantyYears is : " + ac20.warrantyYears);
        System.out.println("The coolingCapacity is : " + ac20.coolingCapacity);
        System.out.println("The hasRemote is : " + ac20.hasRemote);
        System.out.println("The color is : " + ac20.color);
        System.out.println("The stockQuantity is : " + ac20.stockQuantity);
        System.out.println("The powerConsumption is : " + ac20.powerConsumption);
        System.out.println("The isEcoFriendly is : " + ac20.isEcoFriendly);
        System.out.println("The refrigerantType is : " + ac20.refrigerantType);
        System.out.println("The rating is : " + ac20.rating);
        System.out.println("The airFlowRate is : " + ac20.airFlowRate);
        System.out.println("The isCertified is : " + ac20.isCertified);
        System.out.println("The countryOfOrigin is : " + ac20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + ac20.manufacturingYear);
        System.out.println("The noiseLevel is : " + ac20.noiseLevel);
        System.out.println("The supportsWifi is : " + ac20.supportsWifi);
        System.out.println("The certificationType is : " + ac20.certificationType);


    }
}
