class AnkletRunner {
    public static void main(String[] args) {


        Anklet a1 = new Anklet(); 
		a1.design = "Simple";
        Anklet a2 = new Anklet();
		a2.design = "Beaded";
        Anklet a3 = new Anklet(); 
		a3.design = "Chain";
        Anklet a4 = new Anklet();
		a4.design = "Pearl";
        Anklet a5 = new Anklet(); 
		a5.design = "Silver";
        Anklet a6 = new Anklet(); 
		a6.design = "Gold";
        Anklet a7 = new Anklet();
		a7.design = "Diamond";
        Anklet a8 = new Anklet();
		a8.design = "Crystal";
        Anklet a9 = new Anklet();
		a9.design = "Traditional";
        Anklet a10 = new Anklet();
		a10.design = "Modern";
        Anklet a11 = new Anklet();
		a11.design = "Temple";
        Anklet a12 = new Anklet();
		a12.design = "Lotus";
        Anklet a13 = new Anklet();
		a13.design = "Peacock";
        Anklet a14 = new Anklet();
		a14.design = "Leaf";
        Anklet a15 = new Anklet();
		a15.design = "Floral";
        Anklet a16 = new Anklet();
		a16.design = "Star";
        Anklet a17 = new Anklet();
		a17.design = "Moon";
        Anklet a18 = new Anklet();
		a18.design = "Sun";
        Anklet a19 = new Anklet();
		a19.design = "Heart";
        Anklet a20 = new Anklet();
		a20.design = "Butterfly";
        Anklet a21 = new Anklet();
		a21.design = "Bell";
        Anklet a22 = new Anklet();
		a22.design = "Thread";
        Anklet a23 = new Anklet();
		a23.design = "Stone";
        Anklet a24 = new Anklet();
		a24.design = "Vintage";
        Anklet a25 = new Anklet();
		a25.design = "Royal";

        System.out.println("Anklet design : " + a1.design);
        System.out.println("Anklet design : " + a2.design);
        System.out.println("Anklet design : " + a3.design);
        System.out.println("Anklet design : " + a4.design);
        System.out.println("Anklet design : " + a5.design);
        System.out.println("Anklet design : " + a6.design);
        System.out.println("Anklet design : " + a7.design);
        System.out.println("Anklet design : " + a8.design);
        System.out.println("Anklet design : " + a9.design);
        System.out.println("Anklet design : " + a10.design);
        System.out.println("Anklet design : " + a11.design);
        System.out.println("Anklet design : " + a12.design);
        System.out.println("Anklet design : " + a13.design);
        System.out.println("Anklet design : " + a14.design);
        System.out.println("Anklet design : " + a15.design);
        System.out.println("Anklet design : " + a16.design);
        System.out.println("Anklet design : " + a17.design);
        System.out.println("Anklet design : " + a18.design);
        System.out.println("Anklet design : " + a19.design);
        System.out.println("Anklet design : " + a20.design);
        System.out.println("Anklet design : " + a21.design);
        System.out.println("Anklet design : " + a22.design);
        System.out.println("Anklet design : " + a23.design);
        System.out.println("Anklet design : " + a24.design);
        System.out.println("Anklet design : " + a25.design);


        Anklet p1 = new Anklet("Gold");
        Anklet p2 = new Anklet("Silver");
        Anklet p3 = new Anklet("Bronze");
        Anklet p4 = new Anklet("Copper");
        Anklet p5 = new Anklet("Platinum");
        Anklet p6 = new Anklet("Ruby");
        Anklet p7 = new Anklet("Sapphire");
        Anklet p8 = new Anklet("Emerald");
        Anklet p9 = new Anklet("Amethyst");
        Anklet p10 = new Anklet("Topaz");
        Anklet p11 = new Anklet("Pearl");
        Anklet p12 = new Anklet("Jade");
        Anklet p13 = new Anklet("Onyx");
        Anklet p14 = new Anklet("Amber");
        Anklet p15 = new Anklet("Quartz");
        Anklet p16 = new Anklet("Garnet");
        Anklet p17 = new Anklet("Opal");
        Anklet p18 = new Anklet("Zircon");
        Anklet p19 = new Anklet("Aquamarine");
        Anklet p20 = new Anklet("Peridot");
        Anklet p21 = new Anklet("Obsidian");
        Anklet p22 = new Anklet("Malachite");
        Anklet p23 = new Anklet("Lapis");
        Anklet p24 = new Anklet("Citrine");
        Anklet p25 = new Anklet("Spinel");

        System.out.println("Design of Anklet 1: " + p1.design);
        System.out.println("Design of Anklet 2: " + p2.design);
        System.out.println("Design of Anklet 3: " + p3.design);
        System.out.println("Design of Anklet 4: " + p4.design);
        System.out.println("Design of Anklet 5: " + p5.design);
        System.out.println("Design of Anklet 6: " + p6.design);
        System.out.println("Design of Anklet 7: " + p7.design);
        System.out.println("Design of Anklet 8: " + p8.design);
        System.out.println("Design of Anklet 9: " + p9.design);
        System.out.println("Design of Anklet 10: " + p10.design);
        System.out.println("Design of Anklet 11: " + p11.design);
        System.out.println("Design of Anklet 12: " + p12.design);
        System.out.println("Design of Anklet 13: " + p13.design);
        System.out.println("Design of Anklet 14: " + p14.design);
        System.out.println("Design of Anklet 15: " + p15.design);
        System.out.println("Design of Anklet 16: " + p16.design);
        System.out.println("Design of Anklet 17: " + p17.design);
        System.out.println("Design of Anklet 18: " + p18.design);
        System.out.println("Design of Anklet 19: " + p19.design);
        System.out.println("Design of Anklet 20: " + p20.design);
        System.out.println("Design of Anklet 21: " + p21.design);
        System.out.println("Design of Anklet 22: " + p22.design);
        System.out.println("Design of Anklet 23: " + p23.design);
        System.out.println("Design of Anklet 24: " + p24.design);
        System.out.println("Design of Anklet 25: " + p25.design);

    }
}