class BankExecutor {

    public static void main(String[] args) {

        Bank bank1 = new Bank();
        bank1.setBankId(1);
        bank1.setBankName("Canara Bank");
        bank1.setBranch("Bengaluru Main");
        bank1.setIfscCode("CNRB0000001");
        bank1.setAccountType("Savings");
        bank1.setInterestRate("3.5%");
        bank1.setEstablishedOn("1906-07-01");
        System.out.println("The Bank ID is : " + bank1.getBankId());
        System.out.println("The Bank Name is : " + bank1.getBankName());
        System.out.println("The Branch is : " + bank1.getBranch());
        System.out.println("The IFSC Code is : " + bank1.getIfscCode());
        System.out.println("The Account Type is : " + bank1.getAccountType());
        System.out.println("The Interest Rate is : " + bank1.getInterestRate());
        System.out.println("The Established On is : " + bank1.getEstablishedOn());

        Bank bank2 = new Bank();
        bank2.setBankId(2);
        bank2.setBankName("State Bank of India");
        bank2.setBranch("Mumbai Corporate");
        bank2.setIfscCode("SBIN0001234");
        bank2.setAccountType("Current");
        bank2.setInterestRate("2.7%");
        bank2.setEstablishedOn("1955-07-01");
        System.out.println("The Bank ID is : " + bank2.getBankId());
        System.out.println("The Bank Name is : " + bank2.getBankName());
        System.out.println("The Branch is : " + bank2.getBranch());
        System.out.println("The IFSC Code is : " + bank2.getIfscCode());
        System.out.println("The Account Type is : " + bank2.getAccountType());
        System.out.println("The Interest Rate is : " + bank2.getInterestRate());
        System.out.println("The Established On is : " + bank2.getEstablishedOn());

        Bank bank3 = new Bank();
        bank3.setBankId(3);
        bank3.setBankName("HDFC Bank");
        bank3.setBranch("Pune MG Road");
        bank3.setIfscCode("HDFC0000543");
        bank3.setAccountType("Salary");
        bank3.setInterestRate("3.0%");
        bank3.setEstablishedOn("1994-08-30");
        System.out.println("The Bank ID is : " + bank3.getBankId());
        System.out.println("The Bank Name is : " + bank3.getBankName());
        System.out.println("The Branch is : " + bank3.getBranch());
        System.out.println("The IFSC Code is : " + bank3.getIfscCode());
        System.out.println("The Account Type is : " + bank3.getAccountType());
        System.out.println("The Interest Rate is : " + bank3.getInterestRate());
        System.out.println("The Established On is : " + bank3.getEstablishedOn());

        Bank bank4 = new Bank();
        bank4.setBankId(4);
        bank4.setBankName("ICICI Bank");
        bank4.setBranch("Delhi CP");
        bank4.setIfscCode("ICIC0000011");
        bank4.setAccountType("Premium");
        bank4.setInterestRate("3.2%");
        bank4.setEstablishedOn("1994-01-05");
        System.out.println("The Bank ID is : " + bank4.getBankId());
        System.out.println("The Bank Name is : " + bank4.getBankName());
        System.out.println("The Branch is : " + bank4.getBranch());
        System.out.println("The IFSC Code is : " + bank4.getIfscCode());
        System.out.println("The Account Type is : " + bank4.getAccountType());
        System.out.println("The Interest Rate is : " + bank4.getInterestRate());
        System.out.println("The Established On is : " + bank4.getEstablishedOn());

        Bank bank5 = new Bank();
        bank5.setBankId(5);
        bank5.setBankName("Axis Bank");
        bank5.setBranch("Hyderabad Hi-Tech");
        bank5.setIfscCode("UTIB0000214");
        bank5.setAccountType("Savings");
        bank5.setInterestRate("3.5%");
        bank5.setEstablishedOn("1993-12-03");
        System.out.println("The Bank ID is : " + bank5.getBankId());
        System.out.println("The Bank Name is : " + bank5.getBankName());
        System.out.println("The Branch is : " + bank5.getBranch());
        System.out.println("The IFSC Code is : " + bank5.getIfscCode());
        System.out.println("The Account Type is : " + bank5.getAccountType());
        System.out.println("The Interest Rate is : " + bank5.getInterestRate());
        System.out.println("The Established On is : " + bank5.getEstablishedOn());

        Bank bank6 = new Bank();
        bank6.setBankId(6);
        bank6.setBankName("Punjab National Bank");
        bank6.setBranch("Kolkata Metro");
        bank6.setIfscCode("PUNB0123456");
        bank6.setAccountType("Fixed Deposit");
        bank6.setInterestRate("6.5%");
        bank6.setEstablishedOn("1894-05-19");
        System.out.println("The Bank ID is : " + bank6.getBankId());
        System.out.println("The Bank Name is : " + bank6.getBankName());
        System.out.println("The Branch is : " + bank6.getBranch());
        System.out.println("The IFSC Code is : " + bank6.getIfscCode());
        System.out.println("The Account Type is : " + bank6.getAccountType());
        System.out.println("The Interest Rate is : " + bank6.getInterestRate());
        System.out.println("The Established On is : " + bank6.getEstablishedOn());

        Bank bank7 = new Bank();
        bank7.setBankId(7);
        bank7.setBankName("Bank of Baroda");
        bank7.setBranch("Vadodara City");
        bank7.setIfscCode("BARB0VADODX");
        bank7.setAccountType("Current");
        bank7.setInterestRate("0.0%");
        bank7.setEstablishedOn("1908-07-20");
        System.out.println("The Bank ID is : " + bank7.getBankId());
        System.out.println("The Bank Name is : " + bank7.getBankName());
        System.out.println("The Branch is : " + bank7.getBranch());
        System.out.println("The IFSC Code is : " + bank7.getIfscCode());
        System.out.println("The Account Type is : " + bank7.getAccountType());
        System.out.println("The Interest Rate is : " + bank7.getInterestRate());
        System.out.println("The Established On is : " + bank7.getEstablishedOn());

        Bank bank8 = new Bank();
        bank8.setBankId(8);
        bank8.setBankName("Kotak Mahindra Bank");
        bank8.setBranch("Chennai OMR");
        bank8.setIfscCode("KKBK0000123");
        bank8.setAccountType("Savings 811");
        bank8.setInterestRate("4.0%");
        bank8.setEstablishedOn("2003-02-01");
        System.out.println("The Bank ID is : " + bank8.getBankId());
        System.out.println("The Bank Name is : " + bank8.getBankName());
        System.out.println("The Branch is : " + bank8.getBranch());
        System.out.println("The IFSC Code is : " + bank8.getIfscCode());
        System.out.println("The Account Type is : " + bank8.getAccountType());
        System.out.println("The Interest Rate is : " + bank8.getInterestRate());
        System.out.println("The Established On is : " + bank8.getEstablishedOn());

        Bank bank9 = new Bank();
        bank9.setBankId(9);
        bank9.setBankName("IndusInd Bank");
        bank9.setBranch("Gurgaon HQ");
        bank9.setIfscCode("INDB0000001");
        bank9.setAccountType("Wealth");
        bank9.setInterestRate("5.0%");
        bank9.setEstablishedOn("1994-04-01");
        System.out.println("The Bank ID is : " + bank9.getBankId());
        System.out.println("The Bank Name is : " + bank9.getBankName());
        System.out.println("The Branch is : " + bank9.getBranch());
        System.out.println("The IFSC Code is : " + bank9.getIfscCode());
        System.out.println("The Account Type is : " + bank9.getAccountType());
        System.out.println("The Interest Rate is : " + bank9.getInterestRate());
        System.out.println("The Established On is : " + bank9.getEstablishedOn());

        Bank bank10 = new Bank();
        bank10.setBankId(10);
        bank10.setBankName("Union Bank of India");
        bank10.setBranch("Mumbai Gateway");
        bank10.setIfscCode("UBIN0531234");
        bank10.setAccountType("Savings");
        bank10.setInterestRate("3.3%");
        bank10.setEstablishedOn("1919-11-11");
        System.out.println("The Bank ID is : " + bank10.getBankId());
        System.out.println("The Bank Name is : " + bank10.getBankName());
        System.out.println("The Branch is : " + bank10.getBranch());
        System.out.println("The IFSC Code is : " + bank10.getIfscCode());
        System.out.println("The Account Type is : " + bank10.getAccountType());
        System.out.println("The Interest Rate is : " + bank10.getInterestRate());
        System.out.println("The Established On is : " + bank10.getEstablishedOn());

        Bank bank11 = new Bank();
        bank11.setBankId(11);
        bank11.setBankName("IDFC First Bank");
        bank11.setBranch("Bangalore Indiranagar");
        bank11.setIfscCode("IDFB0020123");
        bank11.setAccountType("Savings");
        bank11.setInterestRate("6.0%");
        bank11.setEstablishedOn("2015-10-01");
        System.out.println("The Bank ID is : " + bank11.getBankId());
        System.out.println("The Bank Name is : " + bank11.getBankName());
        System.out.println("The Branch is : " + bank11.getBranch());
        System.out.println("The IFSC Code is : " + bank11.getIfscCode());
        System.out.println("The Account Type is : " + bank11.getAccountType());
        System.out.println("The Interest Rate is : " + bank11.getInterestRate());
        System.out.println("The Established On is : " + bank11.getEstablishedOn());

        Bank bank12 = new Bank();
        bank12.setBankId(12);
        bank12.setBankName("Yes Bank");
        bank12.setBranch("Noida Sector 62");
        bank12.setIfscCode("YESB0000001");
        bank12.setAccountType("Corporate");
        bank12.setInterestRate("3.5%");
        bank12.setEstablishedOn("2004-11-21");
        System.out.println("The Bank ID is : " + bank12.getBankId());
        System.out.println("The Bank Name is : " + bank12.getBankName());
        System.out.println("The Branch is : " + bank12.getBranch());
        System.out.println("The IFSC Code is : " + bank12.getIfscCode());
        System.out.println("The Account Type is : " + bank12.getAccountType());
        System.out.println("The Interest Rate is : " + bank12.getInterestRate());
        System.out.println("The Established On is : " + bank12.getEstablishedOn());

        Bank bank13 = new Bank();
        bank13.setBankId(13);
        bank13.setBankName("Federal Bank");
        bank13.setBranch("Kochi Aluva");
        bank13.setIfscCode("FDRL0001001");
        bank13.setAccountType("NRI Savings");
        bank13.setInterestRate("3.8%");
        bank13.setEstablishedOn("1931-04-23");
        System.out.println("The Bank ID is : " + bank13.getBankId());
        System.out.println("The Bank Name is : " + bank13.getBankName());
        System.out.println("The Branch is : " + bank13.getBranch());
        System.out.println("The IFSC Code is : " + bank13.getIfscCode());
        System.out.println("The Account Type is : " + bank13.getAccountType());
        System.out.println("The Interest Rate is : " + bank13.getInterestRate());
        System.out.println("The Established On is : " + bank13.getEstablishedOn());

        Bank bank14 = new Bank();
        bank14.setBankId(14);
        bank14.setBankName("South Indian Bank");
        bank14.setBranch("Thrissur HO");
        bank14.setIfscCode("SIBL0000123");
        bank14.setAccountType("Recurring Deposit");
        bank14.setInterestRate("6.2%");
        bank14.setEstablishedOn("1929-01-29");
        System.out.println("The Bank ID is : " + bank14.getBankId());
        System.out.println("The Bank Name is : " + bank14.getBankName());
        System.out.println("The Branch is : " + bank14.getBranch());
        System.out.println("The IFSC Code is : " + bank14.getIfscCode());
        System.out.println("The Account Type is : " + bank14.getAccountType());
        System.out.println("The Interest Rate is : " + bank14.getInterestRate());
        System.out.println("The Established On is : " + bank14.getEstablishedOn());

        Bank bank15 = new Bank();
        bank15.setBankId(15);
        bank15.setBankName("RBL Bank");
        bank15.setBranch("Mumbai Lower Parel");
        bank15.setIfscCode("RATN0000111");
        bank15.setAccountType("Savings");
        bank15.setInterestRate("4.5%");
        bank15.setEstablishedOn("1943-08-06");
        System.out.println("The Bank ID is : " + bank15.getBankId());
        System.out.println("The Bank Name is : " + bank15.getBankName());
        System.out.println("The Branch is : " + bank15.getBranch());
        System.out.println("The IFSC Code is : " + bank15.getIfscCode());
        System.out.println("The Account Type is : " + bank15.getAccountType());
        System.out.println("The Interest Rate is : " + bank15.getInterestRate());
        System.out.println("The Established On is : " + bank15.getEstablishedOn());

        Bank bank16 = new Bank();
        bank16.setBankId(16);
        bank16.setBankName("Indian Bank");
        bank16.setBranch("Chennai Mount Rd");
        bank16.setIfscCode("IDIB000M001");
        bank16.setAccountType("Pension");
        bank16.setInterestRate("3.4%");
        bank16.setEstablishedOn("1907-08-15");
        System.out.println("The Bank ID is : " + bank16.getBankId());
        System.out.println("The Bank Name is : " + bank16.getBankName());
        System.out.println("The Branch is : " + bank16.getBranch());
        System.out.println("The IFSC Code is : " + bank16.getIfscCode());
        System.out.println("The Account Type is : " + bank16.getAccountType());
        System.out.println("The Interest Rate is : " + bank16.getInterestRate());
        System.out.println("The Established On is : " + bank16.getEstablishedOn());

        Bank bank17 = new Bank();
        bank17.setBankId(17);
        bank17.setBankName("Indian Overseas Bank");
        bank17.setBranch("Chennai Annasalai");
        bank17.setIfscCode("IOBA0001234");
        bank17.setAccountType("Savings");
        bank17.setInterestRate("3.4%");
        bank17.setEstablishedOn("1937-02-10");
        System.out.println("The Bank ID is : " + bank17.getBankId());
        System.out.println("The Bank Name is : " + bank17.getBankName());
        System.out.println("The Branch is : " + bank17.getBranch());
        System.out.println("The IFSC Code is : " + bank17.getIfscCode());
        System.out.println("The Account Type is : " + bank17.getAccountType());
        System.out.println("The Interest Rate is : " + bank17.getInterestRate());
        System.out.println("The Established On is : " + bank17.getEstablishedOn());

        Bank bank18 = new Bank();
        bank18.setBankId(18);
        bank18.setBankName("Bank of Maharashtra");
        bank18.setBranch("Pune Shivaji Nagar");
        bank18.setIfscCode("MAHB0000001");
        bank18.setAccountType("Current");
        bank18.setInterestRate("0.0%");
        bank18.setEstablishedOn("1935-09-16");
        System.out.println("The Bank ID is : " + bank18.getBankId());
        System.out.println("The Bank Name is : " + bank18.getBankName());
        System.out.println("The Branch is : " + bank18.getBranch());
        System.out.println("The IFSC Code is : " + bank18.getIfscCode());
        System.out.println("The Account Type is : " + bank18.getAccountType());
        System.out.println("The Interest Rate is : " + bank18.getInterestRate());
        System.out.println("The Established On is : " + bank18.getEstablishedOn());

        Bank bank19 = new Bank();
        bank19.setBankId(19);
        bank19.setBankName("UCO Bank");
        bank19.setBranch("Kolkata Brabourne");
        bank19.setIfscCode("UCBA0000002");
        bank19.setAccountType("Savings");
        bank19.setInterestRate("3.5%");
        bank19.setEstablishedOn("1943-01-06");
        System.out.println("The Bank ID is : " + bank19.getBankId());
        System.out.println("The Bank Name is : " + bank19.getBankName());
        System.out.println("The Branch is : " + bank19.getBranch());
        System.out.println("The IFSC Code is : " + bank19.getIfscCode());
        System.out.println("The Account Type is : " + bank19.getAccountType());
        System.out.println("The Interest Rate is : " + bank19.getInterestRate());
        System.out.println("The Established On is : " + bank19.getEstablishedOn());

        Bank bank20 = new Bank();
        bank20.setBankId(20);
        bank20.setBankName("Central Bank of India");
        bank20.setBranch("Mumbai Nariman Pt");
        bank20.setIfscCode("CBIN0280001");
        bank20.setAccountType("Savings");
        bank20.setInterestRate("3.4%");
        bank20.setEstablishedOn("1911-12-21");
        System.out.println("The Bank ID is : " + bank20.getBankId());
        System.out.println("The Bank Name is : " + bank20.getBankName());
        System.out.println("The Branch is : " + bank20.getBranch());
        System.out.println("The IFSC Code is : " + bank20.getIfscCode());
        System.out.println("The Account Type is : " + bank20.getAccountType());
        System.out.println("The Interest Rate is : " + bank20.getInterestRate());
        System.out.println("The Established On is : " + bank20.getEstablishedOn());

        Bank bank21 = new Bank();
        bank21.setBankId(21);
        bank21.setBankName("Karnataka Bank");
        bank21.setBranch("Mangalore Head");
        bank21.setIfscCode("KARB0000001");
        bank21.setAccountType("Savings");
        bank21.setInterestRate("3.7%");
        bank21.setEstablishedOn("1924-02-18");
        System.out.println("The Bank ID is : " + bank21.getBankId());
        System.out.println("The Bank Name is : " + bank21.getBankName());
        System.out.println("The Branch is : " + bank21.getBranch());
        System.out.println("The IFSC Code is : " + bank21.getIfscCode());
        System.out.println("The Account Type is : " + bank21.getAccountType());
        System.out.println("The Interest Rate is : " + bank21.getInterestRate());
        System.out.println("The Established On is : " + bank21.getEstablishedOn());

        Bank bank22 = new Bank();
        bank22.setBankId(22);
        bank22.setBankName("Standard Chartered");
        bank22.setBranch("Mumbai Fort");
        bank22.setIfscCode("SCBL0036001");
        bank22.setAccountType("Foreign");
        bank22.setInterestRate("2.5%");
        bank22.setEstablishedOn("1969-01-01");
        System.out.println("The Bank ID is : " + bank22.getBankId());
        System.out.println("The Bank Name is : " + bank22.getBankName());
        System.out.println("The Branch is : " + bank22.getBranch());
        System.out.println("The IFSC Code is : " + bank22.getIfscCode());
        System.out.println("The Account Type is : " + bank22.getAccountType());
        System.out.println("The Interest Rate is : " + bank22.getInterestRate());
        System.out.println("The Established On is : " + bank22.getEstablishedOn());

        Bank bank23 = new Bank();
        bank23.setBankId(23);
        bank23.setBankName("DBS Bank");
        bank23.setBranch("Singapore Towers");
        bank23.setIfscCode("DBSS0IN0811");
        bank23.setAccountType("Digital");
        bank23.setInterestRate("4.0%");
        bank23.setEstablishedOn("1968-07-16");
        System.out.println("The Bank ID is : " + bank23.getBankId());
        System.out.println("The Bank Name is : " + bank23.getBankName());
        System.out.println("The Branch is : " + bank23.getBranch());
        System.out.println("The IFSC Code is : " + bank23.getIfscCode());
        System.out.println("The Account Type is : " + bank23.getAccountType());
        System.out.println("The Interest Rate is : " + bank23.getInterestRate());
        System.out.println("The Established On is : " + bank23.getEstablishedOn());

        Bank bank24 = new Bank();
        bank24.setBankId(24);
        bank24.setBankName("Bandhan Bank");
        bank24.setBranch("Kolkata Head");
        bank24.setIfscCode("BDBL0001001");
        bank24.setAccountType("Savings");
        bank24.setInterestRate("3.0%");
        bank24.setEstablishedOn("2015-08-23");
        System.out.println("The Bank ID is : " + bank24.getBankId());
        System.out.println("The Bank Name is : " + bank24.getBankName());
        System.out.println("The Branch is : " + bank24.getBranch());
        System.out.println("The IFSC Code is : " + bank24.getIfscCode());
        System.out.println("The Account Type is : " + bank24.getAccountType());
        System.out.println("The Interest Rate is : " + bank24.getInterestRate());
        System.out.println("The Established On is : " + bank24.getEstablishedOn());

        Bank bank25 = new Bank();
        bank25.setBankId(25);
        bank25.setBankName("Punjab & Sind Bank");
        bank25.setBranch("Amritsar Hall");
        bank25.setIfscCode("PSIB0000001");
        bank25.setAccountType("Savings");
        bank25.setInterestRate("3.6%");
        bank25.setEstablishedOn("1908-06-24");
        System.out.println("The Bank ID is : " + bank25.getBankId());
        System.out.println("The Bank Name is : " + bank25.getBankName());
        System.out.println("The Branch is : " + bank25.getBranch());
        System.out.println("The IFSC Code is : " + bank25.getIfscCode());
        System.out.println("The Account Type is : " + bank25.getAccountType());
        System.out.println("The Interest Rate is : " + bank25.getInterestRate());
        System.out.println("The Established On is : " + bank25.getEstablishedOn());

        Bank bank26 = new Bank();
        bank26.setBankId(26);
        bank26.setBankName("Citibank");
        bank26.setBranch("Mumbai BKC");
        bank26.setIfscCode("CITI0000001");
        bank26.setAccountType("NRI");
        bank26.setInterestRate("2.0%");
        bank26.setEstablishedOn("1812-06-16");
        System.out.println("The Bank ID is : " + bank26.getBankId());
        System.out.println("The Bank Name is : " + bank26.getBankName());
        System.out.println("The Branch is : " + bank26.getBranch());
        System.out.println("The IFSC Code is : " + bank26.getIfscCode());
        System.out.println("The Account Type is : " + bank26.getAccountType());
        System.out.println("The Interest Rate is : " + bank26.getInterestRate());
        System.out.println("The Established On is : " + bank26.getEstablishedOn());

        Bank bank27 = new Bank();
        bank27.setBankId(27);
        bank27.setBankName("HSBC Bank");
        bank27.setBranch("Mumbai Fort");
        bank27.setIfscCode("HSBC0400002");
        bank27.setAccountType("Premier");
        bank27.setInterestRate("3.0%");
        bank27.setEstablishedOn("1865-03-03");
        System.out.println("The Bank ID is : " + bank27.getBankId());
        System.out.println("The Bank Name is : " + bank27.getBankName());
        System.out.println("The Branch is : " + bank27.getBranch());
        System.out.println("The IFSC Code is : " + bank27.getIfscCode());
        System.out.println("The Account Type is : " + bank27.getAccountType());
        System.out.println("The Interest Rate is : " + bank27.getInterestRate());
        System.out.println("The Established On is : " + bank27.getEstablishedOn());

        Bank bank28 = new Bank();
        bank28.setBankId(28);
        bank28.setBankName("Karur Vysya Bank");
        bank28.setBranch("Karur HQ");
        bank28.setIfscCode("KVBL0001101");
        bank28.setAccountType("Savings");
        bank28.setInterestRate("3.2%");
        bank28.setEstablishedOn("1916-01-01");
        System.out.println("The Bank ID is : " + bank28.getBankId());
        System.out.println("The Bank Name is : " + bank28.getBankName());
        System.out.println("The Branch is : " + bank28.getBranch());
        System.out.println("The IFSC Code is : " + bank28.getIfscCode());
        System.out.println("The Account Type is : " + bank28.getAccountType());
        System.out.println("The Interest Rate is : " + bank28.getInterestRate());
        System.out.println("The Established On is : " + bank28.getEstablishedOn());

        Bank bank29 = new Bank();
        bank29.setBankId(29);
        bank29.setBankName("CSB Bank");
        bank29.setBranch("Thrissur City");
        bank29.setIfscCode("CSBK0000001");
        bank29.setAccountType("Savings");
        bank29.setInterestRate("3.0%");
        bank29.setEstablishedOn("1920-11-26");
        System.out.println("The Bank ID is : " + bank29.getBankId());
        System.out.println("The Bank Name is : " + bank29.getBankName());
        System.out.println("The Branch is : " + bank29.getBranch());
        System.out.println("The IFSC Code is : " + bank29.getIfscCode());
        System.out.println("The Account Type is : " + bank29.getAccountType());
        System.out.println("The Interest Rate is : " + bank29.getInterestRate());
        System.out.println("The Established On is : " + bank29.getEstablishedOn());

    }
}