class CaseEvidenceExecutor {
	
    public static void main(String[] args) {

        CaseEvidence caseEvidence1 = new CaseEvidence();
        caseEvidence1.setEvidenceId(101);
        caseEvidence1.setCaseNumber("2024-CR-001");
        caseEvidence1.setEvidenceType("9mm Shell Casing");
        caseEvidence1.setCollectedBy("Det. Sarah Jenkins");
        caseEvidence1.setCollectedOn("2024-03-01 08:30");
        caseEvidence1.setLocation("North Alleyway");
        caseEvidence1.setStatus("In Lab");
        System.out.println("The Evidence ID is : " + caseEvidence1.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence1.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence1.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence1.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence1.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence1.getLocation());
        System.out.println("The Status is : " + caseEvidence1.getStatus());

        CaseEvidence caseEvidence2 = new CaseEvidence();
        caseEvidence2.setEvidenceId(102);
        caseEvidence2.setCaseNumber("2024-CR-001");
        caseEvidence2.setEvidenceType("Latent Fingerprints");
        caseEvidence2.setCollectedBy("Tech Mark Sloan");
        caseEvidence2.setCollectedOn("2024-03-01 09:15");
        caseEvidence2.setLocation("Glass Entry Door");
        caseEvidence2.setStatus("Processed");
        System.out.println("The Evidence ID is : " + caseEvidence2.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence2.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence2.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence2.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence2.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence2.getLocation());
        System.out.println("The Status is : " + caseEvidence2.getStatus());

        CaseEvidence caseEvidence3 = new CaseEvidence();
        caseEvidence3.setEvidenceId(103);
        caseEvidence3.setCaseNumber("2024-CR-005");
        caseEvidence3.setEvidenceType("Blood Spatter Swab");
        caseEvidence3.setCollectedBy("CSI Maria Gomez");
        caseEvidence3.setCollectedOn("2024-03-02 11:00");
        caseEvidence3.setLocation("Living Room Wall");
        caseEvidence3.setStatus("Cold Storage");
        System.out.println("The Evidence ID is : " + caseEvidence3.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence3.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence3.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence3.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence3.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence3.getLocation());
        System.out.println("The Status is : " + caseEvidence3.getStatus());

        CaseEvidence caseEvidence4 = new CaseEvidence();
        caseEvidence4.setEvidenceId(104);
        caseEvidence4.setCaseNumber("2024-CR-012");
        caseEvidence4.setEvidenceType("Digital Hard Drive");
        caseEvidence4.setCollectedBy("Agent Kyle Reed");
        caseEvidence4.setCollectedOn("2024-03-03 14:20");
        caseEvidence4.setLocation("Home Office Desk");
        caseEvidence4.setStatus("Under Analysis");
        System.out.println("The Evidence ID is : " + caseEvidence4.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence4.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence4.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence4.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence4.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence4.getLocation());
        System.out.println("The Status is : " + caseEvidence4.getStatus());

        CaseEvidence caseEvidence5 = new CaseEvidence();
        caseEvidence5.setEvidenceId(105);
        caseEvidence5.setCaseNumber("2024-CR-012");
        caseEvidence5.setEvidenceType("Encrypted Smartphone");
        caseEvidence5.setCollectedBy("Agent Kyle Reed");
        caseEvidence5.setCollectedOn("2024-03-03 14:25");
        caseEvidence5.setLocation("Suspect's Pocket");
        caseEvidence5.setStatus("Secure Vault");
        System.out.println("The Evidence ID is : " + caseEvidence5.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence5.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence5.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence5.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence5.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence5.getLocation());
        System.out.println("The Status is : " + caseEvidence5.getStatus());

        CaseEvidence caseEvidence6 = new CaseEvidence();
        caseEvidence6.setEvidenceId(106);
        caseEvidence6.setCaseNumber("2024-TH-088");
        caseEvidence6.setEvidenceType("Lockpick Set");
        caseEvidence6.setCollectedBy("Officer Lee");
        caseEvidence6.setCollectedOn("2024-03-04 23:10");
        caseEvidence6.setLocation("Backyard Garden");
        caseEvidence6.setStatus("Property Room");
        System.out.println("The Evidence ID is : " + caseEvidence6.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence6.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence6.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence6.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence6.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence6.getLocation());
        System.out.println("The Status is : " + caseEvidence6.getStatus());

        CaseEvidence caseEvidence7 = new CaseEvidence();
        caseEvidence7.setEvidenceId(107);
        caseEvidence7.setCaseNumber("2024-CR-090");
        caseEvidence7.setEvidenceType("Unknown White Powder");
        caseEvidence7.setCollectedBy("Hazmat Unit 4");
        caseEvidence7.setCollectedOn("2024-03-05 02:00");
        caseEvidence7.setLocation("Kitchen Counter");
        caseEvidence7.setStatus("Chemical Lab");
        System.out.println("The Evidence ID is : " + caseEvidence7.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence7.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence7.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence7.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence7.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence7.getLocation());
        System.out.println("The Status is : " + caseEvidence7.getStatus());

        CaseEvidence caseEvidence8 = new CaseEvidence();
        caseEvidence8.setEvidenceId(108);
        caseEvidence8.setCaseNumber("2024-CR-090");
        caseEvidence8.setEvidenceType("Digital Scale");
        caseEvidence8.setCollectedBy("Det. Sarah Jenkins");
        caseEvidence8.setCollectedOn("2024-03-05 02:45");
        caseEvidence8.setLocation("Kitchen Cupboard");
        caseEvidence8.setStatus("Property Room");
        System.out.println("The Evidence ID is : " + caseEvidence8.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence8.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence8.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence8.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence8.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence8.getLocation());
        System.out.println("The Status is : " + caseEvidence8.getStatus());

        CaseEvidence caseEvidence9 = new CaseEvidence();
        caseEvidence9.setEvidenceId(109);
        caseEvidence9.setCaseNumber("2024-AS-221");
        caseEvidence9.setEvidenceType("Torn Clothing");
        caseEvidence9.setCollectedBy("Officer Brown");
        caseEvidence9.setCollectedOn("2024-03-06 19:12");
        caseEvidence9.setLocation("Street Pavement");
        caseEvidence9.setStatus("Biological Bag");
        System.out.println("The Evidence ID is : " + caseEvidence9.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence9.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence9.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence9.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence9.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence9.getLocation());
        System.out.println("The Status is : " + caseEvidence9.getStatus());

        CaseEvidence caseEvidence10 = new CaseEvidence();
        caseEvidence10.setEvidenceId(110);
        caseEvidence10.setCaseNumber("2024-CR-300");
        caseEvidence10.setEvidenceType("Hair Sample");
        caseEvidence10.setCollectedBy("Tech Mark Sloan");
        caseEvidence10.setCollectedOn("2024-03-07 10:00");
        caseEvidence10.setLocation("Passenger Seat");
        caseEvidence10.setStatus("DNA Lab");
        System.out.println("The Evidence ID is : " + caseEvidence10.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence10.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence10.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence10.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence10.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence10.getLocation());
        System.out.println("The Status is : " + caseEvidence10.getStatus());

        CaseEvidence caseEvidence11 = new CaseEvidence();
        caseEvidence11.setEvidenceId(111);
        caseEvidence11.setCaseNumber("2024-CR-300");
        caseEvidence11.setEvidenceType("Fiber Trace");
        caseEvidence11.setCollectedBy("Tech Mark Sloan");
        caseEvidence11.setCollectedOn("2024-03-07 10:15");
        caseEvidence11.setLocation("Floor Mat");
        caseEvidence11.setStatus("Microscopy");
        System.out.println("The Evidence ID is : " + caseEvidence11.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence11.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence11.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence11.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence11.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence11.getLocation());
        System.out.println("The Status is : " + caseEvidence11.getStatus());

        CaseEvidence caseEvidence12 = new CaseEvidence();
        caseEvidence12.setEvidenceId(112);
        caseEvidence12.setCaseNumber("2024-FR-050");
        caseEvidence12.setEvidenceType("Burned Ledger");
        caseEvidence12.setCollectedBy("Fire Marshal Dave");
        caseEvidence12.setCollectedOn("2024-03-08 13:00");
        caseEvidence12.setLocation("Fireplace Grate");
        caseEvidence12.setStatus("Document Recovery");
        System.out.println("The Evidence ID is : " + caseEvidence12.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence12.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence12.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence12.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence12.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence12.getLocation());
        System.out.println("The Status is : " + caseEvidence12.getStatus());

        CaseEvidence caseEvidence13 = new CaseEvidence();
        caseEvidence13.setEvidenceId(113);
        caseEvidence13.setCaseNumber("2024-FR-050");
        caseEvidence13.setEvidenceType("Gasoline Can");
        caseEvidence13.setCollectedBy("Fire Marshal Dave");
        caseEvidence13.setCollectedOn("2024-03-08 13:30");
        caseEvidence13.setLocation("Garage Corner");
        caseEvidence13.setStatus("Arson Lab");
        System.out.println("The Evidence ID is : " + caseEvidence13.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence13.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence13.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence13.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence13.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence13.getLocation());
        System.out.println("The Status is : " + caseEvidence13.getStatus());

        CaseEvidence caseEvidence14 = new CaseEvidence();
        caseEvidence14.setEvidenceId(114);
        caseEvidence14.setCaseNumber("2024-CR-411");
        caseEvidence14.setEvidenceType("Kitchen Knife");
        caseEvidence14.setCollectedBy("CSI Maria Gomez");
        caseEvidence14.setCollectedOn("2024-03-09 16:40");
        caseEvidence14.setLocation("Under Sofa");
        caseEvidence14.setStatus("Fingerprint Lab");
        System.out.println("The Evidence ID is : " + caseEvidence14.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence14.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence14.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence14.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence14.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence14.getLocation());
        System.out.println("The Status is : " + caseEvidence14.getStatus());

        CaseEvidence caseEvidence15 = new CaseEvidence();
        caseEvidence15.setEvidenceId(115);
        caseEvidence15.setCaseNumber("2024-CR-411");
        caseEvidence15.setEvidenceType("DNA Swab");
        caseEvidence15.setCollectedBy("CSI Maria Gomez");
        caseEvidence15.setCollectedOn("2024-03-09 17:10");
        caseEvidence15.setLocation("Staircase Rail");
        caseEvidence15.setStatus("DNA Lab");
        System.out.println("The Evidence ID is : " + caseEvidence15.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence15.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence15.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence15.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence15.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence15.getLocation());
        System.out.println("The Status is : " + caseEvidence15.getStatus());

        CaseEvidence caseEvidence16 = new CaseEvidence();
        caseEvidence16.setEvidenceId(116);
        caseEvidence16.setCaseNumber("2024-CY-999");
        caseEvidence16.setEvidenceType("USB Flash Drive");
        caseEvidence16.setCollectedBy("Det. Miller");
        caseEvidence16.setCollectedOn("2024-03-10 09:00");
        caseEvidence16.setLocation("Car Console");
        caseEvidence16.setStatus("Digital Lab");
        System.out.println("The Evidence ID is : " + caseEvidence16.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence16.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence16.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence16.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence16.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence16.getLocation());
        System.out.println("The Status is : " + caseEvidence16.getStatus());

        CaseEvidence caseEvidence17 = new CaseEvidence();
        caseEvidence17.setEvidenceId(117);
        caseEvidence17.setCaseNumber("2024-CR-502");
        caseEvidence17.setEvidenceType("Muddy Boot Print");
        caseEvidence17.setCollectedBy("Officer Wright");
        caseEvidence17.setCollectedOn("2024-03-11 07:45");
        caseEvidence17.setLocation("Flower Bed");
        caseEvidence17.setStatus("Impression Cast");
        System.out.println("The Evidence ID is : " + caseEvidence17.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence17.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence17.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence17.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence17.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence17.getLocation());
        System.out.println("The Status is : " + caseEvidence17.getStatus());

        CaseEvidence caseEvidence18 = new CaseEvidence();
        caseEvidence18.setEvidenceId(118);
        caseEvidence18.setCaseNumber("2024-CR-502");
        caseEvidence18.setEvidenceType("Broken Glass");
        caseEvidence18.setCollectedBy("Officer Wright");
        caseEvidence18.setCollectedOn("2024-03-11 08:00");
        caseEvidence18.setLocation("Patio Floor");
        caseEvidence18.setStatus("Trace Lab");
        System.out.println("The Evidence ID is : " + caseEvidence18.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence18.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence18.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence18.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence18.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence18.getLocation());
        System.out.println("The Status is : " + caseEvidence18.getStatus());

        CaseEvidence caseEvidence19 = new CaseEvidence();
        caseEvidence19.setEvidenceId(119);
        caseEvidence19.setCaseNumber("2024-HO-101");
        caseEvidence19.setEvidenceType("Pill Bottle");
        caseEvidence19.setCollectedBy("Coroner Bell");
        caseEvidence19.setCollectedOn("2024-03-12 11:20");
        caseEvidence19.setLocation("Nightstand");
        caseEvidence19.setStatus("Toxicology Lab");
        System.out.println("The Evidence ID is : " + caseEvidence19.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence19.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence19.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence19.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence19.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence19.getLocation());
        System.out.println("The Status is : " + caseEvidence19.getStatus());

        CaseEvidence caseEvidence20 = new CaseEvidence();
        caseEvidence20.setEvidenceId(120);
        caseEvidence20.setCaseNumber("2024-CR-600");
        caseEvidence20.setEvidenceType("Counterfeit Bills");
        caseEvidence20.setCollectedBy("Agent Smith");
        caseEvidence20.setCollectedOn("2024-03-13 15:00");
        caseEvidence20.setLocation("Retail Counter");
        caseEvidence20.setStatus("Federal Vault");
        System.out.println("The Evidence ID is : " + caseEvidence20.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence20.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence20.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence20.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence20.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence20.getLocation());
        System.out.println("The Status is : " + caseEvidence20.getStatus());

        CaseEvidence caseEvidence21 = new CaseEvidence();
        caseEvidence21.setEvidenceId(121);
        caseEvidence21.setCaseNumber("2024-CR-600");
        caseEvidence21.setEvidenceType("Ink Cartridge");
        caseEvidence21.setCollectedBy("Agent Smith");
        caseEvidence21.setCollectedOn("2024-03-13 15:30");
        caseEvidence21.setLocation("Basement");
        caseEvidence21.setStatus("Federal Lab");
        System.out.println("The Evidence ID is : " + caseEvidence21.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence21.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence21.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence21.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence21.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence21.getLocation());
        System.out.println("The Status is : " + caseEvidence21.getStatus());

        CaseEvidence caseEvidence22 = new CaseEvidence();
        caseEvidence22.setEvidenceId(122);
        caseEvidence22.setCaseNumber("2024-RO-777");
        caseEvidence22.setEvidenceType("CCTV Backup");
        caseEvidence22.setCollectedBy("Det. Sarah Jenkins");
        caseEvidence22.setCollectedOn("2024-03-14 10:10");
        caseEvidence22.setLocation("Security Room");
        caseEvidence22.setStatus("Reviewing");
        System.out.println("The Evidence ID is : " + caseEvidence22.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence22.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence22.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence22.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence22.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence22.getLocation());
        System.out.println("The Status is : " + caseEvidence22.getStatus());

        CaseEvidence caseEvidence23 = new CaseEvidence();
        caseEvidence23.setEvidenceId(123);
        caseEvidence23.setCaseNumber("2024-CR-812");
        caseEvidence23.setEvidenceType("Vehicle Paint");
        caseEvidence23.setCollectedBy("Tech Mark Sloan");
        caseEvidence23.setCollectedOn("2024-03-15 12:45");
        caseEvidence23.setLocation("Bumper");
        caseEvidence23.setStatus("Spectroscopy");
        System.out.println("The Evidence ID is : " + caseEvidence23.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence23.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence23.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence23.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence23.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence23.getLocation());
        System.out.println("The Status is : " + caseEvidence23.getStatus());

        CaseEvidence caseEvidence24 = new CaseEvidence();
        caseEvidence24.setEvidenceId(124);
        caseEvidence24.setCaseNumber("2024-CR-812");
        caseEvidence24.setEvidenceType("Broken Tailight");
        caseEvidence24.setCollectedBy("Tech Mark Sloan");
        caseEvidence24.setCollectedOn("2024-03-15 13:00");
        caseEvidence24.setLocation("Intersection");
        caseEvidence24.setStatus("Reconstruction");
        System.out.println("The Evidence ID is : " + caseEvidence24.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence24.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence24.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence24.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence24.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence24.getLocation());
        System.out.println("The Status is : " + caseEvidence24.getStatus());

        CaseEvidence caseEvidence25 = new CaseEvidence();
        caseEvidence25.setEvidenceId(125);
        caseEvidence25.setCaseNumber("2024-CR-900");
        caseEvidence25.setEvidenceType("Handwritten Note");
        caseEvidence25.setCollectedBy("CSI Maria Gomez");
        caseEvidence25.setCollectedOn("2024-03-16 18:20");
        caseEvidence25.setLocation("Trash Bin");
        caseEvidence25.setStatus("Analysis");
        System.out.println("The Evidence ID is : " + caseEvidence25.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence25.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence25.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence25.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence25.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence25.getLocation());
        System.out.println("The Status is : " + caseEvidence25.getStatus());

        CaseEvidence caseEvidence26 = new CaseEvidence();
        caseEvidence26.setEvidenceId(126);
        caseEvidence26.setCaseNumber("2024-CR-900");
        caseEvidence26.setEvidenceType("Fountain Pen");
        caseEvidence26.setCollectedBy("CSI Maria Gomez");
        caseEvidence26.setCollectedOn("2024-03-16 18:30");
        caseEvidence26.setLocation("Study Desk");
        caseEvidence26.setStatus("Property Room");
        System.out.println("The Evidence ID is : " + caseEvidence26.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence26.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence26.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence26.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence26.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence26.getLocation());
        System.out.println("The Status is : " + caseEvidence26.getStatus());

        CaseEvidence caseEvidence27 = new CaseEvidence();
        caseEvidence27.setEvidenceId(127);
        caseEvidence27.setCaseNumber("2024-BG-442");
        caseEvidence27.setEvidenceType("Crowbar");
        caseEvidence27.setCollectedBy("Officer Lee");
        caseEvidence27.setCollectedOn("2024-03-17 01:15");
        caseEvidence27.setLocation("Side Window");
        caseEvidence27.setStatus("Toolmark Lab");
        System.out.println("The Evidence ID is : " + caseEvidence27.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence27.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence27.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence27.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence27.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence27.getLocation());
        System.out.println("The Status is : " + caseEvidence27.getStatus());

        CaseEvidence caseEvidence28 = new CaseEvidence();
        caseEvidence28.setEvidenceId(128);
        caseEvidence28.setCaseNumber("2024-BG-442");
        caseEvidence28.setEvidenceType("Cigarette Butt");
        caseEvidence28.setCollectedBy("Officer Lee");
        caseEvidence28.setCollectedOn("2024-03-17 01:45");
        caseEvidence28.setLocation("Front Porch");
        caseEvidence28.setStatus("DNA Lab");
        System.out.println("The Evidence ID is : " + caseEvidence28.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence28.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence28.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence28.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence28.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence28.getLocation());
        System.out.println("The Status is : " + caseEvidence28.getStatus());

        CaseEvidence caseEvidence29 = new CaseEvidence();
        caseEvidence29.setEvidenceId(129);
        caseEvidence29.setCaseNumber("2024-CR-111");
        caseEvidence29.setEvidenceType("Soil Sample");
        caseEvidence29.setCollectedBy("Dr. Reed");
        caseEvidence29.setCollectedOn("2024-03-18 09:30");
        caseEvidence29.setLocation("Tire Treads");
        caseEvidence29.setStatus("Mineralogy");
        System.out.println("The Evidence ID is : " + caseEvidence29.getEvidenceId());
        System.out.println("The Case Number is : " + caseEvidence29.getCaseNumber());
        System.out.println("The Evidence Type is : " + caseEvidence29.getEvidenceType());
        System.out.println("The Collected By is : " + caseEvidence29.getCollectedBy());
        System.out.println("The Collected On is : " + caseEvidence29.getCollectedOn());
        System.out.println("The Location is : " + caseEvidence29.getLocation());
        System.out.println("The Status is : " + caseEvidence29.getStatus());

    }
}