class GpsDetailsExecutor {
    public static void main(String[] args) {

        GpsDetails gpsDetails1 = new GpsDetails();
        gpsDetails1.setGpsId(1);
        gpsDetails1.setDeviceName("SkyTrack-Alpha");
        gpsDetails1.setLatitude("40.7128 N");
        gpsDetails1.setLongitude("74.0060 W");
        gpsDetails1.setAltitude("10m");
        gpsDetails1.setSpeed("0 km/h");
        gpsDetails1.setLastUpdated("2026-03-31 10:00:05");
        System.out.println("The GPS ID is : " + gpsDetails1.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails1.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails1.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails1.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails1.getAltitude());
        System.out.println("The Speed is : " + gpsDetails1.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails1.getLastUpdated());

        GpsDetails gpsDetails2 = new GpsDetails();
        gpsDetails2.setGpsId(2);
        gpsDetails2.setDeviceName("FleetMaster-02");
        gpsDetails2.setLatitude("34.0522 N");
        gpsDetails2.setLongitude("118.2437 W");
        gpsDetails2.setAltitude("85m");
        gpsDetails2.setSpeed("65 km/h");
        gpsDetails2.setLastUpdated("2026-03-31 10:05:12");
        System.out.println("The GPS ID is : " + gpsDetails2.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails2.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails2.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails2.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails2.getAltitude());
        System.out.println("The Speed is : " + gpsDetails2.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails2.getLastUpdated());

        GpsDetails gpsDetails3 = new GpsDetails();
        gpsDetails3.setGpsId(3);
        gpsDetails3.setDeviceName("NaviCore-X");
        gpsDetails3.setLatitude("51.5074 N");
        gpsDetails3.setLongitude("0.1278 W");
        gpsDetails3.setAltitude("35m");
        gpsDetails3.setSpeed("12 km/h");
        gpsDetails3.setLastUpdated("2026-03-31 10:12:45");
        System.out.println("The GPS ID is : " + gpsDetails3.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails3.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails3.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails3.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails3.getAltitude());
        System.out.println("The Speed is : " + gpsDetails3.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails3.getLastUpdated());

        GpsDetails gpsDetails4 = new GpsDetails();
        gpsDetails4.setGpsId(4);
        gpsDetails4.setDeviceName("GeoPulse-Prime");
        gpsDetails4.setLatitude("48.8566 N");
        gpsDetails4.setLongitude("2.3522 E");
        gpsDetails4.setAltitude("76m");
        gpsDetails4.setSpeed("0 km/h");
        gpsDetails4.setLastUpdated("2026-03-31 10:15:30");
        System.out.println("The GPS ID is : " + gpsDetails4.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails4.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails4.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails4.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails4.getAltitude());
        System.out.println("The Speed is : " + gpsDetails4.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails4.getLastUpdated());

        GpsDetails gpsDetails5 = new GpsDetails();
        gpsDetails5.setGpsId(5);
        gpsDetails5.setDeviceName("RouteLink-500");
        gpsDetails5.setLatitude("35.6762 N");
        gpsDetails5.setLongitude("139.6503 E");
        gpsDetails5.setAltitude("40m");
        gpsDetails5.setSpeed("110 km/h");
        gpsDetails5.setLastUpdated("2026-03-31 10:20:00");
        System.out.println("The GPS ID is : " + gpsDetails5.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails5.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails5.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails5.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails5.getAltitude());
        System.out.println("The Speed is : " + gpsDetails5.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails5.getLastUpdated());

        GpsDetails gpsDetails6 = new GpsDetails();
        gpsDetails6.setGpsId(6);
        gpsDetails6.setDeviceName("StarPath-9");
        gpsDetails6.setLatitude("-33.8688 S");
        gpsDetails6.setLongitude("151.2093 E");
        gpsDetails6.setAltitude("3m");
        gpsDetails6.setSpeed("45 km/h");
        gpsDetails6.setLastUpdated("2026-03-31 10:22:18");
        System.out.println("The GPS ID is : " + gpsDetails6.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails6.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails6.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails6.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails6.getAltitude());
        System.out.println("The Speed is : " + gpsDetails6.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails6.getLastUpdated());

        GpsDetails gpsDetails7 = new GpsDetails();
        gpsDetails7.setGpsId(7);
        gpsDetails7.setDeviceName("ApexTracker-Z");
        gpsDetails7.setLatitude("25.2048 N");
        gpsDetails7.setLongitude("55.2708 E");
        gpsDetails7.setAltitude("12m");
        gpsDetails7.setSpeed("80 km/h");
        gpsDetails7.setLastUpdated("2026-03-31 10:25:55");
        System.out.println("The GPS ID is : " + gpsDetails7.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails7.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails7.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails7.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails7.getAltitude());
        System.out.println("The Speed is : " + gpsDetails7.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails7.getLastUpdated());

        GpsDetails gpsDetails8 = new GpsDetails();
        gpsDetails8.setGpsId(8);
        gpsDetails8.setDeviceName("AtlasRover-M1");
        gpsDetails8.setLatitude("55.7558 N");
        gpsDetails8.setLongitude("37.6173 E");
        gpsDetails8.setAltitude("156m");
        gpsDetails8.setSpeed("20 km/h");
        gpsDetails8.setLastUpdated("2026-03-31 10:28:40");
        System.out.println("The GPS ID is : " + gpsDetails8.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails8.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails8.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails8.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails8.getAltitude());
        System.out.println("The Speed is : " + gpsDetails8.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails8.getLastUpdated());

        GpsDetails gpsDetails9 = new GpsDetails();
        gpsDetails9.setGpsId(9);
        gpsDetails9.setDeviceName("LogiWay-Pro");
        gpsDetails9.setLatitude("-23.5505 S");
        gpsDetails9.setLongitude("-46.6333 W");
        gpsDetails9.setAltitude("760m");
        gpsDetails9.setSpeed("55 km/h");
        gpsDetails9.setLastUpdated("2026-03-31 10:30:12");
        System.out.println("The GPS ID is : " + gpsDetails9.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails9.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails9.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails9.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails9.getAltitude());
        System.out.println("The Speed is : " + gpsDetails9.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails9.getLastUpdated());

        GpsDetails gpsDetails10 = new GpsDetails();
        gpsDetails10.setGpsId(10);
        gpsDetails10.setDeviceName("TerraScan-V2");
        gpsDetails10.setLatitude("19.4326 N");
        gpsDetails10.setLongitude("-99.1332 W");
        gpsDetails10.setAltitude("2240m");
        gpsDetails10.setSpeed("15 km/h");
        gpsDetails10.setLastUpdated("2026-03-31 10:33:05");
        System.out.println("The GPS ID is : " + gpsDetails10.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails10.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails10.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails10.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails10.getAltitude());
        System.out.println("The Speed is : " + gpsDetails10.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails10.getLastUpdated());

        GpsDetails gpsDetails11 = new GpsDetails();
        gpsDetails11.setGpsId(11);
        gpsDetails11.setDeviceName("VistaNav-Lite");
        gpsDetails11.setLatitude("28.6139 N");
        gpsDetails11.setLongitude("77.2090 E");
        gpsDetails11.setAltitude("216m");
        gpsDetails11.setSpeed("40 km/h");
        gpsDetails11.setLastUpdated("2026-03-31 10:35:44");
        System.out.println("The GPS ID is : " + gpsDetails11.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails11.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails11.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails11.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails11.getAltitude());
        System.out.println("The Speed is : " + gpsDetails11.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails11.getLastUpdated());

        GpsDetails gpsDetails12 = new GpsDetails();
        gpsDetails12.setGpsId(12);
        gpsDetails12.setDeviceName("OceanPoint-3");
        gpsDetails12.setLatitude("1.3521 N");
        gpsDetails12.setLongitude("103.8198 E");
        gpsDetails12.setAltitude("15m");
        gpsDetails12.setSpeed("0 km/h");
        gpsDetails12.setLastUpdated("2026-03-31 10:38:21");
        System.out.println("The GPS ID is : " + gpsDetails12.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails12.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails12.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails12.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails12.getAltitude());
        System.out.println("The Speed is : " + gpsDetails12.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails12.getLastUpdated());

        GpsDetails gpsDetails13 = new GpsDetails();
        gpsDetails13.setGpsId(13);
        gpsDetails13.setDeviceName("SummitSeeker");
        gpsDetails13.setLatitude("47.3769 N");
        gpsDetails13.setLongitude("8.5417 E");
        gpsDetails13.setAltitude("408m");
        gpsDetails13.setSpeed("5 km/h");
        gpsDetails13.setLastUpdated("2026-03-31 10:40:59");
        System.out.println("The GPS ID is : " + gpsDetails13.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails13.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails13.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails13.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails13.getAltitude());
        System.out.println("The Speed is : " + gpsDetails13.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails13.getLastUpdated());

        GpsDetails gpsDetails14 = new GpsDetails();
        gpsDetails14.setGpsId(14);
        gpsDetails14.setDeviceName("UrbanEagle-X1");
        gpsDetails14.setLatitude("41.9028 N");
        gpsDetails14.setLongitude("12.4964 E");
        gpsDetails14.setAltitude("21m");
        gpsDetails14.setSpeed("32 km/h");
        gpsDetails14.setLastUpdated("2026-03-31 10:42:33");
        System.out.println("The GPS ID is : " + gpsDetails14.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails14.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails14.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails14.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails14.getAltitude());
        System.out.println("The Speed is : " + gpsDetails14.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails14.getLastUpdated());

        GpsDetails gpsDetails15 = new GpsDetails();
        gpsDetails15.setGpsId(15);
        gpsDetails15.setDeviceName("CargoGuard-99");
        gpsDetails15.setLatitude("31.2304 N");
        gpsDetails15.setLongitude("121.4737 E");
        gpsDetails15.setAltitude("4m");
        gpsDetails15.setSpeed("18 km/h");
        gpsDetails15.setLastUpdated("2026-03-31 10:45:00");
        System.out.println("The GPS ID is : " + gpsDetails15.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails15.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails15.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails15.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails15.getAltitude());
        System.out.println("The Speed is : " + gpsDetails15.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails15.getLastUpdated());

        GpsDetails gpsDetails16 = new GpsDetails();
        gpsDetails16.setGpsId(16);
        gpsDetails16.setDeviceName("SwiftPath-04");
        gpsDetails16.setLatitude("52.5200 N");
        gpsDetails16.setLongitude("13.4050 E");
        gpsDetails16.setAltitude("34m");
        gpsDetails16.setSpeed("55 km/h");
        gpsDetails16.setLastUpdated("2026-03-31 10:48:15");
        System.out.println("The GPS ID is : " + gpsDetails16.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails16.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails16.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails16.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails16.getAltitude());
        System.out.println("The Speed is : " + gpsDetails16.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails16.getLastUpdated());

        GpsDetails gpsDetails17 = new GpsDetails();
        gpsDetails17.setGpsId(17);
        gpsDetails17.setDeviceName("HorizonLink");
        gpsDetails17.setLatitude("30.0444 N");
        gpsDetails17.setLongitude("31.2357 E");
        gpsDetails17.setAltitude("23m");
        gpsDetails17.setSpeed("0 km/h");
        gpsDetails17.setLastUpdated("2026-03-31 10:50:55");
        System.out.println("The GPS ID is : " + gpsDetails17.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails17.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails17.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails17.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails17.getAltitude());
        System.out.println("The Speed is : " + gpsDetails17.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails17.getLastUpdated());

        GpsDetails gpsDetails18 = new GpsDetails();
        gpsDetails18.setGpsId(18);
        gpsDetails18.setDeviceName("FalconEye-7");
        gpsDetails18.setLatitude("39.9042 N");
        gpsDetails18.setLongitude("116.4074 E");
        gpsDetails18.setAltitude("43m");
        gpsDetails18.setSpeed("92 km/h");
        gpsDetails18.setLastUpdated("2026-03-31 10:52:10");
        System.out.println("The GPS ID is : " + gpsDetails18.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails18.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails18.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails18.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails18.getAltitude());
        System.out.println("The Speed is : " + gpsDetails18.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails18.getLastUpdated());

        GpsDetails gpsDetails19 = new GpsDetails();
        gpsDetails19.setGpsId(19);
        gpsDetails19.setDeviceName("RoverCloud");
        gpsDetails19.setLatitude("-26.2041 S");
        gpsDetails19.setLongitude("28.0473 E");
        gpsDetails19.setAltitude("1753m");
        gpsDetails19.setSpeed("60 km/h");
        gpsDetails19.setLastUpdated("2026-03-31 10:55:00");
        System.out.println("The GPS ID is : " + gpsDetails19.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails19.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails19.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails19.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails19.getAltitude());
        System.out.println("The Speed is : " + gpsDetails19.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails19.getLastUpdated());

        GpsDetails gpsDetails20 = new GpsDetails();
        gpsDetails20.setGpsId(20);
        gpsDetails20.setDeviceName("NanoLocate-S");
        gpsDetails20.setLatitude("37.5665 N");
        gpsDetails20.setLongitude("126.9780 E");
        gpsDetails20.setAltitude("38m");
        gpsDetails20.setSpeed("10 km/h");
        gpsDetails20.setLastUpdated("2026-03-31 10:57:45");
        System.out.println("The GPS ID is : " + gpsDetails20.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails20.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails20.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails20.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails20.getAltitude());
        System.out.println("The Speed is : " + gpsDetails20.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails20.getLastUpdated());

        GpsDetails gpsDetails21 = new GpsDetails();
        gpsDetails21.setGpsId(21);
        gpsDetails21.setDeviceName("BlueTrack-X");
        gpsDetails21.setLatitude("55.6761 N");
        gpsDetails21.setLongitude("12.5683 E");
        gpsDetails21.setAltitude("5m");
        gpsDetails21.setSpeed("25 km/h");
        gpsDetails21.setLastUpdated("2026-03-31 11:00:00");
        System.out.println("The GPS ID is : " + gpsDetails21.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails21.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails21.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails21.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails21.getAltitude());
        System.out.println("The Speed is : " + gpsDetails21.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails21.getLastUpdated());

        GpsDetails gpsDetails22 = new GpsDetails();
        gpsDetails22.setGpsId(22);
        gpsDetails22.setDeviceName("MapStreamer");
        gpsDetails22.setLatitude("33.4484 N");
        gpsDetails22.setLongitude("-112.0740 W");
        gpsDetails22.setAltitude("331m");
        gpsDetails22.setSpeed("75 km/h");
        gpsDetails22.setLastUpdated("2026-03-31 11:02:30");
        System.out.println("The GPS ID is : " + gpsDetails22.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails22.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails22.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails22.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails22.getAltitude());
        System.out.println("The Speed is : " + gpsDetails22.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails22.getLastUpdated());

        GpsDetails gpsDetails23 = new GpsDetails();
        gpsDetails23.setGpsId(23);
        gpsDetails23.setDeviceName("VectorUnit-5");
        gpsDetails23.setLatitude("59.3293 N");
        gpsDetails23.setLongitude("18.0686 E");
        gpsDetails23.setAltitude("28m");
        gpsDetails23.setSpeed("0 km/h");
        gpsDetails23.setLastUpdated("2026-03-31 11:05:12");
        System.out.println("The GPS ID is : " + gpsDetails23.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails23.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails23.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails23.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails23.getAltitude());
        System.out.println("The Speed is : " + gpsDetails23.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails23.getLastUpdated());

        GpsDetails gpsDetails24 = new GpsDetails();
        gpsDetails24.setGpsId(24);
        gpsDetails24.setDeviceName("GlobeRunner");
        gpsDetails24.setLatitude("-34.6037 S");
        gpsDetails24.setLongitude("-58.3816 W");
        gpsDetails24.setAltitude("25m");
        gpsDetails24.setSpeed("42 km/h");
        gpsDetails24.setLastUpdated("2026-03-31 11:08:44");
        System.out.println("The GPS ID is : " + gpsDetails24.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails24.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails24.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails24.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails24.getAltitude());
        System.out.println("The Speed is : " + gpsDetails24.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails24.getLastUpdated());

        GpsDetails gpsDetails25 = new GpsDetails();
        gpsDetails25.setGpsId(25);
        gpsDetails25.setDeviceName("PinnacleNav");
        gpsDetails25.setLatitude("53.3498 N");
        gpsDetails25.setLongitude("-6.2603 W");
        gpsDetails25.setAltitude("8m");
        gpsDetails25.setSpeed("15 km/h");
        gpsDetails25.setLastUpdated("2026-03-31 11:10:05");
        System.out.println("The GPS ID is : " + gpsDetails25.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails25.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails25.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails25.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails25.getAltitude());
        System.out.println("The Speed is : " + gpsDetails25.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails25.getLastUpdated());

        GpsDetails gpsDetails26 = new GpsDetails();
        gpsDetails26.setGpsId(26);
        gpsDetails26.setDeviceName("EchoTrack-R1");
        gpsDetails26.setLatitude("52.3676 N");
        gpsDetails26.setLongitude("4.9041 E");
        gpsDetails26.setAltitude("-2m");
        gpsDetails26.setSpeed("12 km/h");
        gpsDetails26.setLastUpdated("2026-03-31 11:12:30");
        System.out.println("The GPS ID is : " + gpsDetails26.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails26.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails26.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails26.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails26.getAltitude());
        System.out.println("The Speed is : " + gpsDetails26.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails26.getLastUpdated());

        GpsDetails gpsDetails27 = new GpsDetails();
        gpsDetails27.setGpsId(27);
        gpsDetails27.setDeviceName("SolarisTracker");
        gpsDetails27.setLatitude("45.4215 N");
        gpsDetails27.setLongitude("-75.6972 W");
        gpsDetails27.setAltitude("70m");
        gpsDetails27.setSpeed("50 km/h");
        gpsDetails27.setLastUpdated("2026-03-31 11:15:55");
        System.out.println("The GPS ID is : " + gpsDetails27.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails27.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails27.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails27.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails27.getAltitude());
        System.out.println("The Speed is : " + gpsDetails27.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails27.getLastUpdated());

        GpsDetails gpsDetails28 = new GpsDetails();
        gpsDetails28.setGpsId(28);
        gpsDetails28.setDeviceName("DeepLink-90");
        gpsDetails28.setLatitude("22.3193 N");
        gpsDetails28.setLongitude("114.1694 E");
        gpsDetails28.setAltitude("2m");
        gpsDetails28.setSpeed("3 km/h");
        gpsDetails28.setLastUpdated("2026-03-31 11:18:20");
        System.out.println("The GPS ID is : " + gpsDetails28.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails28.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails28.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails28.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails28.getAltitude());
        System.out.println("The Speed is : " + gpsDetails28.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails28.getLastUpdated());

        GpsDetails gpsDetails29 = new GpsDetails();
        gpsDetails29.setGpsId(29);
        gpsDetails29.setDeviceName("TransitNode-0");
        gpsDetails29.setLatitude("50.0755 N");
        gpsDetails29.setLongitude("14.4378 E");
        gpsDetails29.setAltitude("190m");
        gpsDetails29.setSpeed("28 km/h");
        gpsDetails29.setLastUpdated("2026-03-31 11:20:45");
        System.out.println("The GPS ID is : " + gpsDetails29.getGpsId());
        System.out.println("The Device Name is : " + gpsDetails29.getDeviceName());
        System.out.println("The Latitude is : " + gpsDetails29.getLatitude());
        System.out.println("The Longitude is : " + gpsDetails29.getLongitude());
        System.out.println("The Altitude is : " + gpsDetails29.getAltitude());
        System.out.println("The Speed is : " + gpsDetails29.getSpeed());
        System.out.println("The Last Updated is : " + gpsDetails29.getLastUpdated());

    }
}