class IndianArmyExecutor {
    public static void main(String[] args) {

        IndianArmy indianArmy1 = new IndianArmy();
        indianArmy1.setSoldierId(1);
        indianArmy1.setSoldierName("Sam Manekshaw");
        indianArmy1.setRank("Field Marshal");
        indianArmy1.setRegiment("8 Gorkha Rifles");
        indianArmy1.setPostingArea("New Delhi");
        indianArmy1.setEnrolledOn("1934-02-01");
        indianArmy1.setMedals("Padma Vibhushan, MC");
        System.out.println("The Soldier ID is : " + indianArmy1.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy1.getSoldierName());
        System.out.println("The Rank is : " + indianArmy1.getRank());
        System.out.println("The Regiment is : " + indianArmy1.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy1.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy1.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy1.getMedals());

        IndianArmy indianArmy2 = new IndianArmy();
        indianArmy2.setSoldierId(2);
        indianArmy2.setSoldierName("Vikram Batra");
        indianArmy2.setRank("Captain");
        indianArmy2.setRegiment("13 Jammu and Kashmir Rifles");
        indianArmy2.setPostingArea("Kargil");
        indianArmy2.setEnrolledOn("1997-12-06");
        indianArmy2.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy2.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy2.getSoldierName());
        System.out.println("The Rank is : " + indianArmy2.getRank());
        System.out.println("The Regiment is : " + indianArmy2.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy2.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy2.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy2.getMedals());

        IndianArmy indianArmy3 = new IndianArmy();
        indianArmy3.setSoldierId(3);
        indianArmy3.setSoldierName("Manoj Kumar Pandey");
        indianArmy3.setRank("Captain");
        indianArmy3.setRegiment("1/11 Gorkha Rifles");
        indianArmy3.setPostingArea("Batalik");
        indianArmy3.setEnrolledOn("1997-06-07");
        indianArmy3.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy3.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy3.getSoldierName());
        System.out.println("The Rank is : " + indianArmy3.getRank());
        System.out.println("The Regiment is : " + indianArmy3.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy3.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy3.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy3.getMedals());

        IndianArmy indianArmy4 = new IndianArmy();
        indianArmy4.setSoldierId(4);
        indianArmy4.setSoldierName("Sandeep Unnikrishnan");
        indianArmy4.setRank("Major");
        indianArmy4.setRegiment("7th Bihar / NSG");
        indianArmy4.setPostingArea("Mumbai");
        indianArmy4.setEnrolledOn("1999-06-12");
        indianArmy4.setMedals("Ashoka Chakra");
        System.out.println("The Soldier ID is : " + indianArmy4.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy4.getSoldierName());
        System.out.println("The Rank is : " + indianArmy4.getRank());
        System.out.println("The Regiment is : " + indianArmy4.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy4.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy4.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy4.getMedals());

        IndianArmy indianArmy5 = new IndianArmy();
        indianArmy5.setSoldierId(5);
        indianArmy5.setSoldierName("Yogendra Singh Yadav");
        indianArmy5.setRank("Subedar Major");
        indianArmy5.setRegiment("18 Grenadiers");
        indianArmy5.setPostingArea("Tiger Hill");
        indianArmy5.setEnrolledOn("1996-12-27");
        indianArmy5.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy5.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy5.getSoldierName());
        System.out.println("The Rank is : " + indianArmy5.getRank());
        System.out.println("The Regiment is : " + indianArmy5.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy5.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy5.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy5.getMedals());

        IndianArmy indianArmy6 = new IndianArmy();
        indianArmy6.setSoldierId(6);
        indianArmy6.setSoldierName("Arjan Singh");
        indianArmy6.setRank("Marshal of the Air Force");
        indianArmy6.setRegiment("IAF (Honorary)");
        indianArmy6.setPostingArea("New Delhi");
        indianArmy6.setEnrolledOn("1939-12-01");
        indianArmy6.setMedals("Padma Vibhushan, DFC");
        System.out.println("The Soldier ID is : " + indianArmy6.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy6.getSoldierName());
        System.out.println("The Rank is : " + indianArmy6.getRank());
        System.out.println("The Regiment is : " + indianArmy6.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy6.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy6.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy6.getMedals());

        IndianArmy indianArmy7 = new IndianArmy();
        indianArmy7.setSoldierId(7);
        indianArmy7.setSoldierName("Somnath Sharma");
        indianArmy7.setRank("Major");
        indianArmy7.setRegiment("4th Kumaon");
        indianArmy7.setPostingArea("Badgam");
        indianArmy7.setEnrolledOn("1942-02-22");
        indianArmy7.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy7.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy7.getSoldierName());
        System.out.println("The Rank is : " + indianArmy7.getRank());
        System.out.println("The Regiment is : " + indianArmy7.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy7.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy7.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy7.getMedals());

        IndianArmy indianArmy8 = new IndianArmy();
        indianArmy8.setSoldierId(8);
        indianArmy8.setSoldierName("Jaswant Singh Rawat");
        indianArmy8.setRank("Rifleman");
        indianArmy8.setRegiment("4th Garhwal Rifles");
        indianArmy8.setPostingArea("Tawang");
        indianArmy8.setEnrolledOn("1960-08-19");
        indianArmy8.setMedals("Maha Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy8.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy8.getSoldierName());
        System.out.println("The Rank is : " + indianArmy8.getRank());
        System.out.println("The Regiment is : " + indianArmy8.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy8.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy8.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy8.getMedals());

        IndianArmy indianArmy9 = new IndianArmy();
        indianArmy9.setSoldierId(9);
        indianArmy9.setSoldierName("Arun Khetarpal");
        indianArmy9.setRank("Second Lieutenant");
        indianArmy9.setRegiment("17 Poona Horse");
        indianArmy9.setPostingArea("Shakar Garh");
        indianArmy9.setEnrolledOn("1971-06-13");
        indianArmy9.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy9.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy9.getSoldierName());
        System.out.println("The Rank is : " + indianArmy9.getRank());
        System.out.println("The Regiment is : " + indianArmy9.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy9.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy9.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy9.getMedals());

        IndianArmy indianArmy10 = new IndianArmy();
        indianArmy10.setSoldierId(10);
        indianArmy10.setSoldierName("Sanjay Kumar");
        indianArmy10.setRank("Subedar");
        indianArmy10.setRegiment("13 J&K Rifles");
        indianArmy10.setPostingArea("Muskoh Valley");
        indianArmy10.setEnrolledOn("1996-06-04");
        indianArmy10.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy10.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy10.getSoldierName());
        System.out.println("The Rank is : " + indianArmy10.getRank());
        System.out.println("The Regiment is : " + indianArmy10.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy10.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy10.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy10.getMedals());

        IndianArmy indianArmy11 = new IndianArmy();
        indianArmy11.setSoldierId(11);
        indianArmy11.setSoldierName("Abhinandan Varthaman");
        indianArmy11.setRank("Group Captain");
        indianArmy11.setRegiment("IAF Attaché");
        indianArmy11.setPostingArea("Srinagar");
        indianArmy11.setEnrolledOn("2004-06-19");
        indianArmy11.setMedals("Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy11.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy11.getSoldierName());
        System.out.println("The Rank is : " + indianArmy11.getRank());
        System.out.println("The Regiment is : " + indianArmy11.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy11.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy11.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy11.getMedals());

        IndianArmy indianArmy12 = new IndianArmy();
        indianArmy12.setSoldierId(12);
        indianArmy12.setSoldierName("Jadunath Singh");
        indianArmy12.setRank("Naik");
        indianArmy12.setRegiment("1 Rajput");
        indianArmy12.setPostingArea("Naushera");
        indianArmy12.setEnrolledOn("1941-12-01");
        indianArmy12.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy12.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy12.getSoldierName());
        System.out.println("The Rank is : " + indianArmy12.getRank());
        System.out.println("The Regiment is : " + indianArmy12.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy12.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy12.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy12.getMedals());

        IndianArmy indianArmy13 = new IndianArmy();
        indianArmy13.setSoldierId(13);
        indianArmy13.setSoldierName("Piru Singh");
        indianArmy13.setRank("Company Havildar Major");
        indianArmy13.setRegiment("6th Rajputana Rifles");
        indianArmy13.setPostingArea("Tithwal");
        indianArmy13.setEnrolledOn("1936-05-20");
        indianArmy13.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy13.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy13.getSoldierName());
        System.out.println("The Rank is : " + indianArmy13.getRank());
        System.out.println("The Regiment is : " + indianArmy13.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy13.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy13.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy13.getMedals());

        IndianArmy indianArmy14 = new IndianArmy();
        indianArmy14.setSoldierId(14);
        indianArmy14.setSoldierName("Gurbachan Singh Salaria");
        indianArmy14.setRank("Captain");
        indianArmy14.setRegiment("3/1 Gorkha Rifles");
        indianArmy14.setPostingArea("Congo");
        indianArmy14.setEnrolledOn("1954-06-09");
        indianArmy14.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy14.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy14.getSoldierName());
        System.out.println("The Rank is : " + indianArmy14.getRank());
        System.out.println("The Regiment is : " + indianArmy14.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy14.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy14.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy14.getMedals());

        IndianArmy indianArmy15 = new IndianArmy();
        indianArmy15.setSoldierId(15);
        indianArmy15.setSoldierName("Dhan Singh Thapa");
        indianArmy15.setRank("Major");
        indianArmy15.setRegiment("1/8 Gorkha Rifles");
        indianArmy15.setPostingArea("Ladakh");
        indianArmy15.setEnrolledOn("1949-08-28");
        indianArmy15.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy15.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy15.getSoldierName());
        System.out.println("The Rank is : " + indianArmy15.getRank());
        System.out.println("The Regiment is : " + indianArmy15.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy15.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy15.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy15.getMedals());

        IndianArmy indianArmy16 = new IndianArmy();
        indianArmy16.setSoldierId(16);
        indianArmy16.setSoldierName("Joginder Singh");
        indianArmy16.setRank("Subedar");
        indianArmy16.setRegiment("1 Sikh");
        indianArmy16.setPostingArea("Bum La");
        indianArmy16.setEnrolledOn("1936-09-28");
        indianArmy16.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy16.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy16.getSoldierName());
        System.out.println("The Rank is : " + indianArmy16.getRank());
        System.out.println("The Regiment is : " + indianArmy16.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy16.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy16.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy16.getMedals());

        IndianArmy indianArmy17 = new IndianArmy();
        indianArmy17.setSoldierId(17);
        indianArmy17.setSoldierName("Shaitan Singh");
        indianArmy17.setRank("Major");
        indianArmy17.setRegiment("13 Kumaon");
        indianArmy17.setPostingArea("Rezang La");
        indianArmy17.setEnrolledOn("1949-08-01");
        indianArmy17.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy17.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy17.getSoldierName());
        System.out.println("The Rank is : " + indianArmy17.getRank());
        System.out.println("The Regiment is : " + indianArmy17.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy17.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy17.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy17.getMedals());

        IndianArmy indianArmy18 = new IndianArmy();
        indianArmy18.setSoldierId(18);
        indianArmy18.setSoldierName("Abdul Hamid");
        indianArmy18.setRank("Company Quartermaster Havildar");
        indianArmy18.setRegiment("4 Grenadiers");
        indianArmy18.setPostingArea("Khem Karan");
        indianArmy18.setEnrolledOn("1954-12-27");
        indianArmy18.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy18.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy18.getSoldierName());
        System.out.println("The Rank is : " + indianArmy18.getRank());
        System.out.println("The Regiment is : " + indianArmy18.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy18.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy18.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy18.getMedals());

        IndianArmy indianArmy19 = new IndianArmy();
        indianArmy19.setSoldierId(19);
        indianArmy19.setSoldierName("Albert Ekka");
        indianArmy19.setRank("Lance Naik");
        indianArmy19.setRegiment("14 Guards");
        indianArmy19.setPostingArea("Gangasagar");
        indianArmy19.setEnrolledOn("1962-12-27");
        indianArmy19.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy19.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy19.getSoldierName());
        System.out.println("The Rank is : " + indianArmy19.getRank());
        System.out.println("The Regiment is : " + indianArmy19.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy19.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy19.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy19.getMedals());

        IndianArmy indianArmy20 = new IndianArmy();
        indianArmy20.setSoldierId(20);
        indianArmy20.setSoldierName("Nirmal Jit Singh Sekhon");
        indianArmy20.setRank("Flying Officer");
        indianArmy20.setRegiment("IAF No.18 Sqn");
        indianArmy20.setPostingArea("Srinagar");
        indianArmy20.setEnrolledOn("1967-06-04");
        indianArmy20.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy20.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy20.getSoldierName());
        System.out.println("The Rank is : " + indianArmy20.getRank());
        System.out.println("The Regiment is : " + indianArmy20.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy20.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy20.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy20.getMedals());

        IndianArmy indianArmy21 = new IndianArmy();
        indianArmy21.setSoldierId(21);
        indianArmy21.setSoldierName("Hoshiar Singh");
        indianArmy21.setRank("Major");
        indianArmy21.setRegiment("3 Grenadiers");
        indianArmy21.setPostingArea("Basantar River");
        indianArmy21.setEnrolledOn("1963-06-30");
        indianArmy21.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy21.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy21.getSoldierName());
        System.out.println("The Rank is : " + indianArmy21.getRank());
        System.out.println("The Regiment is : " + indianArmy21.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy21.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy21.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy21.getMedals());

        IndianArmy indianArmy22 = new IndianArmy();
        indianArmy22.setSoldierId(22);
        indianArmy22.setSoldierName("Bana Singh");
        indianArmy22.setRank("Subedar Major");
        indianArmy22.setRegiment("8 J&K Light Infantry");
        indianArmy22.setPostingArea("Siachen Glacier");
        indianArmy22.setEnrolledOn("1969-01-06");
        indianArmy22.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy22.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy22.getSoldierName());
        System.out.println("The Rank is : " + indianArmy22.getRank());
        System.out.println("The Regiment is : " + indianArmy22.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy22.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy22.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy22.getMedals());

        IndianArmy indianArmy23 = new IndianArmy();
        indianArmy23.setSoldierId(23);
        indianArmy23.setSoldierName("Ramaswamy Parameswaran");
        indianArmy23.setRank("Major");
        indianArmy23.setRegiment("8 Mahar Regiment");
        indianArmy23.setPostingArea("Sri Lanka");
        indianArmy23.setEnrolledOn("1972-01-16");
        indianArmy23.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy23.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy23.getSoldierName());
        System.out.println("The Rank is : " + indianArmy23.getRank());
        System.out.println("The Regiment is : " + indianArmy23.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy23.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy23.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy23.getMedals());

        IndianArmy indianArmy24 = new IndianArmy();
        indianArmy24.setSoldierId(24);
        indianArmy24.setSoldierName("Karam Singh");
        indianArmy24.setRank("Subedar");
        indianArmy24.setRegiment("1 Sikh");
        indianArmy24.setPostingArea("Richmar Gali");
        indianArmy24.setEnrolledOn("1941-09-15");
        indianArmy24.setMedals("Param Vir Chakra");
        System.out.println("The Soldier ID is : " + indianArmy24.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy24.getSoldierName());
        System.out.println("The Rank is : " + indianArmy24.getRank());
        System.out.println("The Regiment is : " + indianArmy24.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy24.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy24.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy24.getMedals());

        IndianArmy indianArmy25 = new IndianArmy();
        indianArmy25.setSoldierId(25);
        indianArmy25.setSoldierName("Umrao Singh");
        indianArmy25.setRank("Havildar");
        indianArmy25.setRegiment("Royal Indian Artillery");
        indianArmy25.setPostingArea("Kaladan Valley");
        indianArmy25.setEnrolledOn("1939-11-01");
        indianArmy25.setMedals("Victoria Cross");
        System.out.println("The Soldier ID is : " + indianArmy25.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy25.getSoldierName());
        System.out.println("The Rank is : " + indianArmy25.getRank());
        System.out.println("The Regiment is : " + indianArmy25.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy25.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy25.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy25.getMedals());

        IndianArmy indianArmy26 = new IndianArmy();
        indianArmy26.setSoldierId(26);
        indianArmy26.setSoldierName("K. M. Cariappa");
        indianArmy26.setRank("Field Marshal");
        indianArmy26.setRegiment("Rajput Regiment");
        indianArmy26.setPostingArea("New Delhi");
        indianArmy26.setEnrolledOn("1919-12-01");
        indianArmy26.setMedals("Order of the British Empire");
        System.out.println("The Soldier ID is : " + indianArmy26.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy26.getSoldierName());
        System.out.println("The Rank is : " + indianArmy26.getRank());
        System.out.println("The Regiment is : " + indianArmy26.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy26.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy26.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy26.getMedals());

        IndianArmy indianArmy27 = new IndianArmy();
        indianArmy27.setSoldierId(27);
        indianArmy27.setSoldierName("Neelakantan Jayachandran Nair");
        indianArmy27.setRank("Colonel");
        indianArmy27.setRegiment("16 Maratha Light Infantry");
        indianArmy27.setPostingArea("Nagaland");
        indianArmy27.setEnrolledOn("1971-06-13");
        indianArmy27.setMedals("Ashoka Chakra, Kirti Chakra");
        System.out.println("The Soldier ID is : " + indianArmy27.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy27.getSoldierName());
        System.out.println("The Rank is : " + indianArmy27.getRank());
        System.out.println("The Regiment is : " + indianArmy27.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy27.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy27.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy27.getMedals());

        IndianArmy indianArmy28 = new IndianArmy();
        indianArmy28.setSoldierId(28);
        indianArmy28.setSoldierName("Mohit Sharma");
        indianArmy28.setRank("Major");
        indianArmy28.setRegiment("1 Para (SF)");
        indianArmy28.setPostingArea("Kupwara");
        indianArmy28.setEnrolledOn("1999-12-11");
        indianArmy28.setMedals("Ashoka Chakra, Sena Medal");
        System.out.println("The Soldier ID is : " + indianArmy28.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy28.getSoldierName());
        System.out.println("The Rank is : " + indianArmy28.getRank());
        System.out.println("The Regiment is : " + indianArmy28.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy28.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy28.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy28.getMedals());

        IndianArmy indianArmy29 = new IndianArmy();
        indianArmy29.setSoldierId(29);
        indianArmy29.setSoldierName("Tushar Mahajan");
        indianArmy29.setRank("Captain");
        indianArmy29.setRegiment("9 Para (SF)");
        indianArmy29.setPostingArea("Pampore");
        indianArmy29.setEnrolledOn("2010-06-12");
        indianArmy29.setMedals(" Shaurya Chakra");
        System.out.println("The Soldier ID is : " + indianArmy29.getSoldierId());
        System.out.println("The Soldier Name is : " + indianArmy29.getSoldierName());
        System.out.println("The Rank is : " + indianArmy29.getRank());
        System.out.println("The Regiment is : " + indianArmy29.getRegiment());
        System.out.println("The Posting Area is : " + indianArmy29.getPostingArea());
        System.out.println("The Enrolled On is : " + indianArmy29.getEnrolledOn());
        System.out.println("The Medals is : " + indianArmy29.getMedals());
    }
}