class MedicineExecutor {
    public static void main(String[] args) {

        Medicine medicine1 = new Medicine();
        medicine1.setMedicineId(1);
        medicine1.setMedicineName("Amoxicillin");
        medicine1.setDosage("500mg");
        medicine1.setManufacturer("Pfizer");
        medicine1.setExpiresOn("12/2025");
        medicine1.setSideEffects("Nausea, Rash");
        medicine1.setPrice("15.50");
        System.out.println("The Medicine ID is : " + medicine1.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine1.getMedicineName());
        System.out.println("The Dosage is : " + medicine1.getDosage());
        System.out.println("The Manufacturer is : " + medicine1.getManufacturer());
        System.out.println("The Expires On is : " + medicine1.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine1.getSideEffects());
        System.out.println("The Price is : " + medicine1.getPrice());

        Medicine medicine2 = new Medicine();
        medicine2.setMedicineId(2);
        medicine2.setMedicineName("Ibuprofen");
        medicine2.setDosage("200mg");
        medicine2.setManufacturer("Advil");
        medicine2.setExpiresOn("08/2026");
        medicine2.setSideEffects("Stomach ache");
        medicine2.setPrice("8.99");
        System.out.println("The Medicine ID is : " + medicine2.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine2.getMedicineName());
        System.out.println("The Dosage is : " + medicine2.getDosage());
        System.out.println("The Manufacturer is : " + medicine2.getManufacturer());
        System.out.println("The Expires On is : " + medicine2.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine2.getSideEffects());
        System.out.println("The Price is : " + medicine2.getPrice());

        Medicine medicine3 = new Medicine();
        medicine3.setMedicineId(3);
        medicine3.setMedicineName("Metformin");
        medicine3.setDosage("850mg");
        medicine3.setManufacturer("Bristol-Myers");
        medicine3.setExpiresOn("05/2025");
        medicine3.setSideEffects("Dizziness");
        medicine3.setPrice("12.00");
        System.out.println("The Medicine ID is : " + medicine3.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine3.getMedicineName());
        System.out.println("The Dosage is : " + medicine3.getDosage());
        System.out.println("The Manufacturer is : " + medicine3.getManufacturer());
        System.out.println("The Expires On is : " + medicine3.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine3.getSideEffects());
        System.out.println("The Price is : " + medicine3.getPrice());

        Medicine medicine4 = new Medicine();
        medicine4.setMedicineId(4);
        medicine4.setMedicineName("Atorvastatin");
        medicine4.setDosage("20mg");
        medicine4.setManufacturer("Viatris");
        medicine4.setExpiresOn("11/2026");
        medicine4.setSideEffects("Muscle pain");
        medicine4.setPrice("25.30");
        System.out.println("The Medicine ID is : " + medicine4.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine4.getMedicineName());
        System.out.println("The Dosage is : " + medicine4.getDosage());
        System.out.println("The Manufacturer is : " + medicine4.getManufacturer());
        System.out.println("The Expires On is : " + medicine4.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine4.getSideEffects());
        System.out.println("The Price is : " + medicine4.getPrice());

        Medicine medicine5 = new Medicine();
        medicine5.setMedicineId(5);
        medicine5.setMedicineName("Lisinopril");
        medicine5.setDosage("10mg");
        medicine5.setManufacturer("Lupin");
        medicine5.setExpiresOn("03/2027");
        medicine5.setSideEffects("Dry cough");
        medicine5.setPrice("10.25");
        System.out.println("The Medicine ID is : " + medicine5.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine5.getMedicineName());
        System.out.println("The Dosage is : " + medicine5.getDosage());
        System.out.println("The Manufacturer is : " + medicine5.getManufacturer());
        System.out.println("The Expires On is : " + medicine5.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine5.getSideEffects());
        System.out.println("The Price is : " + medicine5.getPrice());

        Medicine medicine6 = new Medicine();
        medicine6.setMedicineId(6);
        medicine6.setMedicineName("Omeprazole");
        medicine6.setDosage("40mg");
        medicine6.setManufacturer("AstraZeneca");
        medicine6.setExpiresOn("09/2025");
        medicine6.setSideEffects("Headache");
        medicine6.setPrice("18.75");
        System.out.println("The Medicine ID is : " + medicine6.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine6.getMedicineName());
        System.out.println("The Dosage is : " + medicine6.getDosage());
        System.out.println("The Manufacturer is : " + medicine6.getManufacturer());
        System.out.println("The Expires On is : " + medicine6.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine6.getSideEffects());
        System.out.println("The Price is : " + medicine6.getPrice());

        Medicine medicine7 = new Medicine();
        medicine7.setMedicineId(7);
        medicine7.setMedicineName("Levothyroxine");
        medicine7.setDosage("50mcg");
        medicine7.setManufacturer("AbbVie");
        medicine7.setExpiresOn("01/2026");
        medicine7.setSideEffects("Hair loss");
        medicine7.setPrice("22.10");
        System.out.println("The Medicine ID is : " + medicine7.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine7.getMedicineName());
        System.out.println("The Dosage is : " + medicine7.getDosage());
        System.out.println("The Manufacturer is : " + medicine7.getManufacturer());
        System.out.println("The Expires On is : " + medicine7.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine7.getSideEffects());
        System.out.println("The Price is : " + medicine7.getPrice());

        Medicine medicine8 = new Medicine();
        medicine8.setMedicineId(8);
        medicine8.setMedicineName("Amlodipine");
        medicine8.setDosage("5mg");
        medicine8.setManufacturer("Novartis");
        medicine8.setExpiresOn("06/2026");
        medicine8.setSideEffects("Swelling");
        medicine8.setPrice("9.45");
        System.out.println("The Medicine ID is : " + medicine8.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine8.getMedicineName());
        System.out.println("The Dosage is : " + medicine8.getDosage());
        System.out.println("The Manufacturer is : " + medicine8.getManufacturer());
        System.out.println("The Expires On is : " + medicine8.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine8.getSideEffects());
        System.out.println("The Price is : " + medicine8.getPrice());

        Medicine medicine9 = new Medicine();
        medicine9.setMedicineId(9);
        medicine9.setMedicineName("Gabapentin");
        medicine9.setDosage("300mg");
        medicine9.setManufacturer("Greenstone");
        medicine9.setExpiresOn("10/2025");
        medicine9.setSideEffects("Fatigue");
        medicine9.setPrice("31.00");
        System.out.println("The Medicine ID is : " + medicine9.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine9.getMedicineName());
        System.out.println("The Dosage is : " + medicine9.getDosage());
        System.out.println("The Manufacturer is : " + medicine9.getManufacturer());
        System.out.println("The Expires On is : " + medicine9.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine9.getSideEffects());
        System.out.println("The Price is : " + medicine9.getPrice());

        Medicine medicine10 = new Medicine();
        medicine10.setMedicineId(10);
        medicine10.setMedicineName("Albuterol");
        medicine10.setDosage("90mcg");
        medicine10.setManufacturer("GSK");
        medicine10.setExpiresOn("12/2026");
        medicine10.setSideEffects("Tremors");
        medicine10.setPrice("45.00");
        System.out.println("The Medicine ID is : " + medicine10.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine10.getMedicineName());
        System.out.println("The Dosage is : " + medicine10.getDosage());
        System.out.println("The Manufacturer is : " + medicine10.getManufacturer());
        System.out.println("The Expires On is : " + medicine10.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine10.getSideEffects());
        System.out.println("The Price is : " + medicine10.getPrice());

        Medicine medicine11 = new Medicine();
        medicine11.setMedicineId(11);
        medicine11.setMedicineName("Hydrochlorothiazide");
        medicine11.setDosage("25mg");
        medicine11.setManufacturer("Sandoz");
        medicine11.setExpiresOn("04/2026");
        medicine11.setSideEffects("Dehydration");
        medicine11.setPrice("7.20");
        System.out.println("The Medicine ID is : " + medicine11.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine11.getMedicineName());
        System.out.println("The Dosage is : " + medicine11.getDosage());
        System.out.println("The Manufacturer is : " + medicine11.getManufacturer());
        System.out.println("The Expires On is : " + medicine11.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine11.getSideEffects());
        System.out.println("The Price is : " + medicine11.getPrice());

        Medicine medicine12 = new Medicine();
        medicine12.setMedicineId(12);
        medicine12.setMedicineName("Sertraline");
        medicine12.setDosage("50mg");
        medicine12.setManufacturer("Zoloft Corp");
        medicine12.setExpiresOn("07/2025");
        medicine12.setSideEffects("Insomnia");
        medicine12.setPrice("19.99");
        System.out.println("The Medicine ID is : " + medicine12.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine12.getMedicineName());
        System.out.println("The Dosage is : " + medicine12.getDosage());
        System.out.println("The Manufacturer is : " + medicine12.getManufacturer());
        System.out.println("The Expires On is : " + medicine12.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine12.getSideEffects());
        System.out.println("The Price is : " + medicine12.getPrice());

        Medicine medicine13 = new Medicine();
        medicine13.setMedicineId(13);
        medicine13.setMedicineName("Losartan");
        medicine13.setDosage("50mg");
        medicine13.setManufacturer("Merck");
        medicine13.setExpiresOn("02/2027");
        medicine13.setSideEffects("Back pain");
        medicine13.setPrice("14.40");
        System.out.println("The Medicine ID is : " + medicine13.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine13.getMedicineName());
        System.out.println("The Dosage is : " + medicine13.getDosage());
        System.out.println("The Manufacturer is : " + medicine13.getManufacturer());
        System.out.println("The Expires On is : " + medicine13.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine13.getSideEffects());
        System.out.println("The Price is : " + medicine13.getPrice());

        Medicine medicine14 = new Medicine();
        medicine14.setMedicineId(14);
        medicine14.setMedicineName("Furosemide");
        medicine14.setDosage("40mg");
        medicine14.setManufacturer("Sanofi");
        medicine14.setExpiresOn("11/2025");
        medicine14.setSideEffects("Cramps");
        medicine14.setPrice("6.50");
        System.out.println("The Medicine ID is : " + medicine14.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine14.getMedicineName());
        System.out.println("The Dosage is : " + medicine14.getDosage());
        System.out.println("The Manufacturer is : " + medicine14.getManufacturer());
        System.out.println("The Expires On is : " + medicine14.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine14.getSideEffects());
        System.out.println("The Price is : " + medicine14.getPrice());

        Medicine medicine15 = new Medicine();
        medicine15.setMedicineId(15);
        medicine15.setMedicineName("Prednisone");
        medicine15.setDosage("10mg");
        medicine15.setManufacturer("Hikma");
        medicine15.setExpiresOn("08/2026");
        medicine15.setSideEffects("Weight gain");
        medicine15.setPrice("11.20");
        System.out.println("The Medicine ID is : " + medicine15.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine15.getMedicineName());
        System.out.println("The Dosage is : " + medicine15.getDosage());
        System.out.println("The Manufacturer is : " + medicine15.getManufacturer());
        System.out.println("The Expires On is : " + medicine15.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine15.getSideEffects());
        System.out.println("The Price is : " + medicine15.getPrice());

        Medicine medicine16 = new Medicine();
        medicine16.setMedicineId(16);
        medicine16.setMedicineName("Meloxicam");
        medicine16.setDosage("15mg");
        medicine16.setManufacturer("Boehringer");
        medicine16.setExpiresOn("04/2027");
        medicine16.setSideEffects("Heartburn");
        medicine16.setPrice("13.80");
        System.out.println("The Medicine ID is : " + medicine16.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine16.getMedicineName());
        System.out.println("The Dosage is : " + medicine16.getDosage());
        System.out.println("The Manufacturer is : " + medicine16.getManufacturer());
        System.out.println("The Expires On is : " + medicine16.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine16.getSideEffects());
        System.out.println("The Price is : " + medicine16.getPrice());

        Medicine medicine17 = new Medicine();
        medicine17.setMedicineId(17);
        medicine17.setMedicineName("Pantoprazole");
        medicine17.setDosage("40mg");
        medicine17.setManufacturer("Takeda");
        medicine17.setExpiresOn("10/2025");
        medicine17.setSideEffects("Joint pain");
        medicine17.setPrice("17.40");
        System.out.println("The Medicine ID is : " + medicine17.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine17.getMedicineName());
        System.out.println("The Dosage is : " + medicine17.getDosage());
        System.out.println("The Manufacturer is : " + medicine17.getManufacturer());
        System.out.println("The Expires On is : " + medicine17.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine17.getSideEffects());
        System.out.println("The Price is : " + medicine17.getPrice());

        Medicine medicine18 = new Medicine();
        medicine18.setMedicineId(18);
        medicine18.setMedicineName("Fluticasone");
        medicine18.setDosage("50mcg");
        medicine18.setManufacturer("GSK");
        medicine18.setExpiresOn("01/2026");
        medicine18.setSideEffects("Nosebleeds");
        medicine18.setPrice("28.90");
        System.out.println("The Medicine ID is : " + medicine18.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine18.getMedicineName());
        System.out.println("The Dosage is : " + medicine18.getDosage());
        System.out.println("The Manufacturer is : " + medicine18.getManufacturer());
        System.out.println("The Expires On is : " + medicine18.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine18.getSideEffects());
        System.out.println("The Price is : " + medicine18.getPrice());

        Medicine medicine19 = new Medicine();
        medicine19.setMedicineId(19);
        medicine19.setMedicineName("Tramadol");
        medicine19.setDosage("50mg");
        medicine19.setManufacturer("Janssen");
        medicine19.setExpiresOn("03/2027");
        medicine19.setSideEffects("Constipation");
        medicine19.setPrice("20.15");
        System.out.println("The Medicine ID is : " + medicine19.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine19.getMedicineName());
        System.out.println("The Dosage is : " + medicine19.getDosage());
        System.out.println("The Manufacturer is : " + medicine19.getManufacturer());
        System.out.println("The Expires On is : " + medicine19.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine19.getSideEffects());
        System.out.println("The Price is : " + medicine19.getPrice());

        Medicine medicine20 = new Medicine();
        medicine20.setMedicineId(20);
        medicine20.setMedicineName("Carvedilol");
        medicine20.setDosage("6.25mg");
        medicine20.setManufacturer("Roche");
        medicine20.setExpiresOn("06/2026");
        medicine20.setSideEffects("Dry eyes");
        medicine20.setPrice("13.20");
        System.out.println("The Medicine ID is : " + medicine20.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine20.getMedicineName());
        System.out.println("The Dosage is : " + medicine20.getDosage());
        System.out.println("The Manufacturer is : " + medicine20.getManufacturer());
        System.out.println("The Expires On is : " + medicine20.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine20.getSideEffects());
        System.out.println("The Price is : " + medicine20.getPrice());

        Medicine medicine21 = new Medicine();
        medicine21.setMedicineId(21);
        medicine21.setMedicineName("Clopidogrel");
        medicine21.setDosage("75mg");
        medicine21.setManufacturer("Bristol-Myers");
        medicine21.setExpiresOn("09/2025");
        medicine21.setSideEffects("Bruising");
        medicine21.setPrice("34.50");
        System.out.println("The Medicine ID is : " + medicine21.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine21.getMedicineName());
        System.out.println("The Dosage is : " + medicine21.getDosage());
        System.out.println("The Manufacturer is : " + medicine21.getManufacturer());
        System.out.println("The Expires On is : " + medicine21.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine21.getSideEffects());
        System.out.println("The Price is : " + medicine21.getPrice());

        Medicine medicine22 = new Medicine();
        medicine22.setMedicineId(22);
        medicine22.setMedicineName("Tamsulosin");
        medicine22.setDosage("0.4mg");
        medicine22.setManufacturer("Boehringer");
        medicine22.setExpiresOn("11/2026");
        medicine22.setSideEffects("Drowsiness");
        medicine22.setPrice("42.00");
        System.out.println("The Medicine ID is : " + medicine22.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine22.getMedicineName());
        System.out.println("The Dosage is : " + medicine22.getDosage());
        System.out.println("The Manufacturer is : " + medicine22.getManufacturer());
        System.out.println("The Expires On is : " + medicine22.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine22.getSideEffects());
        System.out.println("The Price is : " + medicine22.getPrice());

        Medicine medicine23 = new Medicine();
        medicine23.setMedicineId(23);
        medicine23.setMedicineName("Atenolol");
        medicine23.setDosage("50mg");
        medicine23.setManufacturer("AstraZeneca");
        medicine23.setExpiresOn("05/2026");
        medicine23.setSideEffects("Cold hands");
        medicine23.setPrice("8.15");
        System.out.println("The Medicine ID is : " + medicine23.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine23.getMedicineName());
        System.out.println("The Dosage is : " + medicine23.getDosage());
        System.out.println("The Manufacturer is : " + medicine23.getManufacturer());
        System.out.println("The Expires On is : " + medicine23.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine23.getSideEffects());
        System.out.println("The Price is : " + medicine23.getPrice());

        Medicine medicine24 = new Medicine();
        medicine24.setMedicineId(24);
        medicine24.setMedicineName("Citalopram");
        medicine24.setDosage("20mg");
        medicine24.setManufacturer("Lundbeck");
        medicine24.setExpiresOn("12/2025");
        medicine24.setSideEffects("Sweating");
        medicine24.setPrice("16.80");
        System.out.println("The Medicine ID is : " + medicine24.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine24.getMedicineName());
        System.out.println("The Dosage is : " + medicine24.getDosage());
        System.out.println("The Manufacturer is : " + medicine24.getManufacturer());
        System.out.println("The Expires On is : " + medicine24.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine24.getSideEffects());
        System.out.println("The Price is : " + medicine24.getPrice());

        Medicine medicine25 = new Medicine();
        medicine25.setMedicineId(25);
        medicine25.setMedicineName("Duloxetine");
        medicine25.setDosage("30mg");
        medicine25.setManufacturer("Eli Lilly");
        medicine25.setExpiresOn("08/2027");
        medicine25.setSideEffects("Dry mouth");
        medicine25.setPrice("27.25");
        System.out.println("The Medicine ID is : " + medicine25.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine25.getMedicineName());
        System.out.println("The Dosage is : " + medicine25.getDosage());
        System.out.println("The Manufacturer is : " + medicine25.getManufacturer());
        System.out.println("The Expires On is : " + medicine25.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine25.getSideEffects());
        System.out.println("The Price is : " + medicine25.getPrice());

        Medicine medicine26 = new Medicine();
        medicine26.setMedicineId(26);
        medicine26.setMedicineName("Rosuvastatin");
        medicine26.setDosage("10mg");
        medicine26.setManufacturer("Crestor Co");
        medicine26.setExpiresOn("02/2026");
        medicine26.setSideEffects("Weakness");
        medicine26.setPrice("21.90");
        System.out.println("The Medicine ID is : " + medicine26.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine26.getMedicineName());
        System.out.println("The Dosage is : " + medicine26.getDosage());
        System.out.println("The Manufacturer is : " + medicine26.getManufacturer());
        System.out.println("The Expires On is : " + medicine26.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine26.getSideEffects());
        System.out.println("The Price is : " + medicine26.getPrice());

        Medicine medicine27 = new Medicine();
        medicine27.setMedicineId(27);
        medicine27.setMedicineName("Venlafaxine");
        medicine27.setDosage("75mg");
        medicine27.setManufacturer("Wyeth");
        medicine27.setExpiresOn("04/2026");
        medicine27.setSideEffects("Vivid dreams");
        medicine27.setPrice("23.00");
        System.out.println("The Medicine ID is : " + medicine27.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine27.getMedicineName());
        System.out.println("The Dosage is : " + medicine27.getDosage());
        System.out.println("The Manufacturer is : " + medicine27.getManufacturer());
        System.out.println("The Expires On is : " + medicine27.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine27.getSideEffects());
        System.out.println("The Price is : " + medicine27.getPrice());

        Medicine medicine28 = new Medicine();
        medicine28.setMedicineId(28);
        medicine28.setMedicineName("Ranitidine");
        medicine28.setDosage("150mg");
        medicine28.setManufacturer("Glaxo");
        medicine28.setExpiresOn("10/2025");
        medicine28.setSideEffects("Headache");
        medicine28.setPrice("5.75");
        System.out.println("The Medicine ID is : " + medicine28.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine28.getMedicineName());
        System.out.println("The Dosage is : " + medicine28.getDosage());
        System.out.println("The Manufacturer is : " + medicine28.getManufacturer());
        System.out.println("The Expires On is : " + medicine28.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine28.getSideEffects());
        System.out.println("The Price is : " + medicine28.getPrice());

        Medicine medicine29 = new Medicine();
        medicine29.setMedicineId(29);
        medicine29.setMedicineName("Spironolactone");
        medicine29.setDosage("25mg");
        medicine29.setManufacturer("Pfizer");
        medicine29.setExpiresOn("07/2026");
        medicine29.setSideEffects("Dizziness");
        medicine29.setPrice("14.20");
        System.out.println("The Medicine ID is : " + medicine29.getMedicineId());
        System.out.println("The Medicine Name is : " + medicine29.getMedicineName());
        System.out.println("The Dosage is : " + medicine29.getDosage());
        System.out.println("The Manufacturer is : " + medicine29.getManufacturer());
        System.out.println("The Expires On is : " + medicine29.getExpiresOn());
        System.out.println("The Side Effects is : " + medicine29.getSideEffects());
        System.out.println("The Price is : " + medicine29.getPrice());

    }
}