class NutritionTableExecutor {
    public static void main(String[] args) {

        NutritionTable nutritionTable1 = new NutritionTable();
        nutritionTable1.setNutritionId(1);
        nutritionTable1.setFoodName("Apple");
        nutritionTable1.setCalories("95");
        nutritionTable1.setProtein("0.5g");
        nutritionTable1.setCarbohydrates("25g");
        nutritionTable1.setFat("0.3g");
        nutritionTable1.setVitamins("Vitamin C, Potassium");
        System.out.println("The Nutrition ID is : " + nutritionTable1.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable1.getFoodName());
        System.out.println("The Calories is : " + nutritionTable1.getCalories());
        System.out.println("The Protein is : " + nutritionTable1.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable1.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable1.getFat());
        System.out.println("The Vitamins is : " + nutritionTable1.getVitamins());

        NutritionTable nutritionTable2 = new NutritionTable();
        nutritionTable2.setNutritionId(2);
        nutritionTable2.setFoodName("Chicken Breast");
        nutritionTable2.setCalories("165");
        nutritionTable2.setProtein("31g");
        nutritionTable2.setCarbohydrates("0g");
        nutritionTable2.setFat("3.6g");
        nutritionTable2.setVitamins("Vitamin B6, Niacin");
        System.out.println("The Nutrition ID is : " + nutritionTable2.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable2.getFoodName());
        System.out.println("The Calories is : " + nutritionTable2.getCalories());
        System.out.println("The Protein is : " + nutritionTable2.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable2.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable2.getFat());
        System.out.println("The Vitamins is : " + nutritionTable2.getVitamins());

        NutritionTable nutritionTable3 = new NutritionTable();
        nutritionTable3.setNutritionId(3);
        nutritionTable3.setFoodName("Broccoli");
        nutritionTable3.setCalories("31");
        nutritionTable3.setProtein("2.5g");
        nutritionTable3.setCarbohydrates("6g");
        nutritionTable3.setFat("0.4g");
        nutritionTable3.setVitamins("Vitamin K, Vitamin C");
        System.out.println("The Nutrition ID is : " + nutritionTable3.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable3.getFoodName());
        System.out.println("The Calories is : " + nutritionTable3.getCalories());
        System.out.println("The Protein is : " + nutritionTable3.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable3.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable3.getFat());
        System.out.println("The Vitamins is : " + nutritionTable3.getVitamins());

        NutritionTable nutritionTable4 = new NutritionTable();
        nutritionTable4.setNutritionId(4);
        nutritionTable4.setFoodName("Almonds");
        nutritionTable4.setCalories("579");
        nutritionTable4.setProtein("21g");
        nutritionTable4.setCarbohydrates("22g");
        nutritionTable4.setFat("50g");
        nutritionTable4.setVitamins("Vitamin E, Magnesium");
        System.out.println("The Nutrition ID is : " + nutritionTable4.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable4.getFoodName());
        System.out.println("The Calories is : " + nutritionTable4.getCalories());
        System.out.println("The Protein is : " + nutritionTable4.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable4.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable4.getFat());
        System.out.println("The Vitamins is : " + nutritionTable4.getVitamins());

        NutritionTable nutritionTable5 = new NutritionTable();
        nutritionTable5.setNutritionId(5);
        nutritionTable5.setFoodName("Salmon");
        nutritionTable5.setCalories("208");
        nutritionTable5.setProtein("20g");
        nutritionTable5.setCarbohydrates("0g");
        nutritionTable5.setFat("13g");
        nutritionTable5.setVitamins("Vitamin B12, Vitamin D");
        System.out.println("The Nutrition ID is : " + nutritionTable5.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable5.getFoodName());
        System.out.println("The Calories is : " + nutritionTable5.getCalories());
        System.out.println("The Protein is : " + nutritionTable5.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable5.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable5.getFat());
        System.out.println("The Vitamins is : " + nutritionTable5.getVitamins());

        NutritionTable nutritionTable6 = new NutritionTable();
        nutritionTable6.setNutritionId(6);
        nutritionTable6.setFoodName("Brown Rice");
        nutritionTable6.setCalories("111");
        nutritionTable6.setProtein("2.6g");
        nutritionTable6.setCarbohydrates("23g");
        nutritionTable6.setFat("0.9g");
        nutritionTable6.setVitamins("B1, B3, B6");
        System.out.println("The Nutrition ID is : " + nutritionTable6.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable6.getFoodName());
        System.out.println("The Calories is : " + nutritionTable6.getCalories());
        System.out.println("The Protein is : " + nutritionTable6.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable6.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable6.getFat());
        System.out.println("The Vitamins is : " + nutritionTable6.getVitamins());

        NutritionTable nutritionTable7 = new NutritionTable();
        nutritionTable7.setNutritionId(7);
        nutritionTable7.setFoodName("Egg");
        nutritionTable7.setCalories("155");
        nutritionTable7.setProtein("13g");
        nutritionTable7.setCarbohydrates("1.1g");
        nutritionTable7.setFat("11g");
        nutritionTable7.setVitamins("Vitamin D, B2");
        System.out.println("The Nutrition ID is : " + nutritionTable7.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable7.getFoodName());
        System.out.println("The Calories is : " + nutritionTable7.getCalories());
        System.out.println("The Protein is : " + nutritionTable7.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable7.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable7.getFat());
        System.out.println("The Vitamins is : " + nutritionTable7.getVitamins());

        NutritionTable nutritionTable8 = new NutritionTable();
        nutritionTable8.setNutritionId(8);
        nutritionTable8.setFoodName("Banana");
        nutritionTable8.setCalories("89");
        nutritionTable8.setProtein("1.1g");
        nutritionTable8.setCarbohydrates("23g");
        nutritionTable8.setFat("0.3g");
        nutritionTable8.setVitamins("Vitamin B6, C");
        System.out.println("The Nutrition ID is : " + nutritionTable8.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable8.getFoodName());
        System.out.println("The Calories is : " + nutritionTable8.getCalories());
        System.out.println("The Protein is : " + nutritionTable8.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable8.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable8.getFat());
        System.out.println("The Vitamins is : " + nutritionTable8.getVitamins());

        NutritionTable nutritionTable9 = new NutritionTable();
        nutritionTable9.setNutritionId(9);
        nutritionTable9.setFoodName("Spinach");
        nutritionTable9.setCalories("23");
        nutritionTable9.setProtein("2.9g");
        nutritionTable9.setCarbohydrates("3.6g");
        nutritionTable9.setFat("0.4g");
        nutritionTable9.setVitamins("Vitamin A, K1");
        System.out.println("The Nutrition ID is : " + nutritionTable9.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable9.getFoodName());
        System.out.println("The Calories is : " + nutritionTable9.getCalories());
        System.out.println("The Protein is : " + nutritionTable9.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable9.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable9.getFat());
        System.out.println("The Vitamins is : " + nutritionTable9.getVitamins());

        NutritionTable nutritionTable10 = new NutritionTable();
        nutritionTable10.setNutritionId(10);
        nutritionTable10.setFoodName("Sweet Potato");
        nutritionTable10.setCalories("86");
        nutritionTable10.setProtein("1.6g");
        nutritionTable10.setCarbohydrates("20g");
        nutritionTable10.setFat("0.1g");
        nutritionTable10.setVitamins("Vitamin A, B5");
        System.out.println("The Nutrition ID is : " + nutritionTable10.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable10.getFoodName());
        System.out.println("The Calories is : " + nutritionTable10.getCalories());
        System.out.println("The Protein is : " + nutritionTable10.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable10.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable10.getFat());
        System.out.println("The Vitamins is : " + nutritionTable10.getVitamins());

        NutritionTable nutritionTable11 = new NutritionTable();
        nutritionTable11.setNutritionId(11);
        nutritionTable11.setFoodName("Greek Yogurt");
        nutritionTable11.setCalories("59");
        nutritionTable11.setProtein("10g");
        nutritionTable11.setCarbohydrates("3.6g");
        nutritionTable11.setFat("0.4g");
        nutritionTable11.setVitamins("B12, Calcium");
        System.out.println("The Nutrition ID is : " + nutritionTable11.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable11.getFoodName());
        System.out.println("The Calories is : " + nutritionTable11.getCalories());
        System.out.println("The Protein is : " + nutritionTable11.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable11.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable11.getFat());
        System.out.println("The Vitamins is : " + nutritionTable11.getVitamins());

        NutritionTable nutritionTable12 = new NutritionTable();
        nutritionTable12.setNutritionId(12);
        nutritionTable12.setFoodName("Oats");
        nutritionTable12.setCalories("389");
        nutritionTable12.setProtein("16.9g");
        nutritionTable12.setCarbohydrates("66g");
        nutritionTable12.setFat("6.9g");
        nutritionTable12.setVitamins("B1, Manganese");
        System.out.println("The Nutrition ID is : " + nutritionTable12.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable12.getFoodName());
        System.out.println("The Calories is : " + nutritionTable12.getCalories());
        System.out.println("The Protein is : " + nutritionTable12.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable12.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable12.getFat());
        System.out.println("The Vitamins is : " + nutritionTable12.getVitamins());

        NutritionTable nutritionTable13 = new NutritionTable();
        nutritionTable13.setNutritionId(13);
        nutritionTable13.setFoodName("Blueberries");
        nutritionTable13.setCalories("57");
        nutritionTable13.setProtein("0.7g");
        nutritionTable13.setCarbohydrates("14g");
        nutritionTable13.setFat("0.3g");
        nutritionTable13.setVitamins("Vitamin K, C");
        System.out.println("The Nutrition ID is : " + nutritionTable13.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable13.getFoodName());
        System.out.println("The Calories is : " + nutritionTable13.getCalories());
        System.out.println("The Protein is : " + nutritionTable13.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable13.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable13.getFat());
        System.out.println("The Vitamins is : " + nutritionTable13.getVitamins());

        NutritionTable nutritionTable14 = new NutritionTable();
        nutritionTable14.setNutritionId(14);
        nutritionTable14.setFoodName("Walnuts");
        nutritionTable14.setCalories("654");
        nutritionTable14.setProtein("15g");
        nutritionTable14.setCarbohydrates("14g");
        nutritionTable14.setFat("65g");
        nutritionTable14.setVitamins("Vitamin B6, Folate");
        System.out.println("The Nutrition ID is : " + nutritionTable14.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable14.getFoodName());
        System.out.println("The Calories is : " + nutritionTable14.getCalories());
        System.out.println("The Protein is : " + nutritionTable14.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable14.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable14.getFat());
        System.out.println("The Vitamins is : " + nutritionTable14.getVitamins());

        NutritionTable nutritionTable15 = new NutritionTable();
        nutritionTable15.setNutritionId(15);
        nutritionTable15.setFoodName("Beef (Lean)");
        nutritionTable15.setCalories("250");
        nutritionTable15.setProtein("26g");
        nutritionTable15.setCarbohydrates("0g");
        nutritionTable15.setFat("15g");
        nutritionTable15.setVitamins("Vitamin B12, Zinc");
        System.out.println("The Nutrition ID is : " + nutritionTable15.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable15.getFoodName());
        System.out.println("The Calories is : " + nutritionTable15.getCalories());
        System.out.println("The Protein is : " + nutritionTable15.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable15.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable15.getFat());
        System.out.println("The Vitamins is : " + nutritionTable15.getVitamins());

        NutritionTable nutritionTable16 = new NutritionTable();
        nutritionTable16.setNutritionId(16);
        nutritionTable16.setFoodName("Avocado");
        nutritionTable16.setCalories("160");
        nutritionTable16.setProtein("2g");
        nutritionTable16.setCarbohydrates("9g");
        nutritionTable16.setFat("15g");
        nutritionTable16.setVitamins("Vitamin K, E");
        System.out.println("The Nutrition ID is : " + nutritionTable16.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable16.getFoodName());
        System.out.println("The Calories is : " + nutritionTable16.getCalories());
        System.out.println("The Protein is : " + nutritionTable16.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable16.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable16.getFat());
        System.out.println("The Vitamins is : " + nutritionTable16.getVitamins());

        NutritionTable nutritionTable17 = new NutritionTable();
        nutritionTable17.setNutritionId(17);
        nutritionTable17.setFoodName("Quinoa");
        nutritionTable17.setCalories("120");
        nutritionTable17.setProtein("4.4g");
        nutritionTable17.setCarbohydrates("21g");
        nutritionTable17.setFat("1.9g");
        nutritionTable17.setVitamins("B-Vitamins, Magnesium");
        System.out.println("The Nutrition ID is : " + nutritionTable17.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable17.getFoodName());
        System.out.println("The Calories is : " + nutritionTable17.getCalories());
        System.out.println("The Protein is : " + nutritionTable17.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable17.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable17.getFat());
        System.out.println("The Vitamins is : " + nutritionTable17.getVitamins());

        NutritionTable nutritionTable18 = new NutritionTable();
        nutritionTable18.setNutritionId(18);
        nutritionTable18.setFoodName("Lentils");
        nutritionTable18.setCalories("116");
        nutritionTable18.setProtein("9g");
        nutritionTable18.setCarbohydrates("20g");
        nutritionTable18.setFat("0.4g");
        nutritionTable18.setVitamins("Folate, Thiamin");
        System.out.println("The Nutrition ID is : " + nutritionTable18.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable18.getFoodName());
        System.out.println("The Calories is : " + nutritionTable18.getCalories());
        System.out.println("The Protein is : " + nutritionTable18.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable18.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable18.getFat());
        System.out.println("The Vitamins is : " + nutritionTable18.getVitamins());

        NutritionTable nutritionTable19 = new NutritionTable();
        nutritionTable19.setNutritionId(19);
        nutritionTable19.setFoodName("Peanut Butter");
        nutritionTable19.setCalories("588");
        nutritionTable19.setProtein("25g");
        nutritionTable19.setCarbohydrates("20g");
        nutritionTable19.setFat("50g");
        nutritionTable19.setVitamins("Vitamin E, B3");
        System.out.println("The Nutrition ID is : " + nutritionTable19.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable19.getFoodName());
        System.out.println("The Calories is : " + nutritionTable19.getCalories());
        System.out.println("The Protein is : " + nutritionTable19.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable19.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable19.getFat());
        System.out.println("The Vitamins is : " + nutritionTable19.getVitamins());

        NutritionTable nutritionTable20 = new NutritionTable();
        nutritionTable20.setNutritionId(20);
        nutritionTable20.setFoodName("Milk (Whole)");
        nutritionTable20.setCalories("61");
        nutritionTable20.setProtein("3.2g");
        nutritionTable20.setCarbohydrates("4.8g");
        nutritionTable20.setFat("3.3g");
        nutritionTable20.setVitamins("Vitamin D, B12");
        System.out.println("The Nutrition ID is : " + nutritionTable20.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable20.getFoodName());
        System.out.println("The Calories is : " + nutritionTable20.getCalories());
        System.out.println("The Protein is : " + nutritionTable20.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable20.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable20.getFat());
        System.out.println("The Vitamins is : " + nutritionTable20.getVitamins());

        NutritionTable nutritionTable21 = new NutritionTable();
        nutritionTable21.setNutritionId(21);
        nutritionTable21.setFoodName("Tuna");
        nutritionTable21.setCalories("132");
        nutritionTable21.setProtein("28g");
        nutritionTable21.setCarbohydrates("0g");
        nutritionTable21.setFat("1.3g");
        nutritionTable21.setVitamins("Vitamin D, B6");
        System.out.println("The Nutrition ID is : " + nutritionTable21.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable21.getFoodName());
        System.out.println("The Calories is : " + nutritionTable21.getCalories());
        System.out.println("The Protein is : " + nutritionTable21.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable21.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable21.getFat());
        System.out.println("The Vitamins is : " + nutritionTable21.getVitamins());

        NutritionTable nutritionTable22 = new NutritionTable();
        nutritionTable22.setNutritionId(22);
        nutritionTable22.setFoodName("Carrot");
        nutritionTable22.setCalories("41");
        nutritionTable22.setProtein("0.9g");
        nutritionTable22.setCarbohydrates("10g");
        nutritionTable22.setFat("0.2g");
        nutritionTable22.setVitamins("Vitamin A, K1");
        System.out.println("The Nutrition ID is : " + nutritionTable22.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable22.getFoodName());
        System.out.println("The Calories is : " + nutritionTable22.getCalories());
        System.out.println("The Protein is : " + nutritionTable22.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable22.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable22.getFat());
        System.out.println("The Vitamins is : " + nutritionTable22.getVitamins());

        NutritionTable nutritionTable23 = new NutritionTable();
        nutritionTable23.setNutritionId(23);
        nutritionTable23.setFoodName("Garlic");
        nutritionTable23.setCalories("149");
        nutritionTable23.setProtein("6.4g");
        nutritionTable23.setCarbohydrates("33g");
        nutritionTable23.setFat("0.5g");
        nutritionTable23.setVitamins("Vitamin C, B6");
        System.out.println("The Nutrition ID is : " + nutritionTable23.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable23.getFoodName());
        System.out.println("The Calories is : " + nutritionTable23.getCalories());
        System.out.println("The Protein is : " + nutritionTable23.getProtein());
        System.out.println("The Carbohydrates is : " + nutritionTable23.getCarbohydrates());
        System.out.println("The Fat is : " + nutritionTable23.getFat());
        System.out.println("The Vitamins is : " + nutritionTable23.getVitamins());

        NutritionTable nutritionTable24 = new NutritionTable();
        nutritionTable24.setNutritionId(24);
        nutritionTable24.setFoodName("Orange");
        nutritionTable24.setCalories("47");
        nutritionTable24.setProtein("0.9g");
        nutritionTable24.setCarbohydrates("12g");
        nutritionTable24.setFat("0.1g");
        nutritionTable24.setVitamins("Vitamin C, Folate");
        System.out.println("The Nutrition ID is : " + nutritionTable24.getNutritionId());
        System.out.println("The Food Name is : " + nutritionTable24.getFoodName());
        System.out.println("The Calories is : " + nutritionTable24.get