class PhoneSettingsExecutor {
    public static void main(String[] args) {

        PhoneSettings phoneSettings1 = new PhoneSettings();
        phoneSettings1.setSettingId(1);
        phoneSettings1.setPhoneName("iPhone 13 Pro");
        phoneSettings1.setOsVersion("iOS 15.4");
        phoneSettings1.setBrightness("85%");
        phoneSettings1.setWifiStatus("Connected to Home_5G");
        phoneSettings1.setStorageUsed("128GB of 256GB");
        phoneSettings1.setBatteryLevel("92%");
        System.out.println("The Setting ID is : " + phoneSettings1.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings1.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings1.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings1.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings1.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings1.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings1.getBatteryLevel());

        PhoneSettings phoneSettings2 = new PhoneSettings();
        phoneSettings2.setSettingId(2);
        phoneSettings2.setPhoneName("Samsung Galaxy S22");
        phoneSettings2.setOsVersion("Android 12");
        phoneSettings2.setBrightness("70%");
        phoneSettings2.setWifiStatus("Connected to Office_Wifi");
        phoneSettings2.setStorageUsed("60GB of 128GB");
        phoneSettings2.setBatteryLevel("45%");
        System.out.println("The Setting ID is : " + phoneSettings2.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings2.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings2.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings2.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings2.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings2.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings2.getBatteryLevel());

        PhoneSettings phoneSettings3 = new PhoneSettings();
        phoneSettings3.setSettingId(3);
        phoneSettings3.setPhoneName("Google Pixel 6");
        phoneSettings3.setOsVersion("Android 13 Beta");
        phoneSettings3.setBrightness("Auto-Brightness On");
        phoneSettings3.setWifiStatus("Searching...");
        phoneSettings3.setStorageUsed("45GB of 128GB");
        phoneSettings3.setBatteryLevel("100%");
        System.out.println("The Setting ID is : " + phoneSettings3.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings3.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings3.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings3.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings3.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings3.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings3.getBatteryLevel());

        PhoneSettings phoneSettings4 = new PhoneSettings();
        phoneSettings4.setSettingId(4);
        phoneSettings4.setPhoneName("OnePlus 10 Pro");
        phoneSettings4.setOsVersion("OxygenOS 12");
        phoneSettings4.setBrightness("50%");
        phoneSettings4.setWifiStatus("Connected to Starbucks_Free");
        phoneSettings4.setStorageUsed("100GB of 256GB");
        phoneSettings4.setBatteryLevel("88%");
        System.out.println("The Setting ID is : " + phoneSettings4.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings4.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings4.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings4.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings4.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings4.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings4.getBatteryLevel());

        PhoneSettings phoneSettings5 = new PhoneSettings();
        phoneSettings5.setSettingId(5);
        phoneSettings5.setPhoneName("Xiaomi Mi 11");
        phoneSettings5.setOsVersion("MIUI 13");
        phoneSettings5.setBrightness("100%");
        phoneSettings5.setWifiStatus("Disconnected");
        phoneSettings5.setStorageUsed("200GB of 512GB");
        phoneSettings5.setBatteryLevel("15%");
        System.out.println("The Setting ID is : " + phoneSettings5.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings5.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings5.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings5.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings5.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings5.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings5.getBatteryLevel());

        PhoneSettings phoneSettings6 = new PhoneSettings();
        phoneSettings6.setSettingId(6);
        phoneSettings6.setPhoneName("Sony Xperia 1 III");
        phoneSettings6.setOsVersion("Android 11");
        phoneSettings6.setBrightness("65%");
        phoneSettings6.setWifiStatus("Connected to Sony_Network");
        phoneSettings6.setStorageUsed("30GB of 256GB");
        phoneSettings6.setBatteryLevel("76%");
        System.out.println("The Setting ID is : " + phoneSettings6.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings6.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings6.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings6.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings6.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings6.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings6.getBatteryLevel());

        PhoneSettings phoneSettings7 = new PhoneSettings();
        phoneSettings7.setSettingId(7);
        phoneSettings7.setPhoneName("Huawei P50 Pro");
        phoneSettings7.setOsVersion("HarmonyOS 2.0");
        phoneSettings7.setBrightness("40%");
        phoneSettings7.setWifiStatus("Connected to Huawei_Router");
        phoneSettings7.setStorageUsed("80GB of 256GB");
        phoneSettings7.setBatteryLevel("55%");
        System.out.println("The Setting ID is : " + phoneSettings7.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings7.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings7.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings7.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings7.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings7.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings7.getBatteryLevel());

        PhoneSettings phoneSettings8 = new PhoneSettings();
        phoneSettings8.setSettingId(8);
        phoneSettings8.setPhoneName("Oppo Find X5");
        phoneSettings8.setOsVersion("ColorOS 12.1");
        phoneSettings8.setBrightness("20%");
        phoneSettings8.setWifiStatus("Connected to Airport_Guest");
        phoneSettings8.setStorageUsed("55GB of 128GB");
        phoneSettings8.setBatteryLevel("32%");
        System.out.println("The Setting ID is : " + phoneSettings8.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings8.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings8.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings8.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings8.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings8.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings8.getBatteryLevel());

        PhoneSettings phoneSettings9 = new PhoneSettings();
        phoneSettings9.setSettingId(9);
        phoneSettings9.setPhoneName("Asus ROG Phone 5");
        phoneSettings9.setOsVersion("Android 11");
        phoneSettings9.setBrightness("90%");
        phoneSettings9.setWifiStatus("Connected to Gaming_Hub");
        phoneSettings9.setStorageUsed("400GB of 512GB");
        phoneSettings9.setBatteryLevel("67%");
        System.out.println("The Setting ID is : " + phoneSettings9.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings9.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings9.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings9.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings9.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings9.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings9.getBatteryLevel());

        PhoneSettings phoneSettings10 = new PhoneSettings();
        phoneSettings10.setSettingId(10);
        phoneSettings10.setPhoneName("Nokia G50");
        phoneSettings10.setOsVersion("Android 11");
        phoneSettings10.setBrightness("35%");
        phoneSettings10.setWifiStatus("Disconnected");
        phoneSettings10.setStorageUsed("10GB of 64GB");
        phoneSettings10.setBatteryLevel("12%");
        System.out.println("The Setting ID is : " + phoneSettings10.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings10.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings10.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings10.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings10.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings10.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings10.getBatteryLevel());

        PhoneSettings phoneSettings11 = new PhoneSettings();
        phoneSettings11.setSettingId(11);
        phoneSettings11.setPhoneName("Motorola Edge 30");
        phoneSettings11.setOsVersion("Android 12");
        phoneSettings11.setBrightness("75%");
        phoneSettings11.setWifiStatus("Connected to Moto_Net");
        phoneSettings11.setStorageUsed("44GB of 256GB");
        phoneSettings11.setBatteryLevel("81%");
        System.out.println("The Setting ID is : " + phoneSettings11.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings11.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings11.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings11.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings11.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings11.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings11.getBatteryLevel());

        PhoneSettings phoneSettings12 = new PhoneSettings();
        phoneSettings12.setSettingId(12);
        phoneSettings12.setPhoneName("Realme GT 2 Pro");
        phoneSettings12.setOsVersion("Realme UI 3.0");
        phoneSettings12.setBrightness("60%");
        phoneSettings12.setWifiStatus("Connected to Campus_Wifi");
        phoneSettings12.setStorageUsed("95GB of 256GB");
        phoneSettings12.setBatteryLevel("49%");
        System.out.println("The Setting ID is : " + phoneSettings12.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings12.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings12.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings12.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings12.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings12.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings12.getBatteryLevel());

        PhoneSettings phoneSettings13 = new PhoneSettings();
        phoneSettings13.setSettingId(13);
        phoneSettings13.setPhoneName("Vivo X80 Pro");
        phoneSettings13.setOsVersion("Funtouch OS 12");
        phoneSettings13.setBrightness("55%");
        phoneSettings13.setWifiStatus("Connected to Vivo_Connect");
        phoneSettings13.setStorageUsed("68GB of 128GB");
        phoneSettings13.setBatteryLevel("73%");
        System.out.println("The Setting ID is : " + phoneSettings13.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings13.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings13.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings13.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings13.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings13.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings13.getBatteryLevel());

        PhoneSettings phoneSettings14 = new PhoneSettings();
        phoneSettings14.setSettingId(14);
        phoneSettings14.setPhoneName("iPhone SE (2022)");
        phoneSettings14.setOsVersion("iOS 15.4");
        phoneSettings14.setBrightness("45%");
        phoneSettings14.setWifiStatus("Connected to Library_Public");
        phoneSettings14.setStorageUsed("22GB of 64GB");
        phoneSettings14.setBatteryLevel("28%");
        System.out.println("The Setting ID is : " + phoneSettings14.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings14.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings14.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings14.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings14.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings14.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings14.getBatteryLevel());

        PhoneSettings phoneSettings15 = new PhoneSettings();
        phoneSettings15.setSettingId(15);
        phoneSettings15.setPhoneName("Samsung Galaxy A53");
        phoneSettings15.setOsVersion("Android 12");
        phoneSettings15.setBrightness("80%");
        phoneSettings15.setWifiStatus("Connected to Home_Kitchen");
        phoneSettings15.setStorageUsed("50GB of 128GB");
        phoneSettings15.setBatteryLevel("95%");
        System.out.println("The Setting ID is : " + phoneSettings15.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings15.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings15.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings15.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings15.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings15.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings15.getBatteryLevel());

        PhoneSettings phoneSettings16 = new PhoneSettings();
        phoneSettings16.setSettingId(16);
        phoneSettings16.setPhoneName("Google Pixel 5a");
        phoneSettings16.setOsVersion("Android 12");
        phoneSettings16.setBrightness("30%");
        phoneSettings16.setWifiStatus("Connected to Google_Guest");
        phoneSettings16.setStorageUsed("110GB of 128GB");
        phoneSettings16.setBatteryLevel("40%");
        System.out.println("The Setting ID is : " + phoneSettings16.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings16.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings16.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings16.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings16.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings16.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings16.getBatteryLevel());

        PhoneSettings phoneSettings17 = new PhoneSettings();
        phoneSettings17.setSettingId(17);
        phoneSettings17.setPhoneName("ZTE Axon 40 Ultra");
        phoneSettings17.setOsVersion("MyOS 12");
        phoneSettings17.setBrightness("100%");
        phoneSettings17.setWifiStatus("Connected to Ultra_Fiber");
        phoneSettings17.setStorageUsed("210GB of 256GB");
        phoneSettings17.setBatteryLevel("61%");
        System.out.println("The Setting ID is : " + phoneSettings17.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings17.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings17.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings17.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings17.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings17.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings17.getBatteryLevel());

        PhoneSettings phoneSettings18 = new PhoneSettings();
        phoneSettings18.setSettingId(18);
        phoneSettings18.setPhoneName("Honor Magic 4 Pro");
        phoneSettings18.setOsVersion("Magic UI 6.0");
        phoneSettings18.setBrightness("15%");
        phoneSettings18.setWifiStatus("Disconnected");
        phoneSettings18.setStorageUsed("15GB of 256GB");
        phoneSettings18.setBatteryLevel("9%");
        System.out.println("The Setting ID is : " + phoneSettings18.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings18.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings18.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings18.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings18.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings18.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings18.getBatteryLevel());

        PhoneSettings phoneSettings19 = new PhoneSettings();
        phoneSettings19.setSettingId(19);
        phoneSettings19.setPhoneName("iPhone 12 Mini");
        phoneSettings19.setOsVersion("iOS 15.1");
        phoneSettings19.setBrightness("50%");
        phoneSettings19.setWifiStatus("Connected to Mini_Network");
        phoneSettings19.setStorageUsed("58GB of 64GB");
        phoneSettings19.setBatteryLevel("52%");
        System.out.println("The Setting ID is : " + phoneSettings19.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings19.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings19.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings19.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings19.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings19.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings19.getBatteryLevel());

        PhoneSettings phoneSettings20 = new PhoneSettings();
        phoneSettings20.setSettingId(20);
        phoneSettings20.setPhoneName("Samsung Galaxy Z Flip 3");
        phoneSettings20.setOsVersion("Android 12");
        phoneSettings20.setBrightness("Adaptive");
        phoneSettings20.setWifiStatus("Connected to Flip_Net");
        phoneSettings20.setStorageUsed("120GB of 256GB");
        phoneSettings20.setBatteryLevel("38%");
        System.out.println("The Setting ID is : " + phoneSettings20.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings20.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings20.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings20.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings20.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings20.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings20.getBatteryLevel());

        PhoneSettings phoneSettings21 = new PhoneSettings();
        phoneSettings21.setSettingId(21);
        phoneSettings21.setPhoneName("Black Shark 5 Pro");
        phoneSettings21.setOsVersion("JoyUI 13");
        phoneSettings21.setBrightness("95%");
        phoneSettings21.setWifiStatus("Connected to Game_Router");
        phoneSettings21.setStorageUsed("310GB of 512GB");
        phoneSettings21.setBatteryLevel("84%");
        System.out.println("The Setting ID is : " + phoneSettings21.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings21.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings21.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings21.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings21.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings21.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings21.getBatteryLevel());

        PhoneSettings phoneSettings22 = new PhoneSettings();
        phoneSettings22.setSettingId(22);
        phoneSettings22.setPhoneName("Poco F4 GT");
        phoneSettings22.setOsVersion("MIUI 13");
        phoneSettings22.setBrightness("60%");
        phoneSettings22.setWifiStatus("Connected to Poco_WLAN");
        phoneSettings22.setStorageUsed("88GB of 256GB");
        phoneSettings22.setBatteryLevel("71%");
        System.out.println("The Setting ID is : " + phoneSettings22.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings22.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings22.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings22.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings22.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings22.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings22.getBatteryLevel());

        PhoneSettings phoneSettings23 = new PhoneSettings();
        phoneSettings23.setSettingId(23);
        phoneSettings23.setPhoneName("Fairphone 4");
        phoneSettings23.setOsVersion("Android 11");
        phoneSettings23.setBrightness("25%");
        phoneSettings23.setWifiStatus("Connected to Eco_Free");
        phoneSettings23.setStorageUsed("12GB of 128GB");
        phoneSettings23.setBatteryLevel("99%");
        System.out.println("The Setting ID is : " + phoneSettings23.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings23.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings23.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings23.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings23.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings23.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings23.getBatteryLevel());

        PhoneSettings phoneSettings24 = new PhoneSettings();
        phoneSettings24.setSettingId(24);
        phoneSettings24.setPhoneName("Sony Xperia 5 IV");
        phoneSettings24.setOsVersion("Android 12");
        phoneSettings24.setBrightness("50%");
        phoneSettings24.setWifiStatus("Disconnected");
        phoneSettings24.setStorageUsed("45GB of 128GB");
        phoneSettings24.setBatteryLevel("42%");
        System.out.println("The Setting ID is : " + phoneSettings24.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings24.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings24.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings24.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings24.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings24.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings24.getBatteryLevel());

        PhoneSettings phoneSettings25 = new PhoneSettings();
        phoneSettings25.setSettingId(25);
        phoneSettings25.setPhoneName("Meizu 18s");
        phoneSettings25.setOsVersion("Flyme 9.2");
        phoneSettings25.setBrightness("80%");
        phoneSettings25.setWifiStatus("Connected to Meizu_Cloud");
        phoneSettings25.setStorageUsed("60GB of 256GB");
        phoneSettings25.setBatteryLevel("19%");
        System.out.println("The Setting ID is : " + phoneSettings25.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings25.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings25.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings25.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings25.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings25.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings25.getBatteryLevel());

        PhoneSettings phoneSettings26 = new PhoneSettings();
        phoneSettings26.setSettingId(26);
        phoneSettings26.setPhoneName("Lenovo Legion Y90");
        phoneSettings26.setOsVersion("ZUI 13");
        phoneSettings26.setBrightness("100%");
        phoneSettings26.setWifiStatus("Connected to Legion_Net");
        phoneSettings26.setStorageUsed("400GB of 640GB");
        phoneSettings26.setBatteryLevel("57%");
        System.out.println("The Setting ID is : " + phoneSettings26.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings26.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings26.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings26.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings26.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings26.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings26.getBatteryLevel());

        PhoneSettings phoneSettings27 = new PhoneSettings();
        phoneSettings27.setSettingId(27);
        phoneSettings27.setPhoneName("Infinix Note 12");
        phoneSettings27.setOsVersion("XOS 10.6");
        phoneSettings27.setBrightness("40%");
        phoneSettings27.setWifiStatus("Connected to Infinix_Hotspot");
        phoneSettings27.setStorageUsed("25GB of 128GB");
        phoneSettings27.setBatteryLevel("78%");
        System.out.println("The Setting ID is : " + phoneSettings27.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings27.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings27.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings27.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings27.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings27.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings27.getBatteryLevel());

        PhoneSettings phoneSettings28 = new PhoneSettings();
        phoneSettings28.setSettingId(28);
        phoneSettings28.setPhoneName("Tecno Camon 19");
        phoneSettings28.setOsVersion("HiOS 8.6");
        phoneSettings28.setBrightness("65%");
        phoneSettings28.setWifiStatus("Connected to Tecno_WiFi");
        phoneSettings28.setStorageUsed("18GB of 128GB");
        phoneSettings28.setBatteryLevel("91%");
        System.out.println("The Setting ID is : " + phoneSettings28.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings28.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings28.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings28.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings28.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings28.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings28.getBatteryLevel());

        PhoneSettings phoneSettings29 = new PhoneSettings();
        phoneSettings29.setSettingId(29);
        phoneSettings29.setPhoneName("ZTE Nubia Red Magic 7");
        phoneSettings29.setOsVersion("RedMagic OS 5.0");
        phoneSettings29.setBrightness("Max");
        phoneSettings29.setWifiStatus("Connected to Red_Magic_Hub");
        phoneSettings29.setStorageUsed("150GB of 256GB");
        phoneSettings29.setBatteryLevel("24%");
        System.out.println("The Setting ID is : " + phoneSettings29.getSettingId());
        System.out.println("The Phone Name is : " + phoneSettings29.getPhoneName());
        System.out.println("The OS Version is : " + phoneSettings29.getOsVersion());
        System.out.println("The Brightness is : " + phoneSettings29.getBrightness());
        System.out.println("The WiFi Status is : " + phoneSettings29.getWifiStatus());
        System.out.println("The Storage Used is : " + phoneSettings29.getStorageUsed());
        System.out.println("The Battery Level is : " + phoneSettings29.getBatteryLevel());
    }
}