class PlayGroundExecutor {
    public static void main(String[] args) {

        PlayGround playGround1 = new PlayGround();
        playGround1.setGroundId(1);
        playGround1.setGroundName("Melbourne Cricket Ground");
        playGround1.setLocation("Melbourne, Australia");
        playGround1.setCapacity("100,024");
        playGround1.setSport("Cricket");
        playGround1.setOpenedOn("1853");
        playGround1.setOwner("Government of Victoria");
        System.out.println("The Ground ID is : " + playGround1.getGroundId());
        System.out.println("The Ground Name is : " + playGround1.getGroundName());
        System.out.println("The Location is : " + playGround1.getLocation());
        System.out.println("The Capacity is : " + playGround1.getCapacity());
        System.out.println("The Sport is : " + playGround1.getSport());
        System.out.println("The Opened On is : " + playGround1.getOpenedOn());
        System.out.println("The Owner is : " + playGround1.getOwner());

        PlayGround playGround2 = new PlayGround();
        playGround2.setGroundId(2);
        playGround2.setGroundName("Narendra Modi Stadium");
        playGround2.setLocation("Ahmedabad, India");
        playGround2.setCapacity("132,000");
        playGround2.setSport("Cricket");
        playGround2.setOpenedOn("1983");
        playGround2.setOwner("Gujarat Cricket Association");
        System.out.println("The Ground ID is : " + playGround2.getGroundId());
        System.out.println("The Ground Name is : " + playGround2.getGroundName());
        System.out.println("The Location is : " + playGround2.getLocation());
        System.out.println("The Capacity is : " + playGround2.getCapacity());
        System.out.println("The Sport is : " + playGround2.getSport());
        System.out.println("The Opened On is : " + playGround2.getOpenedOn());
        System.out.println("The Owner is : " + playGround2.getOwner());

        PlayGround playGround3 = new PlayGround();
        playGround3.setGroundId(3);
        playGround3.setGroundName("Camp Nou");
        playGround3.setLocation("Barcelona, Spain");
        playGround3.setCapacity("99,354");
        playGround3.setSport("Football");
        playGround3.setOpenedOn("1957");
        playGround3.setOwner("FC Barcelona");
        System.out.println("The Ground ID is : " + playGround3.getGroundId());
        System.out.println("The Ground Name is : " + playGround3.getGroundName());
        System.out.println("The Location is : " + playGround3.getLocation());
        System.out.println("The Capacity is : " + playGround3.getCapacity());
        System.out.println("The Sport is : " + playGround3.getSport());
        System.out.println("The Opened On is : " + playGround3.getOpenedOn());
        System.out.println("The Owner is : " + playGround3.getOwner());

        PlayGround playGround4 = new PlayGround();
        playGround4.setGroundId(4);
        playGround4.setGroundName("Wembley Stadium");
        playGround4.setLocation("London, UK");
        playGround4.setCapacity("90,000");
        playGround4.setSport("Football");
        playGround4.setOpenedOn("2007");
        playGround4.setOwner("The Football Association");
        System.out.println("The Ground ID is : " + playGround4.getGroundId());
        System.out.println("The Ground Name is : " + playGround4.getGroundName());
        System.out.println("The Location is : " + playGround4.getLocation());
        System.out.println("The Capacity is : " + playGround4.getCapacity());
        System.out.println("The Sport is : " + playGround4.getSport());
        System.out.println("The Opened On is : " + playGround4.getOpenedOn());
        System.out.println("The Owner is : " + playGround4.getOwner());

        PlayGround playGround5 = new PlayGround();
        playGround5.setGroundId(5);
        playGround5.setGroundName("Eden Gardens");
        playGround5.setLocation("Kolkata, India");
        playGround5.setCapacity("68,000");
        playGround5.setSport("Cricket");
        playGround5.setOpenedOn("1864");
        playGround5.setOwner("Cricket Association of Bengal");
        System.out.println("The Ground ID is : " + playGround5.getGroundId());
        System.out.println("The Ground Name is : " + playGround5.getGroundName());
        System.out.println("The Location is : " + playGround5.getLocation());
        System.out.println("The Capacity is : " + playGround5.getCapacity());
        System.out.println("The Sport is : " + playGround5.getSport());
        System.out.println("The Opened On is : " + playGround5.getOpenedOn());
        System.out.println("The Owner is : " + playGround5.getOwner());

        PlayGround playGround6 = new PlayGround();
        playGround6.setGroundId(6);
        playGround6.setGroundName("Lord's Cricket Ground");
        playGround6.setLocation("London, UK");
        playGround6.setCapacity("31,100");
        playGround6.setSport("Cricket");
        playGround6.setOpenedOn("1814");
        playGround6.setOwner("Marylebone Cricket Club");
        System.out.println("The Ground ID is : " + playGround6.getGroundId());
        System.out.println("The Ground Name is : " + playGround6.getGroundName());
        System.out.println("The Location is : " + playGround6.getLocation());
        System.out.println("The Capacity is : " + playGround6.getCapacity());
        System.out.println("The Sport is : " + playGround6.getSport());
        System.out.println("The Opened On is : " + playGround6.getOpenedOn());
        System.out.println("The Owner is : " + playGround6.getOwner());

        PlayGround playGround7 = new PlayGround();
        playGround7.setGroundId(7);
        playGround7.setGroundName("Old Trafford");
        playGround7.setLocation("Manchester, UK");
        playGround7.setCapacity("74,310");
        playGround7.setSport("Football");
        playGround7.setOpenedOn("1910");
        playGround7.setOwner("Manchester United");
        System.out.println("The Ground ID is : " + playGround7.getGroundId());
        System.out.println("The Ground Name is : " + playGround7.getGroundName());
        System.out.println("The Location is : " + playGround7.getLocation());
        System.out.println("The Capacity is : " + playGround7.getCapacity());
        System.out.println("The Sport is : " + playGround7.getSport());
        System.out.println("The Opened On is : " + playGround7.getOpenedOn());
        System.out.println("The Owner is : " + playGround7.getOwner());

        PlayGround playGround8 = new PlayGround();
        playGround8.setGroundId(8);
        playGround8.setGroundName("Madison Square Garden");
        playGround8.setLocation("New York, USA");
        playGround8.setCapacity("20,789");
        playGround8.setSport("Basketball");
        playGround8.setOpenedOn("1968");
        playGround8.setOwner("MSG Entertainment");
        System.out.println("The Ground ID is : " + playGround8.getGroundId());
        System.out.println("The Ground Name is : " + playGround8.getGroundName());
        System.out.println("The Location is : " + playGround8.getLocation());
        System.out.println("The Capacity is : " + playGround8.getCapacity());
        System.out.println("The Sport is : " + playGround8.getSport());
        System.out.println("The Opened On is : " + playGround8.getOpenedOn());
        System.out.println("The Owner is : " + playGround8.getOwner());

        PlayGround playGround9 = new PlayGround();
        playGround9.setGroundId(9);
        playGround9.setGroundName("Santiago Bernabéu");
        playGround9.setLocation("Madrid, Spain");
        playGround9.setCapacity("81,044");
        playGround9.setSport("Football");
        playGround9.setOpenedOn("1947");
        playGround9.setOwner("Real Madrid CF");
        System.out.println("The Ground ID is : " + playGround9.getGroundId());
        System.out.println("The Ground Name is : " + playGround9.getGroundName());
        System.out.println("The Location is : " + playGround9.getLocation());
        System.out.println("The Capacity is : " + playGround9.getCapacity());
        System.out.println("The Sport is : " + playGround9.getSport());
        System.out.println("The Opened On is : " + playGround9.getOpenedOn());
        System.out.println("The Owner is : " + playGround9.getOwner());

        PlayGround playGround10 = new PlayGround();
        playGround10.setGroundId(10);
        playGround10.setGroundName("Sydney Cricket Ground");
        playGround10.setLocation("Sydney, Australia");
        playGround10.setCapacity("48,000");
        playGround10.setSport("Cricket");
        playGround10.setOpenedOn("1848");
        playGround10.setOwner("SCG Trust");
        System.out.println("The Ground ID is : " + playGround10.getGroundId());
        System.out.println("The Ground Name is : " + playGround10.getGroundName());
        System.out.println("The Location is : " + playGround10.getLocation());
        System.out.println("The Capacity is : " + playGround10.getCapacity());
        System.out.println("The Sport is : " + playGround10.getSport());
        System.out.println("The Opened On is : " + playGround10.getOpenedOn());
        System.out.println("The Owner is : " + playGround10.getOwner());

        PlayGround playGround11 = new PlayGround();
        playGround11.setGroundId(11);
        playGround11.setGroundName("Anfield");
        playGround11.setLocation("Liverpool, UK");
        playGround11.setCapacity("61,276");
        playGround11.setSport("Football");
        playGround11.setOpenedOn("1884");
        playGround11.setOwner("Liverpool FC");
        System.out.println("The Ground ID is : " + playGround11.getGroundId());
        System.out.println("The Ground Name is : " + playGround11.getGroundName());
        System.out.println("The Location is : " + playGround11.getLocation());
        System.out.println("The Capacity is : " + playGround11.getCapacity());
        System.out.println("The Sport is : " + playGround11.getSport());
        System.out.println("The Opened On is : " + playGround11.getOpenedOn());
        System.out.println("The Owner is : " + playGround11.getOwner());

        PlayGround playGround12 = new PlayGround();
        playGround12.setGroundId(12);
        playGround12.setGroundName("Maracanã Stadium");
        playGround12.setLocation("Rio de Janeiro, Brazil");
        playGround12.setCapacity("78,838");
        playGround12.setSport("Football");
        playGround12.setOpenedOn("1950");
        playGround12.setOwner("Rio de Janeiro Government");
        System.out.println("The Ground ID is : " + playGround12.getGroundId());
        System.out.println("The Ground Name is : " + playGround12.getGroundName());
        System.out.println("The Location is : " + playGround12.getLocation());
        System.out.println("The Capacity is : " + playGround12.getCapacity());
        System.out.println("The Sport is : " + playGround12.getSport());
        System.out.println("The Opened On is : " + playGround12.getOpenedOn());
        System.out.println("The Owner is : " + playGround12.getOwner());

        PlayGround playGround13 = new PlayGround();
        playGround13.setGroundId(13);
        playGround13.setGroundName("Allianz Arena");
        playGround13.setLocation("Munich, Germany");
        playGround13.setCapacity("75,024");
        playGround13.setSport("Football");
        playGround13.setOpenedOn("2005");
        playGround13.setOwner("Bayern Munich");
        System.out.println("The Ground ID is : " + playGround13.getGroundId());
        System.out.println("The Ground Name is : " + playGround13.getGroundName());
        System.out.println("The Location is : " + playGround13.getLocation());
        System.out.println("The Capacity is : " + playGround13.getCapacity());
        System.out.println("The Sport is : " + playGround13.getSport());
        System.out.println("The Opened On is : " + playGround13.getOpenedOn());
        System.out.println("The Owner is : " + playGround13.getOwner());

        PlayGround playGround14 = new PlayGround();
        playGround14.setGroundId(14);
        playGround14.setGroundName("The O2 Arena");
        playGround14.setLocation("London, UK");
        playGround14.setCapacity("20,000");
        playGround14.setSport("Tennis");
        playGround14.setOpenedOn("2007");
        playGround14.setOwner("Anschutz Entertainment Group");
        System.out.println("The Ground ID is : " + playGround14.getGroundId());
        System.out.println("The Ground Name is : " + playGround14.getGroundName());
        System.out.println("The Location is : " + playGround14.getLocation());
        System.out.println("The Capacity is : " + playGround14.getCapacity());
        System.out.println("The Sport is : " + playGround14.getSport());
        System.out.println("The Opened On is : " + playGround14.getOpenedOn());
        System.out.println("The Owner is : " + playGround14.getOwner());

        PlayGround playGround15 = new PlayGround();
        playGround15.setGroundId(15);
        playGround15.setGroundName("Wankhede Stadium");
        playGround15.setLocation("Mumbai, India");
        playGround15.setCapacity("33,108");
        playGround15.setSport("Cricket");
        playGround15.setOpenedOn("1974");
        playGround15.setOwner("Mumbai Cricket Association");
        System.out.println("The Ground ID is : " + playGround15.getGroundId());
        System.out.println("The Ground Name is : " + playGround15.getGroundName());
        System.out.println("The Location is : " + playGround15.getLocation());
        System.out.println("The Capacity is : " + playGround15.getCapacity());
        System.out.println("The Sport is : " + playGround15.getSport());
        System.out.println("The Opened On is : " + playGround15.getOpenedOn());
        System.out.println("The Owner is : " + playGround15.getOwner());

        PlayGround playGround16 = new PlayGround();
        playGround16.setGroundId(16);
        playGround16.setGroundName("Stade de France");
        playGround16.setLocation("Saint-Denis, France");
        playGround16.setCapacity("80,698");
        playGround16.setSport("Rugby");
        playGround16.setOpenedOn("1998");
        playGround16.setOwner("Consortium Stade de France");
        System.out.println("The Ground ID is : " + playGround16.getGroundId());
        System.out.println("The Ground Name is : " + playGround16.getGroundName());
        System.out.println("The Location is : " + playGround16.getLocation());
        System.out.println("The Capacity is : " + playGround16.getCapacity());
        System.out.println("The Sport is : " + playGround16.getSport());
        System.out.println("The Opened On is : " + playGround16.getOpenedOn());
        System.out.println("The Owner is : " + playGround16.getOwner());

        PlayGround playGround17 = new PlayGround();
        playGround17.setGroundId(17);
        playGround17.setGroundName("Signal Iduna Park");
        playGround17.setLocation("Dortmund, Germany");
        playGround17.setCapacity("81,365");
        playGround17.setSport("Football");
        playGround17.setOpenedOn("1974");
        playGround17.setOwner("Borussia Dortmund");
        System.out.println("The Ground ID is : " + playGround17.getGroundId());
        System.out.println("The Ground Name is : " + playGround17.getGroundName());
        System.out.println("The Location is : " + playGround17.getLocation());
        System.out.println("The Capacity is : " + playGround17.getCapacity());
        System.out.println("The Sport is : " + playGround17.getSport());
        System.out.println("The Opened On is : " + playGround17.getOpenedOn());
        System.out.println("The Owner is : " + playGround17.getOwner());

        PlayGround playGround18 = new PlayGround();
        playGround18.setGroundId(18);
        playGround18.setGroundName("Fenway Park");
        playGround18.setLocation("Boston, USA");
        playGround18.setCapacity("37,755");
        playGround18.setSport("Baseball");
        playGround18.setOpenedOn("1912");
        playGround18.setOwner("Fenway Sports Group");
        System.out.println("The Ground ID is : " + playGround18.getGroundId());
        System.out.println("The Ground Name is : " + playGround18.getGroundName());
        System.out.println("The Location is : " + playGround18.getLocation());
        System.out.println("The Capacity is : " + playGround18.getCapacity());
        System.out.println("The Sport is : " + playGround18.getSport());
        System.out.println("The Opened On is : " + playGround18.getOpenedOn());
        System.out.println("The Owner is : " + playGround18.getOwner());

        PlayGround playGround19 = new PlayGround();
        playGround19.setGroundId(19);
        playGround19.setGroundName("The Rose Bowl");
        playGround19.setLocation("Pasadena, USA");
        playGround19.setCapacity("92,542");
        playGround19.setSport("American Football");
        playGround19.setOpenedOn("1922");
        playGround19.setOwner("City of Pasadena");
        System.out.println("The Ground ID is : " + playGround19.getGroundId());
        System.out.println("The Ground Name is : " + playGround19.getGroundName());
        System.out.println("The Location is : " + playGround19.getLocation());
        System.out.println("The Capacity is : " + playGround19.getCapacity());
        System.out.println("The Sport is : " + playGround19.getSport());
        System.out.println("The Opened On is : " + playGround19.getOpenedOn());
        System.out.println("The Owner is : " + playGround19.getOwner());

        PlayGround playGround20 = new PlayGround();
        playGround20.setGroundId(20);
        playGround20.setGroundName("Yankee Stadium");
        playGround20.setLocation("Bronx, USA");
        playGround20.setCapacity("46,537");
        playGround20.setSport("Baseball");
        playGround20.setOpenedOn("2009");
        playGround20.setOwner("Yankee Global Enterprises");
        System.out.println("The Ground ID is : " + playGround20.getGroundId());
        System.out.println("The Ground Name is : " + playGround20.getGroundName());
        System.out.println("The Location is : " + playGround20.getLocation());
        System.out.println("The Capacity is : " + playGround20.getCapacity());
        System.out.println("The Sport is : " + playGround20.getSport());
        System.out.println("The Opened On is : " + playGround20.getOpenedOn());
        System.out.println("The Owner is : " + playGround20.getOwner());

        PlayGround playGround21 = new PlayGround();
        playGround21.setGroundId(21);
        playGround21.setGroundName("San Siro");
        playGround21.setLocation("Milan, Italy");
        playGround21.setCapacity("80,018");
        playGround21.setSport("Football");
        playGround21.setOpenedOn("1926");
        playGround21.setOwner("Municipality of Milan");
        System.out.println("The Ground ID is : " + playGround21.getGroundId());
        System.out.println("The Ground Name is : " + playGround21.getGroundName());
        System.out.println("The Location is : " + playGround21.getLocation());
        System.out.println("The Capacity is : " + playGround21.getCapacity());
        System.out.println("The Sport is : " + playGround21.getSport());
        System.out.println("The Opened On is : " + playGround21.getOpenedOn());
        System.out.println("The Owner is : " + playGround21.getOwner());

        PlayGround playGround22 = new PlayGround();
        playGround22.setGroundId(22);
        playGround22.setGroundName("M. Chinnaswamy Stadium");
        playGround22.setLocation("Bengaluru, India");
        playGround22.setCapacity("40,000");
        playGround22.setSport("Cricket");
        playGround22.setOpenedOn("1969");
        playGround22.setOwner("Karnataka State Cricket Association");
        System.out.println("The Ground ID is : " + playGround22.getGroundId());
        System.out.println("The Ground Name is : " + playGround22.getGroundName());
        System.out.println("The Location is : " + playGround22.getLocation());
        System.out.println("The Capacity is : " + playGround22.getCapacity());
        System.out.println("The Sport is : " + playGround22.getSport());
        System.out.println("The Opened On is : " + playGround22.getOpenedOn());
        System.out.println("The Owner is : " + playGround22.getOwner());

        PlayGround playGround23 = new PlayGround();
        playGround23.setGroundId(23);
        playGround23.setGroundName("Estádio da Luz");
        playGround23.setLocation("Lisbon, Portugal");
        playGround23.setCapacity("64,642");
        playGround23.setSport("Football");
        playGround23.setOpenedOn("2003");
        playGround23.setOwner("S.L. Benfica");
        System.out.println("The Ground ID is : " + playGround23.getGroundId());
        System.out.println("The Ground Name is : " + playGround23.getGroundName());
        System.out.println("The Location is : " + playGround23.getLocation());
        System.out.println("The Capacity is : " + playGround23.getCapacity());
        System.out.println("The Sport is : " + playGround23.getSport());
        System.out.println("The Opened On is : " + playGround23.getOpenedOn());
        System.out.println("The Owner is : " + playGround23.getOwner());

        PlayGround playGround24 = new PlayGround();
        playGround24.setGroundId(24);
        playGround24.setGroundName("Michigan Stadium");
        playGround24.setLocation("Ann Arbor, USA");
        playGround24.setCapacity("107,601");
        playGround24.setSport("American Football");
        playGround24.setOpenedOn("1927");
        playGround24.setOwner("University of Michigan");
        System.out.println("The Ground ID is : " + playGround24.getGroundId());
        System.out.println("The Ground Name is : " + playGround24.getGroundName());
        System.out.println("The Location is : " + playGround24.getLocation());
        System.out.println("The Capacity is : " + playGround24.getCapacity());
        System.out.println("The Sport is : " + playGround24.getSport());
        System.out.println("The Opened On is : " + playGround24.getOpenedOn());
        System.out.println("The Owner is : " + playGround24.getOwner());

        PlayGround playGround25 = new PlayGround();
        playGround25.setGroundId(25);
        playGround25.setGroundName("Johan Cruyff Arena");
        playGround25.setLocation("Amsterdam, Netherlands");
        playGround25.setCapacity("55,865");
        playGround25.setSport("Football");
        playGround25.setOpenedOn("1996");
        playGround25.setOwner("Government of Amsterdam");
        System.out.println("The Ground ID is : " + playGround25.getGroundId());
        System.out.println("The Ground Name is : " + playGround25.getGroundName());
        System.out.println("The Location is : " + playGround25.getLocation());
        System.out.println("The Capacity is : " + playGround25.getCapacity());
        System.out.println("The Sport is : " + playGround25.getSport());
        System.out.println("The Opened On is : " + playGround25.getOpenedOn());
        System.out.println("The Owner is : " + playGround25.getOwner());

        PlayGround playGround26 = new PlayGround();
        playGround26.setGroundId(26);
        playGround26.setGroundName("MetLife Stadium");
        playGround26.setLocation("East Rutherford, USA");
        playGround26.setCapacity("82,500");
        playGround26.setSport("American Football");
        playGround26.setOpenedOn("2010");
        playGround26.setOwner("MetLife Stadium Company");
        System.out.println("The Ground ID is : " + playGround26.getGroundId());
        System.out.println("The Ground Name is : " + playGround26.getGroundName());
        System.out.println("The Location is : " + playGround26.getLocation());
        System.out.println("The Capacity is : " + playGround26.getCapacity());
        System.out.println("The Sport is : " + playGround26.getSport());
        System.out.println("The Opened On is : " + playGround26.getOpenedOn());
        System.out.println("The Owner is : " + playGround26.getOwner());

        PlayGround playGround27 = new PlayGround();
        playGround27.setGroundId(27);
        playGround27.setGroundName("Soccer City");
        playGround27.setLocation("Johannesburg, South Africa");
        playGround27.setCapacity("94,736");
        playGround27.setSport("Football");
        playGround27.setOpenedOn("1989");
        playGround27.setOwner("City of Johannesburg");
        System.out.println("The Ground ID is : " + playGround27.getGroundId());
        System.out.println("The Ground Name is : " + playGround27.getGroundName());
        System.out.println("The Location is : " + playGround27.getLocation());
        System.out.println("The Capacity is : " + playGround27.getCapacity());
        System.out.println("The Sport is : " + playGround27.getSport());
        System.out.println("The Opened On is : " + playGround27.getOpenedOn());
        System.out.println("The Owner is : " + playGround27.getOwner());

        PlayGround playGround28 = new PlayGround();
        playGround28.setGroundId(28);
        playGround28.setGroundName("The Gabba");
        playGround28.setLocation("Brisbane, Australia");
        playGround28.setCapacity("42,000");
        playGround28.setSport("Cricket");
        playGround28.setOpenedOn("1895");
        playGround28.setOwner("Government of Queensland");
        System.out.println("The Ground ID is : " + playGround28.getGroundId());
        System.out.println("The Ground Name is : " + playGround28.getGroundName());
        System.out.println("The Location is : " + playGround28.getLocation());
        System.out.println("The Capacity is : " + playGround28.getCapacity());
        System.out.println("The Sport is : " + playGround28.getSport());
        System.out.println("The Opened On is : " + playGround28.getOpenedOn());
        System.out.println("The Owner is : " + playGround28.getOwner());

        PlayGround playGround29 = new PlayGround();
        playGround29.setGroundId(29);
        playGround29.setGroundName("Old Trafford Cricket Ground");
        playGround29.setLocation("Manchester, UK");
        playGround29.setCapacity("26,000");
        playGround29.setSport("Cricket");
        playGround29.setOpenedOn("1857");
        playGround29.setOwner("Lancashire County Cricket Club");
        System.out.println("The Ground ID is : " + playGround29.getGroundId());
        System.out.println("The Ground Name is : " + playGround29.getGroundName());
        System.out.println("The Location is : " + playGround29.getLocation());
        System.out.println("The Capacity is : " + playGround29.getCapacity());
        System.out.println("The Sport is : " + playGround29.getSport());
        System.out.println("The Opened On is : " + playGround29.getOpenedOn());
        System.out.println("The Owner is : " + playGround29.getOwner());

    }
}