class TraineeInfoExecutor {
    public static void main(String[] args) {
        TraineeInfo traineeInfo1 = new TraineeInfo();
        traineeInfo1.setTraineeId(101);
        traineeInfo1.setTraineeName("Alice Johnson");
        traineeInfo1.setCourse("Java Full Stack");
        traineeInfo1.setTrainer("Robert Smith");
        traineeInfo1.setEnrolledOn("2025-01-10");
        traineeInfo1.setCompletedOn("2025-03-15");
        traineeInfo1.setGrade("A");
        System.out.println("The Trainee ID is : " + traineeInfo1.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo1.getTraineeName());
        System.out.println("The Course is : " + traineeInfo1.getCourse());
        System.out.println("The Trainer is : " + traineeInfo1.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo1.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo1.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo1.getGrade());

        TraineeInfo traineeInfo2 = new TraineeInfo();
        traineeInfo2.setTraineeId(102);
        traineeInfo2.setTraineeName("Bob Miller");
        traineeInfo2.setCourse("Python Data Science");
        traineeInfo2.setTrainer("Sarah Connor");
        traineeInfo2.setEnrolledOn("2025-01-12");
        traineeInfo2.setCompletedOn("2025-03-20");
        traineeInfo2.setGrade("B+");
        System.out.println("The Trainee ID is : " + traineeInfo2.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo2.getTraineeName());
        System.out.println("The Course is : " + traineeInfo2.getCourse());
        System.out.println("The Trainer is : " + traineeInfo2.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo2.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo2.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo2.getGrade());

        TraineeInfo traineeInfo3 = new TraineeInfo();
        traineeInfo3.setTraineeId(103);
        traineeInfo3.setTraineeName("Charlie Davis");
        traineeInfo3.setCourse("Cloud Computing");
        traineeInfo3.setTrainer("Michael Brown");
        traineeInfo3.setEnrolledOn("2025-01-15");
        traineeInfo3.setCompletedOn("2025-03-25");
        traineeInfo3.setGrade("A-");
        System.out.println("The Trainee ID is : " + traineeInfo3.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo3.getTraineeName());
        System.out.println("The Course is : " + traineeInfo3.getCourse());
        System.out.println("The Trainer is : " + traineeInfo3.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo3.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo3.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo3.getGrade());

        TraineeInfo traineeInfo4 = new TraineeInfo();
        traineeInfo4.setTraineeId(104);
        traineeInfo4.setTraineeName("Diana Prince");
        traineeInfo4.setCourse("Cyber Security");
        traineeInfo4.setTrainer("David Wilson");
        traineeInfo4.setEnrolledOn("2025-01-18");
        traineeInfo4.setCompletedOn("2025-04-01");
        traineeInfo4.setGrade("A+");
        System.out.println("The Trainee ID is : " + traineeInfo4.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo4.getTraineeName());
        System.out.println("The Course is : " + traineeInfo4.getCourse());
        System.out.println("The Trainer is : " + traineeInfo4.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo4.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo4.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo4.getGrade());

        TraineeInfo traineeInfo5 = new TraineeInfo();
        traineeInfo5.setTraineeId(105);
        traineeInfo5.setTraineeName("Ethan Hunt");
        traineeInfo5.setCourse("Machine Learning");
        traineeInfo5.setTrainer("James Gosling");
        traineeInfo5.setEnrolledOn("2025-01-20");
        traineeInfo5.setCompletedOn("2025-04-05");
        traineeInfo5.setGrade("B");
        System.out.println("The Trainee ID is : " + traineeInfo5.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo5.getTraineeName());
        System.out.println("The Course is : " + traineeInfo5.getCourse());
        System.out.println("The Trainer is : " + traineeInfo5.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo5.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo5.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo5.getGrade());

        TraineeInfo traineeInfo6 = new TraineeInfo();
        traineeInfo6.setTraineeId(106);
        traineeInfo6.setTraineeName("Fiona Gallagher");
        traineeInfo6.setCourse("React Development");
        traineeInfo6.setTrainer("Dan Abramov");
        traineeInfo6.setEnrolledOn("2025-01-22");
        traineeInfo6.setCompletedOn("2025-04-10");
        traineeInfo6.setGrade("A");
        System.out.println("The Trainee ID is : " + traineeInfo6.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo6.getTraineeName());
        System.out.println("The Course is : " + traineeInfo6.getCourse());
        System.out.println("The Trainer is : " + traineeInfo6.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo6.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo6.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo6.getGrade());

        TraineeInfo traineeInfo7 = new TraineeInfo();
        traineeInfo7.setTraineeId(107);
        traineeInfo7.setTraineeName("George Miller");
        traineeInfo7.setCourse("DevOps Engineering");
        traineeInfo7.setTrainer("Gene Kim");
        traineeInfo7.setEnrolledOn("2025-01-25");
        traineeInfo7.setCompletedOn("2025-04-15");
        traineeInfo7.setGrade("B+");
        System.out.println("The Trainee ID is : " + traineeInfo7.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo7.getTraineeName());
        System.out.println("The Course is : " + traineeInfo7.getCourse());
        System.out.println("The Trainer is : " + traineeInfo7.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo7.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo7.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo7.getGrade());

        TraineeInfo traineeInfo8 = new TraineeInfo();
        traineeInfo8.setTraineeId(108);
        traineeInfo8.setTraineeName("Hannah Abbott");
        traineeInfo8.setCourse("Database Admin");
        traineeInfo8.setTrainer("Larry Ellison");
        traineeInfo8.setEnrolledOn("2025-01-28");
        traineeInfo8.setCompletedOn("2025-04-20");
        traineeInfo8.setGrade("A-");
        System.out.println("The Trainee ID is : " + traineeInfo8.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo8.getTraineeName());
        System.out.println("The Course is : " + traineeInfo8.getCourse());
        System.out.println("The Trainer is : " + traineeInfo8.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo8.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo8.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo8.getGrade());

        TraineeInfo traineeInfo9 = new TraineeInfo();
        traineeInfo9.setTraineeId(109);
        traineeInfo9.setTraineeName("Ian Wright");
        traineeInfo9.setCourse("Mobile App Dev");
        traineeInfo9.setTrainer("Chris Lattner");
        traineeInfo9.setEnrolledOn("2025-02-01");
        traineeInfo9.setCompletedOn("2025-04-25");
        traineeInfo9.setGrade("B");
        System.out.println("The Trainee ID is : " + traineeInfo9.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo9.getTraineeName());
        System.out.println("The Course is : " + traineeInfo9.getCourse());
        System.out.println("The Trainer is : " + traineeInfo9.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo9.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo9.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo9.getGrade());

        TraineeInfo traineeInfo10 = new TraineeInfo();
        traineeInfo10.setTraineeId(110);
        traineeInfo10.setTraineeName("Julia Roberts");
        traineeInfo10.setCourse("UI/UX Design");
        traineeInfo10.setTrainer("Steve Krug");
        traineeInfo10.setEnrolledOn("2025-02-05");
        traineeInfo10.setCompletedOn("2025-04-30");
        traineeInfo10.setGrade("A+");
        System.out.println("The Trainee ID is : " + traineeInfo10.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo10.getTraineeName());
        System.out.println("The Course is : " + traineeInfo10.getCourse());
        System.out.println("The Trainer is : " + traineeInfo10.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo10.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo10.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo10.getGrade());

        TraineeInfo traineeInfo11 = new TraineeInfo();
        traineeInfo11.setTraineeId(111);
        traineeInfo11.setTraineeName("Kevin Hart");
        traineeInfo11.setCourse("Data Analytics");
        traineeInfo11.setTrainer("Nate Silver");
        traineeInfo11.setEnrolledOn("2025-02-10");
        traineeInfo11.setCompletedOn("2025-05-05");
        traineeInfo11.setGrade("B+");
        System.out.println("The Trainee ID is : " + traineeInfo11.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo11.getTraineeName());
        System.out.println("The Course is : " + traineeInfo11.getCourse());
        System.out.println("The Trainer is : " + traineeInfo11.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo11.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo11.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo11.getGrade());

        TraineeInfo traineeInfo12 = new TraineeInfo();
        traineeInfo12.setTraineeId(112);
        traineeInfo12.setTraineeName("Laura Palmer");
        traineeInfo12.setCourse("Software Testing");
        traineeInfo12.setTrainer("James Bach");
        traineeInfo12.setEnrolledOn("2025-02-15");
        traineeInfo12.setCompletedOn("2025-05-10");
        traineeInfo12.setGrade("A");
        System.out.println("The Trainee ID is : " + traineeInfo12.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo12.getTraineeName());
        System.out.println("The Course is : " + traineeInfo12.getCourse());
        System.out.println("The Trainer is : " + traineeInfo12.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo12.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo12.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo12.getGrade());

        TraineeInfo traineeInfo13 = new TraineeInfo();
        traineeInfo13.setTraineeId(113);
        traineeInfo13.setTraineeName("Mike Tyson");
        traineeInfo13.setCourse("AWS Architect");
        traineeInfo13.setTrainer("Jeff Barr");
        traineeInfo13.setEnrolledOn("2025-02-18");
        traineeInfo13.setCompletedOn("2025-05-15");
        traineeInfo13.setGrade("A-");
        System.out.println("The Trainee ID is : " + traineeInfo13.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo13.getTraineeName());
        System.out.println("The Course is : " + traineeInfo13.getCourse());
        System.out.println("The Trainer is : " + traineeInfo13.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo13.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo13.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo13.getGrade());

        TraineeInfo traineeInfo14 = new TraineeInfo();
        traineeInfo14.setTraineeId(114);
        traineeInfo14.setTraineeName("Nina Simone");
        traineeInfo14.setCourse("Angular Mastery");
        traineeInfo14.setTrainer("Misko Hevery");
        traineeInfo14.setEnrolledOn("2025-02-20");
        traineeInfo14.setCompletedOn("2025-05-20");
        traineeInfo14.setGrade("B");
        System.out.println("The Trainee ID is : " + traineeInfo14.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo14.getTraineeName());
        System.out.println("The Course is : " + traineeInfo14.getCourse());
        System.out.println("The Trainer is : " + traineeInfo14.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo14.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo14.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo14.getGrade());

        TraineeInfo traineeInfo15 = new TraineeInfo();
        traineeInfo15.setTraineeId(115);
        traineeInfo15.setTraineeName("Oscar Wilde");
        traineeInfo15.setCourse("Artificial Intelligence");
        traineeInfo15.setTrainer("Andrew Ng");
        traineeInfo15.setEnrolledOn("2025-02-22");
        traineeInfo15.setCompletedOn("2025-05-25");
        traineeInfo15.setGrade("A+");
        System.out.println("The Trainee ID is : " + traineeInfo15.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo15.getTraineeName());
        System.out.println("The Course is : " + traineeInfo15.getCourse());
        System.out.println("The Trainer is : " + traineeInfo15.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo15.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo15.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo15.getGrade());

        TraineeInfo traineeInfo16 = new TraineeInfo();
        traineeInfo16.setTraineeId(116);
        traineeInfo16.setTraineeName("Peter Parker");
        traineeInfo16.setCourse("Node.js Backend");
        traineeInfo16.setTrainer("Ryan Dahl");
        traineeInfo16.setEnrolledOn("2025-02-25");
        traineeInfo16.setCompletedOn("2025-05-30");
        traineeInfo16.setGrade("A");
        System.out.println("The Trainee ID is : " + traineeInfo16.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo16.getTraineeName());
        System.out.println("The Course is : " + traineeInfo16.getCourse());
        System.out.println("The Trainer is : " + traineeInfo16.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo16.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo16.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo16.getGrade());

        TraineeInfo traineeInfo17 = new TraineeInfo();
        traineeInfo17.setTraineeId(117);
        traineeInfo17.setTraineeName("Quentin Tarantino");
        traineeInfo17.setCourse("Big Data Engineering");
        traineeInfo17.setTrainer("Doug Cutting");
        traineeInfo17.setEnrolledOn("2025-03-01");
        traineeInfo17.setCompletedOn("2025-06-05");
        traineeInfo17.setGrade("B+");
        System.out.println("The Trainee ID is : " + traineeInfo17.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo17.getTraineeName());
        System.out.println("The Course is : " + traineeInfo17.getCourse());
        System.out.println("The Trainer is : " + traineeInfo17.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo17.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo17.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo17.getGrade());

        TraineeInfo traineeInfo18 = new TraineeInfo();
        traineeInfo18.setTraineeId(118);
        traineeInfo18.setTraineeName("Rachel Green");
        traineeInfo18.setCourse("C# .NET Core");
        traineeInfo18.setTrainer("Anders Hejlsberg");
        traineeInfo18.setEnrolledOn("2025-03-05");
        traineeInfo18.setCompletedOn("2025-06-10");
        traineeInfo18.setGrade("A");
        System.out.println("The Trainee ID is : " + traineeInfo18.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo18.getTraineeName());
        System.out.println("The Course is : " + traineeInfo18.getCourse());
        System.out.println("The Trainer is : " + traineeInfo18.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo18.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo18.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo18.getGrade());

        TraineeInfo traineeInfo19 = new TraineeInfo();
        traineeInfo19.setTraineeId(119);
        traineeInfo19.setTraineeName("Steven Spielberg");
        traineeInfo19.setCourse("Blockchain Tech");
        traineeInfo19.setTrainer("Vitalik Buterin");
        traineeInfo19.setEnrolledOn("2025-03-08");
        traineeInfo19.setCompletedOn("2025-06-15");
        traineeInfo19.setGrade("A+");
        System.out.println("The Trainee ID is : " + traineeInfo19.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo19.getTraineeName());
        System.out.println("The Course is : " + traineeInfo19.getCourse());
        System.out.println("The Trainer is : " + traineeInfo19.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo19.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo19.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo19.getGrade());

        TraineeInfo traineeInfo20 = new TraineeInfo();
        traineeInfo20.setTraineeId(120);
        traineeInfo20.setTraineeName("Thomas Edison");
        traineeInfo20.setCourse("Embedded Systems");
        traineeInfo20.setTrainer("Jack Ganssle");
        traineeInfo20.setEnrolledOn("2025-03-10");
        traineeInfo20.setCompletedOn("2025-06-20");
        traineeInfo20.setGrade("B");
        System.out.println("The Trainee ID is : " + traineeInfo20.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo20.getTraineeName());
        System.out.println("The Course is : " + traineeInfo20.getCourse());
        System.out.println("The Trainer is : " + traineeInfo20.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo20.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo20.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo20.getGrade());

        TraineeInfo traineeInfo21 = new TraineeInfo();
        traineeInfo21.setTraineeId(121);
        traineeInfo21.setTraineeName("Ursula Corbero");
        traineeInfo21.setCourse("Kubernetes Admin");
        traineeInfo21.setTrainer("Brendan Burns");
        traineeInfo21.setEnrolledOn("2025-03-12");
        traineeInfo21.setCompletedOn("2025-06-25");
        traineeInfo21.setGrade("A-");
        System.out.println("The Trainee ID is : " + traineeInfo21.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo21.getTraineeName());
        System.out.println("The Course is : " + traineeInfo21.getCourse());
        System.out.println("The Trainer is : " + traineeInfo21.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo21.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo21.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo21.getGrade());

        TraineeInfo traineeInfo22 = new TraineeInfo();
        traineeInfo22.setTraineeId(122);
        traineeInfo22.setTraineeName("Victor Von Doom");
        traineeInfo22.setCourse("Quantum Computing");
        traineeInfo22.setTrainer("Richard Feynman");
        traineeInfo22.setEnrolledOn("2025-03-15");
        traineeInfo22.setCompletedOn("2025-06-30");
        traineeInfo22.setGrade("A+");
        System.out.println("The Trainee ID is : " + traineeInfo22.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo22.getTraineeName());
        System.out.println("The Course is : " + traineeInfo22.getCourse());
        System.out.println("The Trainer is : " + traineeInfo22.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo22.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo22.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo22.getGrade());

        TraineeInfo traineeInfo23 = new TraineeInfo();
        traineeInfo23.setTraineeId(123);
        traineeInfo23.setTraineeName("Wanda Maximoff");
        traineeInfo23.setCourse("Ethical Hacking");
        traineeInfo23.setTrainer("Kevin Mitnick");
        traineeInfo23.setEnrolledOn("2025-03-18");
        traineeInfo23.setCompletedOn("2025-07-05");
        traineeInfo23.setGrade("A");
        System.out.println("The Trainee ID is : " + traineeInfo23.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo23.getTraineeName());
        System.out.println("The Course is : " + traineeInfo23.getCourse());
        System.out.println("The Trainer is : " + traineeInfo23.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo23.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo23.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo23.getGrade());

        TraineeInfo traineeInfo24 = new TraineeInfo();
        traineeInfo24.setTraineeId(124);
        traineeInfo24.setTraineeName("Xavier Renegade");
        traineeInfo24.setCourse("GraphQL APIs");
        traineeInfo24.setTrainer("Lee Byron");
        traineeInfo24.setEnrolledOn("2025-03-20");
        traineeInfo24.setCompletedOn("2025-07-10");
        traineeInfo24.setGrade("B+");
        System.out.println("The Trainee ID is : " + traineeInfo24.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo24.getTraineeName());
        System.out.println("The Course is : " + traineeInfo24.getCourse());
        System.out.println("The Trainer is : " + traineeInfo24.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo24.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo24.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo24.getGrade());

        TraineeInfo traineeInfo25 = new TraineeInfo();
        traineeInfo25.setTraineeId(125);
        traineeInfo25.setTraineeName("Yara Shahidi");
        traineeInfo25.setCourse("Swift Programming");
        traineeInfo25.setTrainer("Angela Yu");
        traineeInfo25.setEnrolledOn("2025-03-22");
        traineeInfo25.setCompletedOn("2025-07-15");
        traineeInfo25.setGrade("A-");
        System.out.println("The Trainee ID is : " + traineeInfo25.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo25.getTraineeName());
        System.out.println("The Course is : " + traineeInfo25.getCourse());
        System.out.println("The Trainer is : " + traineeInfo25.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo25.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo25.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo25.getGrade());

        TraineeInfo traineeInfo26 = new TraineeInfo();
        traineeInfo26.setTraineeId(126);
        traineeInfo26.setTraineeName("Zane Truesdale");
        traineeInfo26.setCourse("Golang Services");
        traineeInfo26.setTrainer("Ken Thompson");
        traineeInfo26.setEnrolledOn("2025-03-25");
        traineeInfo26.setCompletedOn("2025-07-20");
        traineeInfo26.setGrade("A");
        System.out.println("The Trainee ID is : " + traineeInfo26.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo26.getTraineeName());
        System.out.println("The Course is : " + traineeInfo26.getCourse());
        System.out.println("The Trainer is : " + traineeInfo26.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo26.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo26.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo26.getGrade());

        TraineeInfo traineeInfo27 = new TraineeInfo();
        traineeInfo27.setTraineeId(127);
        traineeInfo27.setTraineeName("Arthur Curry");
        traineeInfo27.setCourse("Rust Systems");
        traineeInfo27.setTrainer("Graydon Hoare");
        traineeInfo27.setEnrolledOn("2025-03-28");
        traineeInfo27.setCompletedOn("2025-07-25");
        traineeInfo27.setGrade("B+");
        System.out.println("The Trainee ID is : " + traineeInfo27.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo27.getTraineeName());
        System.out.println("The Course is : " + traineeInfo27.getCourse());
        System.out.println("The Trainer is : " + traineeInfo27.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo27.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo27.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo27.getGrade());

        TraineeInfo traineeInfo28 = new TraineeInfo();
        traineeInfo28.setTraineeId(128);
        traineeInfo28.setTraineeName("Barry Allen");
        traineeInfo28.setCourse("High Perf Computing");
        traineeInfo28.setTrainer("Seymour Cray");
        traineeInfo28.setEnrolledOn("2025-04-01");
        traineeInfo28.setCompletedOn("2025-07-30");
        traineeInfo28.setGrade("A+");
        System.out.println("The Trainee ID is : " + traineeInfo28.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo28.getTraineeName());
        System.out.println("The Course is : " + traineeInfo28.getCourse());
        System.out.println("The Trainer is : " + traineeInfo28.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo28.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo28.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo28.getGrade());

        TraineeInfo traineeInfo29 = new TraineeInfo();
        traineeInfo29.setTraineeId(129);
        traineeInfo29.setTraineeName("Clark Kent");
        traineeInfo29.setCourse("Data Privacy Laws");
        traineeInfo29.setTrainer("Tim Berners-Lee");
        traineeInfo29.setEnrolledOn("2025-04-05");
        traineeInfo29.setCompletedOn("2025-08-05");
        traineeInfo29.setGrade("A");
        System.out.println("The Trainee ID is : " + traineeInfo29.getTraineeId());
        System.out.println("The Trainee Name is : " + traineeInfo29.getTraineeName());
        System.out.println("The Course is : " + traineeInfo29.getCourse());
        System.out.println("The Trainer is : " + traineeInfo29.getTrainer());
        System.out.println("The Enrolled On is : " + traineeInfo29.getEnrolledOn());
        System.out.println("The Completed On is : " + traineeInfo29.getCompletedOn());
        System.out.println("The Grade is : " + traineeInfo29.getGrade());
    }
}