class YouTubeVideoInfoExecutor {
    public static void main(String[] args) {
        YouTubeVideoInfo youTubeVideoInfo1 = new YouTubeVideoInfo();
        youTubeVideoInfo1.setVideoId(1);
        youTubeVideoInfo1.setVideoTitle("Java Tutorial for Beginners");
        youTubeVideoInfo1.setChannelName("Programming with Mosh");
        youTubeVideoInfo1.setViews("15M views");
        youTubeVideoInfo1.setLikes("450K likes");
        youTubeVideoInfo1.setUploadedOn("2020-03-25");
        youTubeVideoInfo1.setDuration("2:30:15");
        System.out.println("The Video ID is : " + youTubeVideoInfo1.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo1.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo1.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo1.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo1.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo1.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo1.getDuration());

        YouTubeVideoInfo youTubeVideoInfo2 = new YouTubeVideoInfo();
        youTubeVideoInfo2.setVideoId(2);
        youTubeVideoInfo2.setVideoTitle("Spring Boot Full Course");
        youTubeVideoInfo2.setChannelName("Amigoscode");
        youTubeVideoInfo2.setViews("2.1M views");
        youTubeVideoInfo2.setLikes("85K likes");
        youTubeVideoInfo2.setUploadedOn("2021-06-12");
        youTubeVideoInfo2.setDuration("4:15:30");
        System.out.println("The Video ID is : " + youTubeVideoInfo2.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo2.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo2.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo2.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo2.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo2.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo2.getDuration());

        YouTubeVideoInfo youTubeVideoInfo3 = new YouTubeVideoInfo();
        youTubeVideoInfo3.setVideoId(3);
        youTubeVideoInfo3.setVideoTitle("Python for Data Science");
        youTubeVideoInfo3.setChannelName("FreeCodeCamp");
        youTubeVideoInfo3.setViews("5M views");
        youTubeVideoInfo3.setLikes("120K likes");
        youTubeVideoInfo3.setUploadedOn("2022-01-05");
        youTubeVideoInfo3.setDuration("12:00:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo3.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo3.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo3.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo3.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo3.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo3.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo3.getDuration());

        YouTubeVideoInfo youTubeVideoInfo4 = new YouTubeVideoInfo();
        youTubeVideoInfo4.setVideoId(4);
        youTubeVideoInfo4.setVideoTitle("React JS Crash Course");
        youTubeVideoInfo4.setChannelName("Traversy Media");
        youTubeVideoInfo4.setViews("3.5M views");
        youTubeVideoInfo4.setLikes("95K likes");
        youTubeVideoInfo4.setUploadedOn("2021-02-18");
        youTubeVideoInfo4.setDuration("1:45:20");
        System.out.println("The Video ID is : " + youTubeVideoInfo4.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo4.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo4.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo4.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo4.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo4.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo4.getDuration());

        YouTubeVideoInfo youTubeVideoInfo5 = new YouTubeVideoInfo();
        youTubeVideoInfo5.setVideoId(5);
        youTubeVideoInfo5.setVideoTitle("SQL Tutorial - Full Database Course");
        youTubeVideoInfo5.setChannelName("Mike Dane");
        youTubeVideoInfo5.setViews("8M views");
        youTubeVideoInfo5.setLikes("200K likes");
        youTubeVideoInfo5.setUploadedOn("2018-07-10");
        youTubeVideoInfo5.setDuration("4:22:10");
        System.out.println("The Video ID is : " + youTubeVideoInfo5.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo5.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo5.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo5.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo5.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo5.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo5.getDuration());

        YouTubeVideoInfo youTubeVideoInfo6 = new YouTubeVideoInfo();
        youTubeVideoInfo6.setVideoId(6);
        youTubeVideoInfo6.setVideoTitle("C++ Full Course for Beginners");
        youTubeVideoInfo6.setChannelName("Bro Code");
        youTubeVideoInfo6.setViews("2.5M views");
        youTubeVideoInfo6.setLikes("110K likes");
        youTubeVideoInfo6.setUploadedOn("2022-05-30");
        youTubeVideoInfo6.setDuration("6:00:15");
        System.out.println("The Video ID is : " + youTubeVideoInfo6.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo6.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo6.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo6.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo6.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo6.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo6.getDuration());

        YouTubeVideoInfo youTubeVideoInfo7 = new YouTubeVideoInfo();
        youTubeVideoInfo7.setVideoId(7);
        youTubeVideoInfo7.setVideoTitle("HTML & CSS Full Course");
        youTubeVideoInfo7.setChannelName("SuperSimpleDev");
        youTubeVideoInfo7.setViews("10M views");
        youTubeVideoInfo7.setLikes("350K likes");
        youTubeVideoInfo7.setUploadedOn("2021-11-20");
        youTubeVideoInfo7.setDuration("6:31:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo7.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo7.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo7.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo7.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo7.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo7.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo7.getDuration());

        YouTubeVideoInfo youTubeVideoInfo8 = new YouTubeVideoInfo();
        youTubeVideoInfo8.setVideoId(8);
        youTubeVideoInfo8.setVideoTitle("Git and GitHub Tutorial");
        youTubeVideoInfo8.setChannelName("Kunis Kushwaha");
        youTubeVideoInfo8.setViews("1.2M views");
        youTubeVideoInfo8.setLikes("45K likes");
        youTubeVideoInfo8.setUploadedOn("2021-08-15");
        youTubeVideoInfo8.setDuration("2:10:45");
        System.out.println("The Video ID is : " + youTubeVideoInfo8.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo8.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo8.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo8.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo8.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo8.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo8.getDuration());

        YouTubeVideoInfo youTubeVideoInfo9 = new YouTubeVideoInfo();
        youTubeVideoInfo9.setVideoId(9);
        youTubeVideoInfo9.setVideoTitle("Docker for Absolute Beginners");
        youTubeVideoInfo9.setChannelName("TechWorld with Nana");
        youTubeVideoInfo9.setViews("4M views");
        youTubeVideoInfo9.setLikes("130K likes");
        youTubeVideoInfo9.setUploadedOn("2020-05-10");
        youTubeVideoInfo9.setDuration("2:15:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo9.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo9.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo9.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo9.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo9.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo9.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo9.getDuration());

        YouTubeVideoInfo youTubeVideoInfo10 = new YouTubeVideoInfo();
        youTubeVideoInfo10.setVideoId(10);
        youTubeVideoInfo10.setVideoTitle("Data Structures and Algorithms");
        youTubeVideoInfo10.setChannelName("Apna College");
        youTubeVideoInfo10.setViews("6.5M views");
        youTubeVideoInfo10.setLikes("280K likes");
        youTubeVideoInfo10.setUploadedOn("2022-03-12");
        youTubeVideoInfo10.setDuration("10:45:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo10.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo10.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo10.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo10.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo10.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo10.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo10.getDuration());

        YouTubeVideoInfo youTubeVideoInfo11 = new YouTubeVideoInfo();
        youTubeVideoInfo11.setVideoId(11);
        youTubeVideoInfo11.setVideoTitle("Node.js Ultimate Guide");
        youTubeVideoInfo11.setChannelName("Fireship");
        youTubeVideoInfo11.setViews("1.8M views");
        youTubeVideoInfo11.setLikes("90K likes");
        youTubeVideoInfo11.setUploadedOn("2021-04-20");
        youTubeVideoInfo11.setDuration("0:12:45");
        System.out.println("The Video ID is : " + youTubeVideoInfo11.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo11.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo11.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo11.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo11.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo11.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo11.getDuration());

        YouTubeVideoInfo youTubeVideoInfo12 = new YouTubeVideoInfo();
        youTubeVideoInfo12.setVideoId(12);
        youTubeVideoInfo12.setVideoTitle("AWS Cloud Practitioner Course");
        youTubeVideoInfo12.setChannelName("ExamPro");
        youTubeVideoInfo12.setViews("2.2M views");
        youTubeVideoInfo12.setLikes("55K likes");
        youTubeVideoInfo12.setUploadedOn("2020-09-14");
        youTubeVideoInfo12.setDuration("13:10:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo12.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo12.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo12.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo12.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo12.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo12.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo12.getDuration());

        YouTubeVideoInfo youTubeVideoInfo13 = new YouTubeVideoInfo();
        youTubeVideoInfo13.setVideoId(13);
        youTubeVideoInfo13.setVideoTitle("Machine Learning Specialization");
        youTubeVideoInfo13.setChannelName("DeepLearningAI");
        youTubeVideoInfo13.setViews("900K views");
        youTubeVideoInfo13.setLikes("40K likes");
        youTubeVideoInfo13.setUploadedOn("2022-06-01");
        youTubeVideoInfo13.setDuration("45:20:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo13.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo13.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo13.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo13.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo13.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo13.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo13.getDuration());

        YouTubeVideoInfo youTubeVideoInfo14 = new YouTubeVideoInfo();
        youTubeVideoInfo14.setVideoId(14);
        youTubeVideoInfo14.setVideoTitle("Kubernetes in 100 Seconds");
        youTubeVideoInfo14.setChannelName("Fireship");
        youTubeVideoInfo14.setViews("2.5M views");
        youTubeVideoInfo14.setLikes("115K likes");
        youTubeVideoInfo14.setUploadedOn("2021-12-05");
        youTubeVideoInfo14.setDuration("0:02:30");
        System.out.println("The Video ID is : " + youTubeVideoInfo14.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo14.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo14.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo14.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo14.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo14.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo14.getDuration());

        YouTubeVideoInfo youTubeVideoInfo15 = new YouTubeVideoInfo();
        youTubeVideoInfo15.setVideoId(15);
        youTubeVideoInfo15.setVideoTitle("Linux Terminal Tutorial");
        youTubeVideoInfo15.setChannelName("The Net Ninja");
        youTubeVideoInfo15.setViews("1.1M views");
        youTubeVideoInfo15.setLikes("38K likes");
        youTubeVideoInfo15.setUploadedOn("2019-10-18");
        youTubeVideoInfo15.setDuration("1:50:40");
        System.out.println("The Video ID is : " + youTubeVideoInfo15.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo15.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo15.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo15.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo15.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo15.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo15.getDuration());

        YouTubeVideoInfo youTubeVideoInfo16 = new YouTubeVideoInfo();
        youTubeVideoInfo16.setVideoId(16);
        youTubeVideoInfo16.setVideoTitle("How to use Figma");
        youTubeVideoInfo16.setChannelName("DesignCourse");
        youTubeVideoInfo16.setViews("3M views");
        youTubeVideoInfo16.setLikes("82K likes");
        youTubeVideoInfo16.setUploadedOn("2021-03-10");
        youTubeVideoInfo16.setDuration("0:55:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo16.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo16.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo16.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo16.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo16.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo16.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo16.getDuration());

        YouTubeVideoInfo youTubeVideoInfo17 = new YouTubeVideoInfo();
        youTubeVideoInfo17.setVideoId(17);
        youTubeVideoInfo17.setVideoTitle("PHP for Beginners");
        youTubeVideoInfo17.setChannelName("Dani Krossing");
        youTubeVideoInfo17.setViews("2M views");
        youTubeVideoInfo17.setLikes("44K likes");
        youTubeVideoInfo17.setUploadedOn("2020-01-22");
        youTubeVideoInfo17.setDuration("5:30:10");
        System.out.println("The Video ID is : " + youTubeVideoInfo17.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo17.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo17.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo17.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo17.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo17.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo17.getDuration());

        YouTubeVideoInfo youTubeVideoInfo18 = new YouTubeVideoInfo();
        youTubeVideoInfo18.setVideoId(18);
        youTubeVideoInfo18.setVideoTitle("Go Language Crash Course");
        youTubeVideoInfo18.setChannelName("Brad Traversy");
        youTubeVideoInfo18.setViews("1.4M views");
        youTubeVideoInfo18.setLikes("52K likes");
        youTubeVideoInfo18.setUploadedOn("2018-11-12");
        youTubeVideoInfo18.setDuration("1:40:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo18.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo18.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo18.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo18.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo18.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo18.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo18.getDuration());

        YouTubeVideoInfo youTubeVideoInfo19 = new YouTubeVideoInfo();
        youTubeVideoInfo19.setVideoId(19);
        youTubeVideoInfo19.setVideoTitle("Excel for Business");
        youTubeVideoInfo19.setChannelName("Kevin Stratvert");
        youTubeVideoInfo19.setViews("6M views");
        youTubeVideoInfo19.setLikes("140K likes");
        youTubeVideoInfo19.setUploadedOn("2021-05-08");
        youTubeVideoInfo19.setDuration("1:15:30");
        System.out.println("The Video ID is : " + youTubeVideoInfo19.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo19.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo19.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo19.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo19.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo19.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo19.getDuration());

        YouTubeVideoInfo youTubeVideoInfo20 = new YouTubeVideoInfo();
        youTubeVideoInfo20.setVideoId(20);
        youTubeVideoInfo20.setVideoTitle("Blockchain Explained");
        youTubeVideoInfo20.setChannelName("Simply Explained");
        youTubeVideoInfo20.setViews("4.2M views");
        youTubeVideoInfo20.setLikes("190K likes");
        youTubeVideoInfo20.setUploadedOn("2017-12-05");
        youTubeVideoInfo20.setDuration("0:06:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo20.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo20.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo20.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo20.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo20.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo20.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo20.getDuration());

        YouTubeVideoInfo youTubeVideoInfo21 = new YouTubeVideoInfo();
        youTubeVideoInfo21.setVideoId(21);
        youTubeVideoInfo21.setVideoTitle("Flutter Tutorial for Beginners");
        youTubeVideoInfo21.setChannelName("Net Ninja");
        youTubeVideoInfo21.setViews("2.8M views");
        youTubeVideoInfo21.setLikes("75K likes");
        youTubeVideoInfo21.setUploadedOn("2020-07-15");
        youTubeVideoInfo21.setDuration("4:30:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo21.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo21.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo21.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo21.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo21.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo21.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo21.getDuration());

        YouTubeVideoInfo youTubeVideoInfo22 = new YouTubeVideoInfo();
        youTubeVideoInfo22.setVideoId(22);
        youTubeVideoInfo22.setVideoTitle("Type Script Tutorial");
        youTubeVideoInfo22.setChannelName("Programming with Mosh");
        youTubeVideoInfo22.setViews("1.9M views");
        youTubeVideoInfo22.setLikes("68K likes");
        youTubeVideoInfo22.setUploadedOn("2022-02-10");
        youTubeVideoInfo22.setDuration("1:05:22");
        System.out.println("The Video ID is : " + youTubeVideoInfo22.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo22.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo22.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo22.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo22.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo22.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo22.getDuration());

        YouTubeVideoInfo youTubeVideoInfo23 = new YouTubeVideoInfo();
        youTubeVideoInfo23.setVideoId(23);
        youTubeVideoInfo23.setVideoTitle("Jenkins Full Course");
        youTubeVideoInfo23.setChannelName("Simplilearn");
        youTubeVideoInfo23.setViews("800K views");
        youTubeVideoInfo23.setLikes("15K likes");
        youTubeVideoInfo23.setUploadedOn("2021-08-25");
        youTubeVideoInfo23.setDuration("3:45:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo23.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo23.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo23.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo23.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo23.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo23.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo23.getDuration());

        YouTubeVideoInfo youTubeVideoInfo24 = new YouTubeVideoInfo();
        youTubeVideoInfo24.setVideoId(24);
        youTubeVideoInfo24.setVideoTitle("Unity Game Dev Tutorial");
        youTubeVideoInfo24.setChannelName("Brackeys");
        youTubeVideoInfo24.setViews("7M views");
        youTubeVideoInfo24.setLikes("250K likes");
        youTubeVideoInfo24.setUploadedOn("2020-04-01");
        youTubeVideoInfo24.setDuration("0:25:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo24.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo24.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo24.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo24.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo24.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo24.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo24.getDuration());

        YouTubeVideoInfo youTubeVideoInfo25 = new YouTubeVideoInfo();
        youTubeVideoInfo25.setVideoId(25);
        youTubeVideoInfo25.setVideoTitle("Ethical Hacking Full Course");
        youTubeVideoInfo25.setChannelName("Edureka");
        youTubeVideoInfo25.setViews("12M views");
        youTubeVideoInfo25.setLikes("400K likes");
        youTubeVideoInfo25.setUploadedOn("2019-12-20");
        youTubeVideoInfo25.setDuration("10:30:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo25.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo25.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo25.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo25.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo25.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo25.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo25.getDuration());

        YouTubeVideoInfo youTubeVideoInfo26 = new YouTubeVideoInfo();
        youTubeVideoInfo26.setVideoId(26);
        youTubeVideoInfo26.setVideoTitle("Postman Tutorial");
        youTubeVideoInfo26.setChannelName("Valentin Despa");
        youTubeVideoInfo26.setViews("1.5M views");
        youTubeVideoInfo26.setLikes("32K likes");
        youTubeVideoInfo26.setUploadedOn("2021-01-10");
        youTubeVideoInfo26.setDuration("1:20:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo26.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo26.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo26.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo26.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo26.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo26.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo26.getDuration());

        YouTubeVideoInfo youTubeVideoInfo27 = new YouTubeVideoInfo();
        youTubeVideoInfo27.setVideoId(27);
        youTubeVideoInfo27.setVideoTitle("Power BI Tutorial");
        youTubeVideoInfo27.setChannelName("Avi Singh");
        youTubeVideoInfo27.setViews("2.4M views");
        youTubeVideoInfo27.setLikes("48K likes");
        youTubeVideoInfo27.setUploadedOn("2020-09-05");
        youTubeVideoInfo27.setDuration("2:15:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo27.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo27.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo27.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo27.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo27.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo27.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo27.getDuration());

        YouTubeVideoInfo youTubeVideoInfo28 = new YouTubeVideoInfo();
        youTubeVideoInfo28.setVideoId(28);
        youTubeVideoInfo28.setVideoTitle("Kubernetes Helm Tutorial");
        youTubeVideoInfo28.setChannelName("Nana Janashia");
        youTubeVideoInfo28.setViews("600K views");
        youTubeVideoInfo28.setLikes("22K likes");
        youTubeVideoInfo28.setUploadedOn("2021-11-18");
        youTubeVideoInfo28.setDuration("0:45:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo28.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo28.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo28.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo28.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo28.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo28.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo28.getDuration());

        YouTubeVideoInfo youTubeVideoInfo29 = new YouTubeVideoInfo();
        youTubeVideoInfo29.setVideoId(29);
        youTubeVideoInfo29.setVideoTitle("Deep Learning with PyTorch");
        youTubeVideoInfo29.setChannelName("Daniel Bourke");
        youTubeVideoInfo29.setViews("1.3M views");
        youTubeVideoInfo29.setLikes("50K likes");
        youTubeVideoInfo29.setUploadedOn("2022-10-12");
        youTubeVideoInfo29.setDuration("25:40:00");
        System.out.println("The Video ID is : " + youTubeVideoInfo29.getVideoId());
        System.out.println("The Video Title is : " + youTubeVideoInfo29.getVideoTitle());
        System.out.println("The Channel Name is : " + youTubeVideoInfo29.getChannelName());
        System.out.println("The Views is : " + youTubeVideoInfo29.getViews());
        System.out.println("The Likes is : " + youTubeVideoInfo29.getLikes());
        System.out.println("The Uploaded On is : " + youTubeVideoInfo29.getUploadedOn());
        System.out.println("The Duration is : " + youTubeVideoInfo29.getDuration());
    }
}